Add Wynncraft Content Team Nametag
Wynntils/Wynntils-Legacy pull request #143
Opened 2019-09-21 12:01 UTC by Sockmower

2019-09-21 17:00 UTC, Sockmower commented
Tested to not show name tag on vip+ users, another content team member couldn't be found on main but it worked on our build server, I'll try and test on main soon.

2019-09-21 19:54 UTC, Sockmower commented
Just tested on main and is fully working as intended.

2019-09-21 22:16 UTC, HeyZeer0 requested changes

2019-09-21 22:16 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/NametagManager.java
> +    private static final NametagLabel wynnContentTeamLabel = new NametagLabel(MinecraftChatColors.DARK_AQUA, "Wynncraft Content Team", 0.7f);
Please rename the tag name to Wynncraft CT, otherwise, it will be insanely big

2019-09-22 01:28 UTC, HeyZeer0 approved these changes

2019-09-22 01:28 UTC, merged