Quest book continuity changes, territory locate feature and a few bug fixes
Wynntils/Wynntils-Legacy pull request #218
Opened 2020-06-18 08:37 UTC by aws404

This PR makes some minor modifications to how some old features work as well as adding a few new ones.
**New Features**  
- Discovery menu upgrades
  - Adds new options to territories (both discovered and undiscovered) in the quest books discoveries menu (Using API), these are the ability to:
    - Left click to set the compass beacon to the centre of the territory
    - Middle click to show the territory on the world map
    - Right click to do both
  - Adds reload button to force a reload of the discovery data (similar to quests menu)
  - Moved the discoveries progress indicator into the discoveries menu (used to be in quests menu) and split into separate territories/world and secret icons.
- Quests menu upgrades
  - Remove discovery progress icon (moved to discovery page)
  - Made mini-quest wiki links go to the individual sections (Quests#Gathering_posts, Quests#Slaying_posts) rather than the broader Mini-Quest header (Quests#Mini-quests)
  - Changed the system for establishing a quests wiki link to use the MediaWiki API rather than a list of manual overrides.  

**Other Changes**  
- Changed the actions under quests and discoveries (eg. Right click to open on the wiki!) to not be bolded and have a blank line between the actions and info. This follows the style used in other areas of the quest book and also removes clutter. [(image)](https://imgur.com/ih5unP3.png)
- Changed discoveries filters to use the more distinct background colour for selection (same as item guide)  

**Bug Fixes**  
- Fixed discoveries page back button returning users to the quest page rather than the main page
- Fixed the lag that occurred while the discoveries page search accumulated no results.
- FIxed the WebManager being called when not required in the discoveries page.
- Fixed crash when hovering discoveries/quest progress icons from the lobby

2020-06-18 15:34 UTC, HeyZeer0 requested changes
So, I do prefer the bold version, it gives a button feeling to the text.
You can make the open URL request async and it will look more smooth and avoid the extra boolean.

Nice commit as always <3

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/DiscoveriesPage.java
> +                        lore.add(TextFormatting.GREEN + "Left click to set compass beacon!");
Add bold here!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/DiscoveriesPage.java
> +                        lore.add(TextFormatting.YELLOW + "Right click to view on the map!");
Add bold here!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +                            lore.add(TextFormatting.RED + "Left click to unpin it!");
Add bold here!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +                            lore.add(TextFormatting.GREEN + "Left click to pin it!");
Add bold here!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +                        lore.add(TextFormatting.YELLOW + "Middle click to view on map!");
Add bold here!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +                    lore.add(TextFormatting.GOLD + "Right click to open on the wiki!");
Add bold here!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +    Boolean needsExtension = false;
Use the primitive boolean instead of the object one (boolean instead of Boolean)

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +                        needsExtension = !jsonOutput.get("query").getAsJsonObject().get("pages").getAsJsonObject().has("-1");
Instead of making it sync, make it async and place the openUrl here as well, this will avoid the needsExtension boolean and will not lock the client temporarily!

2020-06-18 15:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +                    }), false);
Change this to true to make it async, as referred to the commentary above

2020-06-19 02:01 UTC, aws404 commented
All done, I also added an onError to the request to just open the base page if there was an error.

2020-06-19 11:44 UTC, HeyZeer0 approved these changes

2020-06-19 11:44 UTC, merged