Changed info overlay to use an interface and new info overlay variables
Wynntils/Wynntils-Legacy pull request #231
Opened 2020-06-29 01:23 UTC by aws404

This rewrites portions of the InfoOverlay. InfoOverlay variables are now defined in the constructer of the InfoFormatter class in the form of the InfoModule interface assigned into a HashMap. This means when a string is found between to % signs, an attempt to get that key from the HashMap is made and if successful, the output is generated.
Some InfoModules also use the cache HashMap, replacing the variables that were being used previously.

**New Info Variables:**

- %kmph% - Kilometers per hour (1000 blocks per hour)
- %mana% - Current mana
- %mana_max% - Max mana
- %health% - Current health
- %health_max% - Max health
- %xp% - Current XP (Formatted)
- %xp_raw% - Current XP (Raw)
- %xp_req% - Required XP to level up (Formatted)
- %xp_pct% - Percentage XP to next level
- %horse_xp% - Current horse XP (Bascially percentage)
- %horse_level% - Current horse level (Jump/Speed level)
- %horse_level_max% - Max horse level
- %horse_tier% - The horse tier (ie. Brown Horse = 1, Black Horse = 2, ect)
- %pouch% - Amount of items in the ingredeint pouch
- %sp_timer% / %soulpoint_timer% - A simple timer until next soul point (Format: mm:ss)
- %sp_timer_s% / %soulpoint_timer_s% - Seconds until next soul point (in relation to minutes)
- %sp_timer_m% / %soulpoint_timer_m% - Minutes until next soul point (in relation to seconds)
- %sp% / %soulpoints% - current soul points
- %sp_max% / %soulpoints_max% - max soul points

**New Info Symbols**
- \M - mana symbol
- \H - health/heart symbol

A new setting was also added in order to list/copy all the variables in the same way as the presets.
The morse mount keybind also now attempts to find a saddle and spawn a horse if one is found.

2020-06-29 14:22 UTC, magicus approved these changes
Nice!

2020-06-30 05:23 UTC, coehlrich requested changes

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/core/framework/instances/PlayerInfo.java
> +            if (item.hasDisplayName() && item.getDisplayName().contains("Potion of Healing")) {
Should have a check for `item.isEmpty()`

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/core/framework/instances/PlayerInfo.java
> +            if (item.hasDisplayName() && item.getDisplayName().contains("Potion of Mana")) {
Should have a check for `item.isEmpty()`

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/core/framework/instances/PlayerInfo.java
> +            if (stack.hasDisplayName() && stack.getDisplayName().contains(" Horse")) {
Should have a check for `stack.isEmpty()`

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/core/framework/instances/PlayerInfo.java
> +            if (stack.hasDisplayName() && stack.getDisplayName().contains(" Horse")) {
Should have a check for `stack.isEmpty()`

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        if (count < 1000) return "" + count;
Use `Integer.toString`

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/InfoOverlay.java
> +
Remove this tab

2020-06-30 05:23 UTC, coehlrich commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +            return mountHorse(false);
The horse would need to spawn before the player can mount it

2020-06-30 10:22 UTC, aws404 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +            return mountHorse(false);
I changed the way this works to activate the mount when a new horse is spawned, it appears to be more stable this way. Is this a good solution?

2020-07-01 10:55 UTC, coehlrich approved these changes

2020-07-01 19:58 UTC, merged