renamed War Scream to Resistance in OverlayEvents
Wynntils/Wynntils-Legacy pull request #236
Opened 2020-07-13 16:22 UTC by TrapinchO

A really little thing. Previously you would get "War Scream" while using Vanish.

(This is my first PR I hope I didn't mess up)

2020-07-13 19:27 UTC, magicus requested changes
I think would be a step backwards. The term "Resistance" is not used in Wynncraft. If this gets mixed up with Vanish, we need to fix it, but I'd suggest instead figuring out properly the requirements for War Scream (and, for that matter, Vanish).

2020-07-13 19:29 UTC, magicus commented
One way to solve this is to complement ConsumableTimerOverlay.addBasicTimer with a "refillBasicTimer", which checks if there already is a timer with that name, and if so, updates it's timer.

This might still not be enough, if you have War Scream active and then get Vanish, it will likely mis-fire. We might need to look for both requirements for War Scream, that is, two different effects.

2020-07-13 19:33 UTC, TrapinchO commented
Wouldn't be simpler to creare timer for every effect you can get? (speed, resistance, strenght, invisibility)

2020-07-13 19:42 UTC, magicus commented
Simpler for the developer, maybe, but not as good a user experience. As a user, you don't really care that slow weapon speed is implemented using "mining fatigue". You have a slow weapon. And you do your War Scream spell.

2020-07-14 09:58 UTC, TrapinchO commented
> As a user, you don't really care that slow weapon speed is implemented using "mining fatigue". You have a slow weapon.
From what I know it is only decorative

This is not a final commit (I hope)

found bugs:
* after logging in you sometimes get "Vanish (27:xx)"
* "War Scream" timer might not appear during Vanish (not tested)

2020-07-14 13:50 UTC, magicus requested changes

2020-07-14 13:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            String timerName = "";
```suggestion
            String timerName;
```

2020-07-14 13:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            String timerName = "";
This will make timerName effectlively final, so you don't have to copy it before the lambda.

2020-07-14 13:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            else if (!isVanished) {
"isVanished" is true if and only if the previous if condition tested true, so you can just turn this into a simple else
```suggestion
            else {
```

2020-07-14 13:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +        // no idea what this does
It just extracts the actual effect of the layers of data structure that wrap around it. :)

2020-07-14 13:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +        // if effect belongs to player?
Yes, the client get all effects, even on mobs and other players. We ignore all other.

2020-07-14 13:58 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            String timerName = "";
I kept getting error before even when I had it this way, no idea why…
changed

2020-07-14 14:07 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            else if (!isVanished) {
No. Because each effect is resolved individuallly, without it you get both Vanish and War Scream (II).

2020-07-14 14:47 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            else if (!isVanished) {
Hm. Ok, if you say...

2020-07-15 07:37 UTC, TrapinchO commented
If no one has any suggestions or corrections I would call it finished.

2020-07-15 12:21 UTC, magicus approved these changes

2020-07-16 13:42 UTC, TrapinchO commented
@HeyZeer0 could you please review it?

2020-07-22 12:47 UTC, TrapinchO commented
Sorry, closed on accident

2020-07-22 17:42 UTC, magicus commented
You may want to update the title of the PR to reflect the actual changes.

2020-07-22 17:51 UTC, TrapinchO commented
> You may want to update the title of the PR to reflect the actual changes.

Done, thanks.

2020-07-23 17:55 UTC, HeyZeer0 commented
One thing needs to be tested, what happens if you vanish and receive the war scream effect?

2020-07-23 20:59 UTC, TrapinchO commented
In theory you shouldn't get it.

It might be possible to add "if effect is 'resistance' and 'isVanish' is true set 'isVanish' to false" after the "War Scream" check (before the last "else") 
(so it would only disable when "invisibility" is resolved and "War Scream" is skipped), however I am away from my pc (and propably won't be for about a month) so I can't test it.

2020-07-25 17:56 UTC, TrapinchO commented
Fixed.

The only potential problem is when using vanish I (below lv. 26) isVanished might get stuck to true (which shouldn't be problem though)

2020-07-28 15:24 UTC, TrapinchO commented
@HeyZeer0 I think it is ready to merge

2020-08-02 12:39 UTC, TrapinchO commented
@HeyZeer0 do you want to accept the PR? If yes, do you want changes to the code?

2020-08-05 13:09 UTC, merged