added button to open discoveries
Wynntils/Wynntils-Legacy pull request #245
Opened 2020-08-27 18:27 UTC by TrapinchO

Not sure if it works but there is nothing that should break it (since it is one copied line of code)

2020-08-28 16:35 UTC, TrapinchO commented
Made IDE working.
There were no problems with opening discoveries.

2020-08-30 12:54 UTC, TrapinchO commented
Sorry from the info options, dodn't realize I didn't do it on wrong branch (its late now).

Everything should work without crash

2020-08-30 13:41 UTC, HeyZeer0 requested changes

2020-08-30 13:41 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +                    return territory.equals("") ? "" : WebManager.getTerritories().get(territory).getGuild();
instead of ```.equals("")``` use ```.isEmpty()```

2020-08-30 13:41 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +                    return territory.equals("") ? "" : WebManager.getTerritories().get(territory).getGuildPrefix();
instead of ```.equals("")``` use ```.isEmpty()```

2020-08-30 13:41 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +            double compassX = compass.getX();
Use ``location.distance(new Location(Minecraft.getMinecraft().player))`` instead

2020-08-30 13:45 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +            double compassX = compass.getX();
instead of?

2020-08-30 13:50 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +            double compassX = compass.getX();
the whole calculation you made

2020-08-30 19:30 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +                    return territory.equals("") ? "" : WebManager.getTerritories().get(territory).getGuild();
done

2020-08-30 19:30 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +                    return territory.equals("") ? "" : WebManager.getTerritories().get(territory).getGuildPrefix();
done

2020-08-30 19:32 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +            double compassX = compass.getX();
I think you have to show me the code. I have no idea what you mean

2020-08-31 10:51 UTC, HeyZeer0 requested changes

2020-08-31 10:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +            return String.valueOf(MathHelper.floor(MathHelper.sqrt((compass.getX() - playerPos.getX()) * (compass.getX() - playerPos.getX())
replace this with ```compass.distance(playerPos);```

2020-08-31 11:09 UTC, HeyZeer0 requested changes

2020-08-31 11:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +
Remove this empty space :googlycatnotlikethistriggered:

2020-08-31 11:16 UTC, HeyZeer0 approved these changes

2020-08-31 11:17 UTC, merged