Allow accessorries to be shift-clicked on/off
Wynntils/Wynntils-Legacy pull request #266
Opened 2020-10-21 00:53 UTC by P0keDev

Adds a toggleable feature to let accessories be shift clicked as if they were armor pieces.

2020-10-21 10:50 UTC, magicus requested changes

2020-10-21 10:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                e.setCanceled(true);
Just like when equipping items from the inventory,  the setCancel should come only after you are sure to have found an empty slot.  I think..?

2020-10-21 18:03 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                e.setCanceled(true);
As long as the hotbar is full (which it will be if that code is reached), the shift-click won't do anything anyway so I cancel it regardless.

2020-10-22 07:50 UTC, magicus approved these changes

2020-10-22 07:50 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                e.setCanceled(true);
Okay, I see your point. It will work just fine. I still think it would be clearer for the next person reading this code if the cancelling is done in tandem with setting an accessoryDestinationSlot, but if you don't want to change that, I'm fine with the code as-is.

2020-10-22 21:18 UTC, HeyZeer0 approved these changes
LGTM once everything was addressed

2020-10-22 21:18 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/ItemUtils.java
> +    public static ItemType getItemType(ItemStack item) {
Please add documentation on what this method does, just for future reference

2020-10-22 21:18 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (!Reference.onWorld || accessoryDestinationSlot == -1) return;
check if the tick phase is on END otherwise, the event will be triggered twice which could cause some problems

2020-10-22 22:48 UTC, magicus approved these changes
I'm happy. Thanks for improving readability! (And for implementing this feature!)

2020-10-22 23:18 UTC, merged