Middle-click to view player's gear
Wynntils/Wynntils-Legacy pull request #267
Opened 2020-11-02 02:35 UTC by P0keDev

While looking at a player, middle-click (changeable under control settings) to open a GUI and view their armor and held item.

![2020-11-01_18 18 29](https://user-images.githubusercontent.com/3767283/97824422-b85dc500-1c70-11eb-9bb0-3d9962ecff37.png)
![image](https://user-images.githubusercontent.com/3767283/97824429-bf84d300-1c70-11eb-9bd0-504376c89a7e.png)
![image](https://user-images.githubusercontent.com/3767283/97824517-05419b80-1c71-11eb-9294-661ee29f55de.png)

2020-11-09 10:39 UTC, HeyZeer0 requested changes
nice work on this!

2020-11-09 10:39 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/enums/InternalIdentification.java
> +public enum InternalIdentification {
needs to be moved to athena

2020-11-09 10:39 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (!(Minecraft.getMinecraft().currentScreen instanceof SkillPointLoadoutUI || Minecraft.getMinecraft().currentScreen instanceof GearViewerUI)) return;
Create a new type of container class, call it something like FakeContainer (ofcourse it will extend Container), and extends over SkillPointLoadoutUI and GearViewerUI, after that just do ``currentScreen instanceof FakeContainer``. 
Just for future easier scalability

2020-11-09 10:39 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/instances/ContainerGearViewer.java
> +
remove this space

2020-11-09 10:39 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +        CoreModule.getModule().registerKeyBinding("View Player's Gear", -98, "Wynntils", true, GearViewerUI::openGearViewer);
Are you sure there isn't a key enum for mouse buttons? (easier for visualizing in the future)

2020-11-10 05:10 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (!(Minecraft.getMinecraft().currentScreen instanceof SkillPointLoadoutUI || Minecraft.getMinecraft().currentScreen instanceof GearViewerUI)) return;
done

2020-11-10 05:10 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/instances/ContainerGearViewer.java
> +
fixed

2020-11-10 05:11 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +        CoreModule.getModule().registerKeyBinding("View Player's Gear", -98, "Wynntils", true, GearViewerUI::openGearViewer);
As far as I can tell Minecraft hard-codes the mouse codes as 100 - mouse button number, with no enum. For now I've added a comment to clarify.

2020-11-10 08:49 UTC, coehlrich commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +        CoreModule.getModule().registerKeyBinding("View Player's Gear", -98, "Wynntils", true, GearViewerUI::openGearViewer);
Fields with mouse button numbers was added in lwjgl3 from what i could find and Minecraft started using them directly instead of 100 - mouse button number.

I just send stuff like this when i find something that mojang fixed in newer versions (or in this case lwjgl fixing).

2020-11-10 15:34 UTC, HeyZeer0 approved these changes
LGTM once the Athena implementation is done.

2020-11-10 23:30 UTC, merged