Allows you to toggle between Y coordinate and direction in action bar
Wynntils/Wynntils-Legacy pull request #269
Opened 2020-11-08 12:43 UTC by UnfedNintendogs

2020-11-08 13:34 UTC, HeyZeer0 requested changes

2020-11-08 13:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/ActionBarOverlay.java
> +        else {
Don't break a line on this else!

2020-11-08 13:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +    @Setting(displayName = "Replace Direction on Action Bar", description = "Should the direction on the action bar be swapped for the Y coordinate?")
Provide a better description and name for your configuration, otherwise, players might be confused about it.

2020-11-09 05:48 UTC, UnfedNintendogs commented
Sorry this is such a mess... I tried to rename a commit and it didn't work in the way I intended

2020-11-09 10:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +    @Setting(displayName = "Replace Direction on Action Bar", description = "Should the direction on the action bar be swapped for the Y coordinate?")
bump

2020-11-10 15:35 UTC, HeyZeer0 requested changes

2020-11-10 15:35 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +    @Setting(displayName = "Replace Direction on Action Bar", description = "Should the action bar display the Y coordinate instead of the player's direction?")
Provide a better description and name for your configuration, otherwise, players might be confused about it.

2020-11-11 11:36 UTC, HeyZeer0 approved these changes

2020-11-11 11:36 UTC, merged

2020-11-11 12:30 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +    @Setting(displayName = "Use Height on Action Bar", description = "Should the action bar display how high the player is instead of their orientation?")
I see this is integrated already, so maybe not worth the effort. And maybe it's because English is not my native language, but this description sounds like the player is on drugs. I think "how high up" would be better. Someone who speaks English as their mother tongue  could certainly help out here.

2020-11-11 15:11 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +    @Setting(displayName = "Use Height on Action Bar", description = "Should the action bar display how high the player is instead of their orientation?")
lmao not even noticed