Added 2 keybinds
Wynntils/Wynntils-Legacy pull request #270
Opened 2020-11-11 13:18 UTC by TrapinchO

1) Open item guide -> NUMPAD 1
2) Open HUD configuration -> NONE

I can't get for some reason to the server in the testing environment, but it should work

2020-11-13 14:57 UTC, HeyZeer0 requested changes

2020-11-13 14:57 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/QuestBookModule.java
> +        registerKeyBinding("Open Item Guide", Keyboard.KEY_NUMPAD1, "Wynntils", true, () -> QuestBookPages.ITEMGUIDE.getPage().open(true));
We should not use Numpad for a frequent usable feature

2020-11-13 14:58 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/questbook/QuestBookModule.java
> +        registerKeyBinding("Open Item Guide", Keyboard.KEY_NUMPAD1, "Wynntils", true, () -> QuestBookPages.ITEMGUIDE.getPage().open(true));
What key do you propose then? We are running out of them

2020-11-14 02:00 UTC, HeyZeer0 approved these changes

2020-11-14 02:01 UTC, merged