Fixed gathering cooldown not working during prof speed bombs
Wynntils/Wynntils-Legacy pull request #271
Opened 2020-11-11 20:05 UTC by TrapinchO

This should fix the bug. Again, I could not test it ingame (the code is copied and the change is minimal though)

2020-11-12 07:52 UTC, P0keDev requested changes
A much better solution, instead of using redundant code, would be to use a regex expression like the chest cooldown timer does.

2020-11-12 08:09 UTC, TrapinchO commented
Due to my modding skills, I only copied code that (presumably) did the same thing except outside prof speed bombs.

2020-11-12 18:18 UTC, magicus approved these changes
Looks good now.

2020-11-12 19:20 UTC, P0keDev approved these changes

2020-11-13 14:56 UTC, HeyZeer0 approved these changes

2020-11-13 14:57 UTC, merged