Better item level/tier overlays
Wynntils/Wynntils-Legacy pull request #280
Opened 2020-12-18 06:16 UTC by phantamanta44

Currently, item level overlays are implemented with this hacky thing in `RarityColorOverlay` that just modifies stack sizes for identifiable items when the ctrl key is held. Not only is this a rather ugly implementation, but it also precludes the ability to show an overlay over stackable items, such as ingredients or powders, as it relies on the assumption that the item is unstackable.

This PR remedies this by tossing out the entire stack size trick entirely. Instead, it creates a class `WynnRenderItem extends RenderItem`, then uses reflection to inject an instance of this into `Minecraft#renderItem`. This means that all `renderItemOverlayIntoGUI` calls will go through `WynnRenderItem`, giving us the opportunity to intercept them and do our own rendering instead.

The solution for specifying the overlay text that I came up with is to create a new event `RenderEvent.DrawItemOverlay` which any interested party can listen for and use to modify the text that renders in the item overlay. Then, I've created a handler class `ItemLevelOverlay` in the utilities module that replicates the original item level overlay behaviour using the new event-based system. The exact features are:
* Combat level overlays for identified items, exactly as in the old implementation
* Combat level overlays for unidentified items, with a config option for toggling between displaying the entire level range or display only the average level
* Crafting level overlays for crafting ingredients
* Powder tier overlays, with a config option for toggling between roman and arabic numerals

![](https://media.discordapp.net/attachments/424990456435310602/789360021347106826/unknown.png?width=352&height=442)

2020-12-18 13:34 UTC, HeyZeer0 requested changes
Awesome work!
It's great to see that you perfectly followed our code patterns of creating events for future scalability.

Just these small changes and it LGTM!

2020-12-18 13:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/ItemUtils.java
> +    public static class CombatLevel {
We avoid using this kind of nested classes. When they are used by the same class it's fine, but when they are useful for other ones, we create proper files for them.

Move it to the following package: ` com.wynntils.core.utils.objects`

2020-12-18 13:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/framework/rendering/WynnRenderItem.java
> +        } else {
This else is not necessary! Replace it with a return for better code consistency.

2020-12-18 13:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemLevelOverlay.java
> +                } else {
This else is not necessary! Replace it with a return for better code consistency.

2020-12-18 23:01 UTC, HeyZeer0 approved these changes

2020-12-18 23:01 UTC, merged

2020-12-19 13:14 UTC, magicus commented
@phantamanta44 Nice! :) 🎉