Add conflict contexts for keybindings
Wynntils/Wynntils-Legacy pull request #281
Opened 2020-12-20 00:08 UTC by phantamanta44

Wynntils keybindings don't have conflict contexts, so they're all placed in the universal conflict context. This PR remedies this by assigning reasonable conflict contexts to most Wynntils keybindings. Additionally, it adds a new keybinding for the item level overlay.

2020-12-20 01:59 UTC, magicus approved these changes

2020-12-20 21:06 UTC, HeyZeer0 requested changes
LGTM once addressed, nice work on this

2020-12-20 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/framework/enums/wynntils/WynntilsConflictContext.java
> +    AMBIENT {
Mind adding documentation of what Ambient is supposed to do?

2020-12-22 01:05 UTC, HeyZeer0 approved these changes

2020-12-22 01:05 UTC, merged