Item guide adv search mode + other enhancements
Wynntils/Wynntils-Legacy pull request #283
Opened 2020-12-26 16:12 UTC by phantamanta44

This PR implements an "advanced search mode" for the item guide, which addresses two inconveniences I've encountered while playing Wynncraft:

1. It's inconvenient having to alt-tab over to WynnData every time you want to look up items on-the-fly while in-game.
2. The WynnData search paradigm (i.e. having many drop-down boxes to specify filters in) is very clunky, and it's awkward having to switch between the mouse and keyboard.

Advanced search mode remedies these problems by replacing Wynntils' simple name search with a tag-based search. This solves the first problem by building a more flexible item search engine directly into Wynntils and solves the second problem by being purely text-based, allowing for more fluid input. The basic search mode is still the default, and the advanced search mode can be reached via a toggle button in the item guide UI.

This PR also introduces a significant amount of new infrastructure for parsing and representing the item filters used by the 
advanced search mode. The more remarkable changes are:
* `ItemTier`, `ItemType` enums augmented with a function for "loosely" (i.e. accepting reasonable aliases) parsing enum constants from strings.
* `ItemProfile` augmented with methods for retrieving elemental damages and defences by `DamageType`. The values are cached in an enum map the first time they are computed.
* A new `Comparison` enum representing a relation between two orderables (i.e. the standard `<, ≤, =, ≥, >, =, ≠` relations)
* A new `SortDirection` enum representing either ascending or descending order.
* A new `ItemFilter` interface, representing a manner of filtering and sorting items in the item guide, as well as many implementations for filtering by common item properties and stats.
* A new `ItemSearchState` class, representing a chain of item filters that make up a search query.

The basic search mode has also been migrated to use this new infrastructure; it is now, in a sense, a GUI frontend for the underlying advanced search system.

Additionally, this PR adds a few enhancements for the item guide in general:

* The search bar can now be right-clicked to clear it, similar to JEI (also applies to other quest book pages).
* A longer search bar specifically for advanced item search, which can be enabled in the quest book config.
* Items in the item guide can now be shift+rclicked to display then on WynnData.
* If only one filter is selected in basic search mode, shift+clicking it will now toggle all the other filters back on.

Some current issues are:

* The long search bar may be off-screen with smaller GUI scales.
* The icon for the search mode toggle button is the same as the quest book refresh button, which may be confusing.

![](https://i.imgur.com/lAmn0fB.png)

2021-01-02 21:06 UTC, HeyZeer0 requested changes
Seems nicely done! These requests are initially just for code consistency. I'll review again once done!

Really great work!

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +        } else {
You can place a return here and remove the else.

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +        } else {
return here instead of an else

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                    lore.add(TextFormatting.GOLD + "Shift+RClick to open WynnData");
Right Click instead of RClick to maintain standards

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +        } else if (getSearchHandler().handleClick(mouseX, mouseY, mouseButton, selected)) {
else is unnecessary here, you returned above

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                if (searchState != null) {
this if can be done with a ternary operator:
`textField.setText(searchState != null ? searchState.toSearchString() : "")`

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                if (searchText != null) {
this if can be done with a ternary operator:
`textField.setText(searchText != null ? searchText : "")`

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            } else if (selected == 2) {
else is not necessary, just place return true on the above (since you're always returning true!).
The same thing applies to everything below!

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/ItemProfile.java
> +        parsedDefenses = new EnumMap<>(DamageType.class);
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/ItemProfile.java
> +            } else {
else can be replaced with a continue on the upper condition

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/ItemProfile.java
> +        if (parsedHealth == Integer.MIN_VALUE) parsedHealth = 0;
reverse this condition and call a return. Also, place a space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/ItemProfile.java
> +        return parsedAvgDamages;
space above this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                this.tooltip = tooltipBuilder.build();
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                if (!builder.filterTypes.isEmpty()) {
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                for (String line : builder.desc) {
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            return searchText;
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            if (sortFunction == null) {
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            ByStat byLevel = searchState.getFilter(ByStat.TYPE_COMBAT_LEVEL);
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            ItemFilter.ByRarity byRarity = searchState.getFilter(ItemFilter.ByRarity.TYPE);
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            ItemFilter.ByName byName = searchState.getFilter(ItemFilter.ByName.TYPE);
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            ItemFilter.ByType byType = searchState.getFilter(ItemFilter.ByType.TYPE);
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            switch (sortFunction) { // alphabetical is handled above
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            if (allowedTypes.size() < itemTypeArray.size()) {
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            return searchState;
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            return true;
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
>          }
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +        render.drawRect(Textures.UIs.quest_book, centerX - 169, centerY - 130, 0, 342, 339, 19);
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/instances/QuestBookPage.java
>          if (showSearchBar) {
invert condition and call a return.

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/helpers/ItemSearchState.java
> +        if (inQuotes) throw new ItemFilter.FilteringException("Mismatched quotes!");
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/helpers/ItemSearchState.java
> +        return searchState;
space before this

2021-01-02 21:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        return j == searchText.length();
space before this

2021-01-03 06:30 UTC, phantamanta44 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +        } else if (getSearchHandler().handleClick(mouseX, mouseY, mouseButton, selected)) {
i wouldn't normally use both, but the rest of the cases already used both `return` and `else`, so i just followed. i'll fix the rest of the cases too, while i'm at it, i guess

2021-01-03 06:35 UTC, phantamanta44 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +            } else if (selected == 2) {
this should really be a switch statement, actually. i only used the big if..else chain because i just copied over the one that was already previously in `ItemPage#mouseClicked`

2021-01-07 13:38 UTC, HeyZeer0 approved these changes

2021-01-07 13:38 UTC, merged