And 2 things to gameticker
Wynntils/Wynntils-Legacy pull request #286
Opened 2021-01-01 19:39 UTC by LukasmanMHdude

2021-01-01 19:52 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                return;
Since Wynntils use custon class selection screen (and you were not supposed  to read chat anyway), there is no point in having it send a message to the ticker.

Also maybe a setting for it would be great

2021-01-01 19:53 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                return;
idk how to code a setting, but I'll remove that part where it sends to gameticker (if t works how I think it does)

2021-01-01 19:56 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                return;
I can do it after this is merged if you want

Otherwise I would suggest mimicking existing code
https://github.com/Wynntils/Wynntils/blob/e94a4c746bd3394c1090f2b250e3190e8b22e9a8/src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java#L654

2021-01-01 20:04 UTC, DevChromium commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } else if (messageText.equals("Thank you for using the WynnPack. Enjoy the game!"))
Bracket missing

2021-01-01 20:05 UTC, DevChromium commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } else if (messageText.equals("Select a class! Each class is saved individually across all servers, you can come back at any time with /class and select another class!"))
Bracket missing

2021-01-02 19:47 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +
This is the old (and now removed) code for server restart timer right?

How did it appear here, it shouldn't?

2021-01-02 19:56 UTC, TrapinchO requested changes

2021-01-02 19:56 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                }
This is the old (and now removed) code for server restart timer right?

How did it appear here, it shouldn't?

2021-01-02 19:59 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                }
hmmm, prrbably whats causig the issue, lemme remove it (I most likely have an outdated fork)

2021-01-02 20:34 UTC, TrapinchO approved these changes
Seems good to me

2021-01-02 20:48 UTC, HeyZeer0 requested changes
LGTM after changes were made.

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +        if(OverlayConfig.GameUpdate.RedirectSystemMessages.INSTANCE.redirectRss) {
space after ifs

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } else if (messageText.equals("Loading Resource Pack...")) {
this else not necessary (you're returning above)

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +        if(OverlayConfig.GameUpdate.RedirectSystemMessages.INSTANCE.redirectClass) {
space after ifs

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } else if (messageText.equals("Your class has been automatically been selected. Use /class to change your class, or /toggle autojoin to turn this feature off.")) {
this else not necessary (you're returning above)

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +            public boolean redirectRss = true;
rename to redirectResourcePack and set it to false as default

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Automatically selected class!");
Replace with: "Automatically selected your last character!"

2021-01-02 20:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Select a class!");
Replace with: "Select a character!"

2021-01-02 21:08 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Select a charachter!");
typo: "charachter"

2021-01-02 21:09 UTC, HeyZeer0 requested changes

2021-01-02 21:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } if (messageText.equals("Loading Resource Pack...")) {
Break a line for the if

2021-01-02 21:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } if (messageText.equals("Your class has been automatically been selected. Use /class to change your class, or /toggle autojoin to turn this feature off.")) {
Break a line for the if

2021-01-02 21:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Automatically selected your last charachter!");
charachter? please don't rush typing! hahaha

2021-01-02 21:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Select a charachter!");
charachter? please don't rush typing! hahaha

2021-01-02 21:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +            public boolean redirectRss = true;
not solved!

2021-01-02 21:13 UTC, LukasmanMHdude commented
dang travis broke again

2021-01-02 21:14 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Select a charachter!");
I need Grammarly for github

2021-01-02 22:08 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +            public boolean redirectRss = true;
oops forgot to commit

2021-01-02 22:12 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Automatically selected your last character!");9i8u]=
"9i8u]=" ???

2021-01-02 22:14 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Automatically selected your last character!");9i8u]=
???

2021-01-02 22:15 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Automatically selected your last character!");9i8u]=
fixed

2021-01-02 22:16 UTC, LukasmanMHdude commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +            } if (messageText.equals("Your class has been automatically been selected. Use /class to change your class, or /toggle autojoin to turn this feature off.")) {
I (think) I fixe this, although not sure if I did it right

2021-01-02 22:16 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                GameUpdateOverlay.queueMessage(TextFormatting.GOLD + "Select a charachter!");
Get IntelliJ idea, grammarly for Java

2021-01-02 22:36 UTC, LukasmanMHdude commented
I fixed the most of the issues, not sure if I did the `ifs` right. Juest waiting for travis then I'll request a review from trap and you

2021-01-02 22:38 UTC, LukasmanMHdude commented
apparently, I can't request trapiho?

2021-01-02 22:38 UTC, LukasmanMHdude commented
oops

2021-01-02 22:39 UTC, TrapinchO commented
> apparently, I can't request trapiho?

Well, I am not a part of Wynntils, so I can't do much (look at my most recent PR, do I look like a capable coder?)

2021-01-03 01:23 UTC, HeyZeer0 approved these changes

2021-01-03 01:24 UTC, merged