Rewritten Blacksmith redirect message
Wynntils/Wynntils-Legacy pull request #287
Opened 2021-01-02 16:49 UTC by TrapinchO

I can change the formatting if you want

@HeyZeer0 please notice it

2021-01-02 17:15 UTC, magicus commented
I don't understand. What's the point? I can't see what has changed.

2021-01-02 17:17 UTC, TrapinchO commented
> I don't understand. What's the point? I can't see what has changed.

There was a TODO "Jesus Christ rewrite it", so I rewritted it.

2021-01-02 20:52 UTC, HeyZeer0 requested changes
Needs further review after changes.

2021-01-02 20:52 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                message2 = TextFormatting.LIGHT_PURPLE + "Sold " + total
Import TextFormatting.* as static to remove the TextFormating text, will make it cleaner

2021-01-02 20:52 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.startsWith("a")) { countTest[3]++; } // set
you can definitely use a regex with name identifications to match each rarity!

2021-01-02 21:06 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                message2 = TextFormatting.LIGHT_PURPLE + "Sold " + total
ok

2021-01-02 21:07 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.startsWith("a")) { countTest[3]++; } // set
This one only or all?

2021-01-02 21:18 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                message2 = TextFormatting.LIGHT_PURPLE + "Sold " + total
Did for blacksmith, might do the rest later

2021-01-02 22:17 UTC, magicus commented
I don't think this rewrite is any improvement. It's more or less just a reformatting of the same structure. I think the explicative comment might not be warranted -- it's not that bad -- but if you really want to rewrite it, you need to redo it in a more structured way.

For instance, create a holder class that holds the count of the different kinds of rarities, and with a parse() method that can take in a message and update the count correctly. This could in turn use a map with regexpes -> int:s for each rarity. And also a format() or getMessage() method which returns a properly formatted string. And to do this general, you would iterate over a map of rarities -> colors. (This might be available elsewhere.)

2021-01-02 22:18 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
You know that you could have just done `total += countTest`? 🤣

2021-01-02 22:19 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
What, I can add integer and integer array in java?

Wait, what?

2021-01-02 22:21 UTC, magicus requested changes
I think it's better to just remove the comment requesting a rewrite. Otherwise, a completely more structured way to do this is needed. The current patch is a regression in both style, readability and correctness. Sorry to be the deliverer of bad news.

2021-01-02 22:21 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
... or wait, that's not even. what you are doing. You are adding 1+2+3....countTest to total. That's not just inefficient, it's completely wrong.

2021-01-02 22:22 UTC, TrapinchO commented
> I don't think this rewrite is any improvement. It's more or less just a reformatting of the same structure. I think the explicative comment might not be warranted -- it's not that bad -- but if you really want to rewrite it, you need to redo it in a more structured way.
> 
> For instance, create a holder class that holds the count of the different kinds of rarities, and with a parse() method that can take in a message and update the count correctly. This could in turn use a map with regexpes -> int:s for each rarity. And also a format() or getMessage() method which returns a properly formatted string. And to do this general, you would iterate over a map of rarities -> colors. (This might be available elsewhere.)

I have no idea how (and why) I would make it this complicated.

Right now I am attempting to use regex to the the rarities somehow.

2021-01-02 22:24 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
I haven't found a better way to get a sum in an intenger array. Imo at least the sum is better than before, because at least i do not increment it in every if

2021-01-02 22:25 UTC, TrapinchO commented
> I think it's better to just remove the comment requesting a rewrite. Otherwise, a completely more structured way to do this is needed. The current patch is a regression in both style, readability and correctness. Sorry to be the deliverer of bad news.

Well, I have always wondered when it becomes "Just get away". It wasn't really a suprise since Zeer0 mentioned regex here, so you don't have to be sorry :)

2021-01-02 22:25 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
Ah, sorry, the countTest is the array.  It's a horrible name. 

Yes, I'm misreading the code. I see what you are trying to do. 

I would have used something along the lines of `IntStream.of(countTest).sum()` instead, but perhaps that's overdoing it.

Anyway, I think storing the values in an array like this is a bad idea. If anything, you should store it mapped with the rarities as keys.

2021-01-02 22:28 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
countTest was a placeholder name and then I forgot about it, sorry.

I saw this once and just asked "wtf", but yes, it could be used
```
IntStream.of(countTest).sum()
```

Imo better than 8 variables (+ 1 total).
I considered this, but since I have no idea how to initialise hash map with key-pairs already in I dropped it

2021-01-02 22:33 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            if (sold) { // normal selling
changed the 2 things (yes, I know it doesn't have much sense since I will propably rewrite it)

2021-01-02 22:39 UTC, magicus commented
Fair enough; the patch is likely correct -- as I said above, I thought I found an error with the totals, but this was not the case. I still fail to see how it is an improvement though. Now we have hard-coded indexes into an array instead of named variables. In what way do you think this is better? If you have an argument for this, I'd like to hear it. To me, a code piece of code that was quite understandable, like:
```
if (s.startsWith("b")) {
                         countLegendary++;
                         total++;
```
is now
```
 if (s.startsWith("b")) { countTest[4]++; } // legendary
 ```

Now suddenly everyone needs to agree that index 4 is legendary. And instead of enforcing this easily by the name, you have to add a comment. That is not an improvement.

I do agree that increasing the total in every if block is a bit silly. I would support a refactoring where the sum was extracted to the end.

2021-01-02 22:46 UTC, TrapinchO commented
> Fair enough; the patch is likely correct -- as I said above, I thought I found an error with the totals, but this was not the case. I still fail to see how it is an improvement though. Now we have hard-coded indexes into an array instead of named variables. In what way do you think this is better? If you have an argument for this, I'd like to hear it. To me, a code piece of code that was quite understandable, like:
> 
> ```
> if (s.startsWith("b")) {
>                          countLegendary++;
>                          total++;
> ```
> 
> is now
> 
> ```
>  if (s.startsWith("b")) { countTest[4]++; } // legendary
> ```
> 
> Now suddenly everyone needs to agree that index 4 is legendary. And instead of enforcing this easily by the name, you have to add a comment. That is not an improvement.
> 
> I do agree that increasing the total in every if block is a bit silly. I would support a refactoring where the sum was extracted to the end.

I thought the bad thing was the 8 variables there so I tried to make it look nice? in my eyes. I can't really say anything, it is me and well, you know my coding at least somewhat... (Which is why this resulted in me attempting to do redo it completely anyways)

If you tell me how to initialise hashmaps with content in it I can try to do it using these

2021-01-02 22:47 UTC, magicus commented
You have not extracted the common part of the scrapped and sold messages. It is still duplicated, and it's part of what made this code messy.

I still think we have a data class somewhere that connects rarity to their colors. If we do have that, and you wanted to clean this up, you should use it. If we do not have one, you should create one.

I assume the startsWith letters are color codes. You could match explicitly to the named color codes to make it clearer. I assume it would be the same colors that we use later on when formatting the resulting message, giving yet another opportunity to unify and clarify things. 

The strings that we look for do avoid mismatch ("5Blacksmith: ", "dYou sold me: ", etc) can be checked first, and if they match, we will do no further procesing. After that, you will have a simple 1-to-1 matching from color code to rarity type. This can, once again, be nicely supported by a map.

Any, or all, of these changes would constitute the kind of rewrite the author of the "Jesus Christ" rewrite comment meant.

2021-01-02 22:53 UTC, TrapinchO commented
> You have not extracted the common part of the scrapped and sold messages. It is still duplicated, and it's part of what made this code messy.

Actually I have no idea why I scrapped this one

> If we do not have one, you should create one.

I think I am lost enough already, thanks

> I assume the startsWith letters are color codes. You could match explicitly to the named color codes to make it clearer. I assume it would be the same colors that we use later on when formatting the resulting message, giving yet another opportunity to unify and clarify things.

I know and I am trying to work with this in the current attempt

> The strings that we look for do avoid mismatch ("5Blacksmith: ", "dYou sold me: ", etc) can be checked first, and if they match, we will do no further procesing. After that, you will have a simple 1-to-1 matching from color code to rarity type. This can, once again, be nicely supported by a map.

Good idea actually

> This can, once again, be nicely supported by a map.
.
> If you tell me how to initialise hashmaps with content in it I can try to do it using these

2021-01-02 22:55 UTC, magicus commented
We have an ItemTier class, but it is badly placed in com.wynntils.webapi.profiles.item.enums. I'm getting a bit rusty on the code base, perhaps HeyZeer0 has a good idea on where it should be moved so it could be shared by more parts of the code. From it you can get the rarity level name (or "item tier" name) and color, and and an arbitrarily index.

2021-01-02 23:03 UTC, magicus commented
We also have a lot of similar code with explicit code paths for all rarities in `HotbarOverlay`, `ItemPage`, `NametagManager`, `ItemIdentificationOverlay`, `RarityColorOverlay`, and a list of the rarity text colors rendered as CustomColor in `UtilitiesConfig`.

It would make sense to create a RarityLevel or ItemTier class that could support all these use cases.

2021-01-02 23:27 UTC, TrapinchO commented
> We have an ItemTier class, but it is badly placed in com.wynntils.webapi.profiles.item.enums. I'm getting a bit rusty on the code base, perhaps HeyZeer0 has a good idea on where it should be moved so it could be shared by more parts of the code. From it you can get the rarity level name (or "item tier" name) and color, and and an arbitrarily index.

Yet it is not useful for me because there is (presumably) no way to get the character that identifies the color from the color enum aside from the enum implementation.
Also it is missing crafted tied btw

2021-01-03 22:31 UTC, magicus commented
I think this is starting to look better! I was not aware of the EnumMap class; but it's perfect! Please rename the variable to something more descriptive. It is typically helpful to name maps and arrays using a plural -s, to indicate it contain many items (unless it end in -Map or -Array). So something like itemMap or `itemCounts`.

There is a way to get the color code.  Add something like this to ItemTier:
```
    public char getColorCode() {
        return color.charAt(1);
    }
```

Unfortunately the TextFormatting class does not export the color code letter separately, but only as part of the control string, where the letter is the second character. The ItemTier class also converts the incoming TextFormatting object in the constructor to a String, before storing it. Personally, I would have preferred to store it in its original form, and make the toString() call in getColor. In this case, it does not matter, since we have to take the detour with using toString().charAt(1), but, still... If you change it, I'll support you. :)

Furthermore, the order in ItemTier is odd. The SET tier does not really fit in with the rest, but it is usually listed (as in the Blacksmith selling message) between RARE and LEGENDARY. I have checked the usage of priority in ItemTier, and I think it's perfectly fine to reorder them to match the Blacksmith order.

2021-01-03 22:47 UTC, magicus commented
After that, you can compact the matching to something like:

```
char colorCode = s.charAt(0);
if (Character.isLetterOrDigit(colorCode)) {
  Optional<ItemTier> tier = ItemTier.fromColorCode(colorCode)
  tier.ifPresent(itemTier ->  itemCounts.put(itemTier, itemCounts.get(itemTier) + 1));
}
```

and add a method to the enum class to get the correct item tier from color code:
```
    public static Optional<ItemTier> fromColorCode(char ch) {
        return Stream.of(ItemTier.values()).filter(tier -> tier.getColorCode() == ch).findFirst();
    }
```

(code is not tested and might need some tweaking)

2021-01-03 22:47 UTC, TrapinchO commented
> I think this is starting to look better! I was not aware of the EnumMap class; but it's perfect! Please rename the variable to something more descriptive. It is typically helpful to name maps and arrays using a plural -s, to indicate it contain many items (unless it end in -Map or -Array). So something like itemMap or itemCounts.

Since I didn't think the idea would work (like regex etc.) it is just a quick testing name

> There is a way to get the color code. Add something like this to ItemTier:
> ```
    public char getColorCode() {
        return color.charAt(1);
    } ```

I do not see a reason for it but sure.

> Unfortunately the TextFormatting class does not export the color code letter separately, but only as part of the control string, where the letter is the second character. The ItemTier class also converts the incoming TextFormatting object in the constructor to a String, before storing it. Personally, I would have preferred to store it in its original form, and make the toString() call in getColor. In this case, it does not matter, since we have to take the detour with using toString().charAt(1), but, still... If you change it, I'll support you. :)
uh, what?

> Furthermore, the order in ItemTier is odd. The SET tier does not really fit in with the rest, but it is usually listed (as in the Blacksmith selling message) between RARE and LEGENDARY. I have checked the usage of priority in ItemTier, and I think it's perfectly fine to reorder them to match the Blacksmith order.

Again, sure

2021-01-03 22:56 UTC, magicus commented
And then finally you can replace the message part with:

```
        StringBuilder sb = new StringBuilder();
        for (ItemTier tier : ItemTier.values()) {
            sb.append('/');
            sb.append(tier.color);
            sb.append(itemCounts.getOrDefault(tier, 0));
            sb.append(TextFormatting.LIGHT_PURPLE);
        }
        sb.setCharAt(0, '(');
        sb.append(") item(s) for ");
```

2021-01-03 22:58 UTC, magicus commented
At this point, you have transferred all the "knowledge" about rarity levels in Wynntils to a single point, the ItemTier class. If Wynncraft ever introduces a new EPIC item tier (or a MUNDANE below RARE, for that matter), we would only have to update it in a single place, give it it's correct color, and the Blacksmith message code would still continue to work!

2021-01-03 23:01 UTC, TrapinchO commented
> And then finally you can replace the message part with:
> 
> ```
>         StringBuilder sb = new StringBuilder();
>         for (ItemTier tier : ItemTier.values()) {
>             sb.append('/');
>             sb.append(tier.color);
>             sb.append(itemCounts.getOrDefault(tier, 0));
>             sb.append(TextFormatting.LIGHT_PURPLE);
>         }
>         sb.setCharAt(0, '(');
>         sb.append(") item(s) for ");
> ```

This part is missing
```total + " ("```



> And then finally you can replace the message part with:
> 
> ```
>         StringBuilder sb = new StringBuilder();
>         for (ItemTier tier : ItemTier.values()) {
>             sb.append('/');
>             sb.append(tier.color);
>             sb.append(itemCounts.getOrDefault(tier, 0));
>             sb.append(TextFormatting.LIGHT_PURPLE);
>         }
>         sb.setCharAt(0, '(');
>         sb.append(") item(s) for ");
> ```

I will try it if I won't tomorrow forget

2021-01-04 00:20 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +    CRAFTED   (7, TextFormatting.DARK_AQUA, (lvl) -> lvl);
Please try and follow the indentation of the rest of the table for the lambda expression.

2021-01-04 00:22 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +    SET       (1, TextFormatting.GREEN,        (lvl) -> (int)Math.ceil(12d + lvl * 1.6)),
This means you should reorder the priority from SET, UNIQUE and RARE.

2021-01-04 00:24 UTC, magicus commented
Yes, don't forget about the total. :-) The code snippets I'm sending you here are sketches, there might be syntax errors and omissions (like the total) and other adaptations you need to do.

2021-01-04 11:39 UTC, TrapinchO commented
Is this enough or do you want me to try:

```
for (ItemTier tier : ItemTier.values()) {
    if (tier.getColorCode().equals(s.charAt(0))) {
        itemCounts.put(ItemTier.NORMAL, itemCounts.getOrDefault(ItemTier.NORMAL, 0) + 1)
    }
}
```

Also how to get a sum of values within EnumMap?

2021-01-04 13:53 UTC, TrapinchO commented
Ok, I think I am done with this PR if you have nothing else

2021-01-05 00:55 UTC, magicus commented
Yes, please also unify the adding of the values.

2021-01-05 00:56 UTC, magicus commented
As for the EnumMap, perhaps you can do something along the lines of `Stream.of(itemCounts.values().sum()`?

2021-01-05 11:15 UTC, HeyZeer0 requested changes
LGTM once changes done.

2021-01-05 11:15 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.matches("e\\d+")) {
else not necessary you're continuing above

2021-01-05 11:15 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                        message.append(") item(s) for ");
space above this

2021-01-05 11:15 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                        GameUpdateOverlay.queueMessage(message.toString()); // send the redirect messsage
space above this

2021-01-05 11:15 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.startsWith("f")) { itemCounts.put(ItemTier.NORMAL, itemCounts.getOrDefault(ItemTier.NORMAL, 0) + 1); } // normal
Don't make all the code in a single line, remove the else and place a continue. Same for all below ones

2021-01-05 11:15 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
>          return rolledAmount == 0 ? basePrice : basePrice * (int)Math.pow(5, rolledAmount);
nice catch on this class but I just noticed this thing is also wrong, mind changing it as well?
it should be just:
`return basePrice * (int)Math.pow(55, rolledAmount);`

because:
0 rolls -> basePrice * 5^0 = basePrice * 1 = basePrice
1 roll -> basePrice * 5^1 = basePrice * 5

basically, we are doing an unnecessary check.

2021-01-05 11:33 UTC, magicus requested changes

2021-01-05 11:33 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +import static net.minecraft.util.text.TextFormatting.*;
We don't normally do static imports. Now that the color codes are used in just a few places, I think it is better to be explicit about what class they come from, and remove the static import.

2021-01-05 11:33 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                        //int total = IntStream.of(itemCount).sum(); // sum of the items
Remove the commented out code.

2021-01-05 11:33 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            message.insert(0, LIGHT_PURPLE + "Sold " + total + " ");
Instead of using insert(), which is an expensive operation, create a new string builder and append the common part. E.g. rename the current SB message to "messageCounts" or so, and then create a new SB `message`, and start with `message.append(messageCounts)`

2021-01-05 11:33 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.startsWith("f")) { itemCounts.put(ItemTier.NORMAL, itemCounts.getOrDefault(ItemTier.NORMAL, 0) + 1); } // normal
Or, better, as I suggested, do this in a general way instead of testing each rarity by itself.

2021-01-05 11:33 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            message.append(GREEN + s.replace("e", "") + (char) 0xB2 + LIGHT_PURPLE + ".");
Instead of the hardcoded 0xB2, use `EmeraldSymbols.EMERALDS`

2021-01-05 11:33 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            message.append(GREEN + s.replace("e", "") + (char) 0xB2 + LIGHT_PURPLE + ".");
Also, I think we should skip the trailing dot at the end of this (and the scrapped) message.

I don't fully understand what the replace "e" -> "" is doing, but I see this is in the original code as well. If you understand this (perhaps by looking at the original `s` string), please add a comment.

2021-01-05 11:34 UTC, magicus commented
Almost done! Just a few fixes left, hang on and you'll be good to go! :)

2021-01-05 11:35 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +import static net.minecraft.util.text.TextFormatting.*;
Discuss this with @HeyZeer0, he told me to do it

2021-01-05 11:36 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                        //int total = IntStream.of(itemCount).sum(); // sum of the items
Sorry, forgot

2021-01-05 11:38 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            message.append(GREEN + s.replace("e", "") + (char) 0xB2 + LIGHT_PURPLE + ".");
Because instead of the "e" you use the emerald sign

2021-01-05 11:54 UTC, TrapinchO commented
> Almost done! Just a few fixes left, hang on and you'll be good to go! :)

10 change requests - few fixes... :)

2021-01-05 11:59 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.matches("e\\d+")) {
done in the next committ

2021-01-05 12:00 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.startsWith("f")) { itemCounts.put(ItemTier.NORMAL, itemCounts.getOrDefault(ItemTier.NORMAL, 0) + 1); } // normal
> Don't make all the code in a single line, remove the else and place a continue. Same for all below ones

Sure

2021-01-05 12:04 UTC, TrapinchO commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
>          return rolledAmount == 0 ? basePrice : basePrice * (int)Math.pow(5, rolledAmount);
done for the next commit

2021-01-05 12:06 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            message.append(GREEN + s.replace("e", "") + (char) 0xB2 + LIGHT_PURPLE + ".");
done for the next commit

2021-01-05 12:28 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +import static net.minecraft.util.text.TextFormatting.*;
> Now that the color codes are used in just a few places, I think it is better to be explicit about what class they come from, and remove the static import.

The green rectangles are places where colors are used (With `TextFormatting.` before the color). They are used in many palces
![mc_colors](https://user-images.githubusercontent.com/67415128/103646277-b1498080-4f59-11eb-9179-3ed238519537.png)

2021-01-05 12:34 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                            message.insert(0, LIGHT_PURPLE + "Sold " + total + " ");
done for the next commit

2021-01-05 12:46 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                        message.append(") item(s) for ");
done now?

2021-01-05 12:46 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                        GameUpdateOverlay.queueMessage(message.toString()); // send the redirect messsage
done now?

2021-01-05 12:57 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +import static net.minecraft.util.text.TextFormatting.*;
Oh, great, I get to fight @HeyZeer0. ;-) I think consistency is important. If you do this static import, maybe you can come back in a separate PR and remove the TextFormatting prefix for the other places..?

(But personally I think it's mostly helpful to keep the prefix; it helps you understand that it is a text formatting code and not an RGB color triple. But I will not take that fight with Zeer0 here in this PR. :-))

2021-01-05 13:23 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +import static net.minecraft.util.text.TextFormatting.*;
> I think consistency is important. If you do this static import, maybe you can come back in a separate PR and remove the TextFormatting prefix for the other places..?

That was my intention.

> (But personally I think it's mostly helpful to keep the prefix; it helps you understand that it is a text formatting code and not an RGB color triple. But I will not take that fight with Zeer0 here in this PR. :-))
For me personally those are just colors, meaning it is not reakky necessary. In other cases I would propably recommend the prefix too

2021-01-05 13:24 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    else if (s.startsWith("a")) { countTest[3]++; } // set
Since we are using another way to do it I am resolving this one

2021-01-05 14:10 UTC, magicus requested changes

2021-01-05 14:10 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    }
Just needs to compact this to the loop I provided. :)

2021-01-05 15:32 UTC, TrapinchO commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    }
done

2021-01-05 16:40 UTC, magicus commented
Now it really looks great!

All I want is a final confirmation that you have tested this code -- sell a bunch of items of different rarities to a blacksmith and verify that the message looks correct. When you confirm that this works, I'll integrate the PR.

2021-01-05 16:55 UTC, TrapinchO commented
> Now it really looks great!
> 
> All I want is a final confirmation that you have tested this code -- sell a bunch of items of different rarities to a blacksmith and verify that the message looks correct. When you confirm that this works, I'll integrate the PR.

You need to fight HeyZeer0 first :)

Yes, the code works. I only tested it with normal-rare rarities (because I don't have rarer items to sell and TM is down), but it works

2021-01-05 18:33 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +import static net.minecraft.util.text.TextFormatting.*;
Oh, we do use static imports in a lot of places! they drastically reduce the spam on your facing while calling a bunch of color enums.
We use it on GlStateManager as well, to not keep having to call a hell lot of functions that keep
repeating GlStateManager.

Totally fine 👍🏻

2021-01-05 18:34 UTC, HeyZeer0 requested changes
LGTM once changed from 55 to 5!

2021-01-05 18:34 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +        return basePrice * (int)Math.pow(55, rolledAmount);
just 5, not 55!

2021-01-05 18:47 UTC, TrapinchO commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +        return basePrice * (int)Math.pow(55, rolledAmount);
you were the one who told me to use 55 (you sent the code) btw.

I will correct it soon

Btw what is the formula for crafted?

2021-01-05 18:54 UTC, TrapinchO commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +        return basePrice * (int)Math.pow(55, rolledAmount);
corrected

2021-01-05 19:09 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +        return basePrice * (int)Math.pow(55, rolledAmount);
who knows

2021-01-05 19:10 UTC, HeyZeer0 approved these changes

2021-01-05 19:12 UTC, TrapinchO commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +        return basePrice * (int)Math.pow(55, rolledAmount);
You do.
You are Wynncraft dev after all....

(Yes, I know you propably can't use it for Wynntils)

2021-01-05 19:21 UTC, magicus commented
I will not fight Zeer0. :) I accept his desire to do static imports.

2021-01-05 19:21 UTC, magicus approved these changes

2021-01-05 19:22 UTC, merged