Collect all rarity/item tier info in ItemTier class
Wynntils/Wynntils-Legacy pull request #291
Opened 2021-01-06 01:10 UTC by magicus

2021-01-07 13:35 UTC, HeyZeer0 requested changes
LGTM when changes were done

2021-01-07 13:35 UTC, HeyZeer0 commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +    public int getItemCost(int level) {
Cost for what exactly?

2021-01-07 13:35 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        } else if (lore.contains(ItemTier.NORMAL.asFormattedName()) && UtilitiesConfig.Items.INSTANCE.normalHighlight) {
Can you clean this method? 
These elses are completely unnecessary, makes it so hard to read 😔

2021-01-08 01:14 UTC, P0keDev requested changes

2021-01-08 01:14 UTC, P0keDev commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                CustomColor color = pf.getTier().getHighlightColor();
Use user-defined highlight color instead of default

2021-01-09 00:23 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/item/enums/ItemTier.java
> +    public int getItemCost(int level) {
For identification. That's in the Identifier dialog where the price for a certain artifact is previewed. I renamed the method.

2021-01-09 00:24 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        } else if (lore.contains(ItemTier.NORMAL.asFormattedName()) && UtilitiesConfig.Items.INSTANCE.normalHighlight) {
I removed the elses and tried to simplify the function somewhat.

2021-01-09 00:26 UTC, magicus commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/ItemPage.java
> +                CustomColor color = pf.getTier().getHighlightColor();
Done. It's still a lot of odds and ends with the custom highlighting and item guide. For instance, we do not check if crafted items should be highlighted -- we just do it. And we do no not check at all if highlighting should be enabled in the Item Guide -- we just do it. (Frankly, I'm not sure if it's even needed to have an option to turn it off...)

I did not want to fix that in this PR. But it could certainly warrant some more passes over that code...

2021-01-10 05:28 UTC, P0keDev approved these changes

2021-01-11 07:36 UTC, merged