Remove unused import
Wynntils/Wynntils-Legacy pull request #293
Opened 2021-01-12 13:47 UTC by TrapinchO

Removed unused imports from these files:

> core/events/custom/GameEvent.java
> 
> core/events/custom/WynnSocialEvent.java
> 
> 
> modules/core/instances/packet/PacketIncomingFilter.java
> modules/core/overlays/ui/ModConflictScreen.java
> 
> modules/map/rendering/PointRenderer.java
> 
> modules/utilities/instances/InfoFormatter.java
> modules/utilities/managers/NametagManager.java
> 
> modules/utilities/overlays/inventories/SkillPointOverlay.java
> 
> modules/visual/overlays/ui/CharacterSelectorUI.java
> 
> 
> webapi/profiles/guild/GuildProfile.java
> webapi/profiles/FileUpdater.java
> webapi/profiles/LeaderboardProfile.java
> webapi/profiles/ServerProfile.java
> webapi/profiles/UpdateProfile.java

Also added "A Marker Interface" to the "Listener" interface

2021-01-12 17:04 UTC, magicus approved these changes
Looks good. Github says there is a merge conflict; resolve it and I'll push the PR.

2021-01-12 17:07 UTC, TrapinchO commented
> Looks good. Github says there is a merge conflict; resolve it and I'll push the PR.

The problem is I have no idea why. Maybe I am just idiot, but I really have no idea.

2021-01-12 17:07 UTC, TrapinchO commented
I could make redo it of course

2021-01-12 18:47 UTC, TrapinchO commented
Stackoverflow is the saviour of all programmers. Like always

2021-01-12 18:53 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/framework/interfaces/Listener.java
> + * Marker interface
Wrong position, this is inside the copyright notice

2021-01-12 18:53 UTC, HeyZeer0 requested changes
LGTM after the change is done

2021-01-13 11:53 UTC, magicus approved these changes

2021-01-13 11:53 UTC, merged