Code quality improvements
Wynntils/Wynntils-Legacy pull request #294
Opened 2021-01-15 14:48 UTC by HighCrit

Fixed among other things potential memory leaks and concurrency issues

2021-01-15 16:53 UTC, HeyZeer0 requested changes
LGTM once changes done.

Nice work 👍🏻

2021-01-15 16:53 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/framework/FrameworkManager.java
> +    private FrameworkManager() {}
no reason to have a constructor for a class that's not instantiable.

2021-01-15 16:53 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/CoreManager.java
> +    private CoreManager() {}
no reason to have a constructor for a class that's not instantiable.

2021-01-15 16:53 UTC, HeyZeer0 commented on src/main/java/com/wynntils/Reference.java
> +        private ServerIPS() {}
no reason to have a constructor for a class that's not instantiable.

2021-01-15 18:25 UTC, magicus approved these changes

2021-01-15 18:25 UTC, magicus commented on src/main/java/com/wynntils/core/CoreManager.java
> +    private CoreManager() {}
Actually, you always have a default constructor unless you specify another explicitly.

This change is implementing the recommended pattern for non-instantiable classes like singletons.

2021-01-15 18:49 UTC, HighCrit commented on src/main/java/com/wynntils/core/CoreManager.java
> +    private CoreManager() {}
what he said

2021-01-16 02:31 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/CoreManager.java
> +    private CoreManager() {}
still, it doesn't matter and just pollutes your view with a completely useless constructor.

2021-01-16 15:48 UTC, HeyZeer0 approved these changes

2021-01-16 16:05 UTC, merged