Horse Improvements
Wynntils/Wynntils-Legacy pull request #302
Opened 2021-02-13 05:27 UTC by iwei20

Instead of returning an error when the horse is too far, now the horse is despawned and respawned.
Also moved the no horse check to the beginning of the function.
Because you can now successfully mount the horse even if it is far away, the HORSE_TOO_FAR in MountHorseStatus was removed, as well as its error message.

I am completely unaware if this actually affects anything with the network events and whatnot.

2021-02-14 14:07 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +        if(playersHorse != null) {
space between if and (

2021-02-14 14:08 UTC, HeyZeer0 requested changes
Great work, LGTM once the syntax requested changes are done!

2021-02-14 14:08 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +        if(playersHorse != null) {
Space between if and (

2021-02-14 14:08 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +        if(playersHorse == null || far) {
space between if and (

2021-02-14 14:08 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +            if(far) {
space between if and (

2021-02-16 03:56 UTC, merged

2021-02-16 04:19 UTC, LukasmanMHdude commented
POG

2021-02-16 14:24 UTC, McPlayHD commented
I get "Your horse was unable to be found" almost every time.