Fix allowRetry
Wynntils/Wynntils-Legacy pull request #306
Opened 2021-02-18 21:01 UTC by iwei20

Thanks to @McPlayHD for mentioning the problem.  allowRetry was at the beginning, so when the horse spawned and the client event triggered for a second time it returned NO HORSE.  I moved that back into the null/far if statement.

Further testing revealed that there might need to be some modification to client events to actually get it to respawn, or maybe something else.  Current behavior is only despawning the horse on pressing the button which is in my opinion better than spitting out an error message, but I would prefer to get it to my original intention.

2021-02-19 23:19 UTC, iwei20 commented
Finally got behavior to intended state by adding 25-tick delay between despawn and respawn, thanks to @P0keDev for telling me Delay exists

2021-02-20 01:18 UTC, iwei20 commented
Thanks to @HighCrit for the suggestion on multi attempt spawning

2021-03-10 17:48 UTC, HeyZeer0 requested changes
LGTM once addressed, nice work on this, and sorry for the delay!

2021-03-10 17:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    MountHorseManager.ingamePrevention = true;
Move this to the mountHorse method on MountHorseManager

2021-03-10 17:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                    MountHorseManager.ingamePrevention = true;
Move this to the mountHorse method on MountHorseManager

2021-03-10 17:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +            } else {
else is not required since you're returning above

2021-03-10 17:48 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/MountHorseManager.java
> +            } else {
replace the else with a return:
```
if (findHorseInRadius(mc) != null) {
    ClientEvents.isAwaitingHorseMount = true;
    return;
}

// below
```

2021-03-13 07:39 UTC, merged