Server selector displays server number properly
Wynntils/Wynntils-Legacy pull request #307
Opened 2021-02-22 19:46 UTC by DonkeyBlaster69

Replaces the # of items display with actual server numbers, for servers above 64. Uses same method as the display item level feature, except it doesn't check if you're holding down a key. Tested on server 70, and also seems to not affect anything else in-game.

2021-02-23 08:33 UTC, P0keDev requested changes
Feel free to tag me on discord if you need any clarifications

2021-02-23 08:33 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ServerNumberOverlay.java
> +        if (!UtilitiesConfig.Items.INSTANCE.itemLevelOverlayOutsideGui && Minecraft.getMinecraft().currentScreen == null) return;
The config check is unnecessary, since this code is only applicable when a GUI is open (there will never be server items in the hotbar, which is what the config option is for)

2021-02-23 08:33 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ServerNumberOverlay.java
> +        assert serverName != null;
There should not be asserts in any production code, replace with an if statement that returns when null

2021-02-23 08:33 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ServerNumberOverlay.java
> +        }
You can assure more accurate matching and handle the issue of number parsing errors with a regex pattern for server names, something like `World (\d+)(?: \(Recommended!\))?` (I can't recall if that's the exact format for a recommended world, so don't use that without checking). That way, you can verify the item name and grab the server number at the same time, without the ugly try/catch, and it won't try to parse random items whose names start with 'World'.

2021-02-24 02:50 UTC, P0keDev approved these changes

2021-02-27 01:43 UTC, HeyZeer0 approved these changes

2021-02-27 01:43 UTC, merged