Created a loot run list page
Wynntils/Wynntils-Legacy pull request #316
Opened 2021-04-11 02:19 UTC by Incompleteusern

Made a page of the questbook listing the lootruns in similar fashion to the page listing the quest books. Fair bit of code is borrowed and modified from QuestsPage and ItemPage.
![image](https://user-images.githubusercontent.com/58920010/114290073-b8d56580-9a31-11eb-8a04-41ca0691b19d.png)

2021-04-11 14:06 UTC, Incompleteusern commented
TODO: Add a way to delete lootruns from the page, and add a keybind to open it

2021-04-11 19:07 UTC, Incompleteusern commented
Fixed a bug

2021-04-11 21:50 UTC, HighCrit commented
You dont have to close the PR when you fix a bug

2021-04-12 04:54 UTC, wegiboarduwu commented
Hi, it's a nice feature, however there seems to be a few typos on the Lootrun page near the Lootrun's directory. But it's very nice to finally have a cleaner and more manageable way to start lootruns. :)

2021-04-13 04:18 UTC, quick007 commented
> Fixed a bug

next time, feel free to mark it as a draft

2021-04-13 04:21 UTC, quick007 commented
@Incompleteusern few suggestions-

- middle-click to open in file manager
- make the left-click to load bold and the other non bolded. also add a conformation screen if you haven't already

2021-04-14 17:58 UTC, Incompleteusern commented
Updated image
![image](https://user-images.githubusercontent.com/58920010/114757142-58d00f00-9d10-11eb-8a8f-0ecc8ab4116f.png)

2021-04-16 02:19 UTC, Incompleteusern commented
This should be my final commit, unless there is something wrong that can be fixed/a better way to implement. Also I downloaded Github Desktop so all my commits should be grouped together in the future

2021-04-17 14:02 UTC, HeyZeer0 requested changes
Very well done! This feature looks amazing!
This is initially a code review, so I'll review this again once the changes are made based on the functionality.

A good tip is always trying to reducing the amount of elses in the code by, for example, splitting whatever is inside of ``drawScreen`` into their own methods that you can easily add a ``return``

For example, this could be turned into:
```java
            // put next and back button
            if (currentPage == pages) {
                render.drawRect(Textures.UIs.quest_book, x + 128, y + 88, 223, 222, 18, 10);
            } else {
                if (posX >= -145 && posX <= -127 && posY >= -97 && posY <= -88) {
                    render.drawRect(Textures.UIs.quest_book, x + 128, y + 88, 223, 222, 18, 10);
                } else {
                    render.drawRect(Textures.UIs.quest_book, x + 128, y + 88, 205, 222, 18, 10);
                }
            }
```
```java
public void drawNextPageButton(int x, int y) {
	if (currentPage == pages) {
		render.drawRect(Textures.UIs.quest_book, x + 128, y + 88, 223, 222, 18, 10);
		return;
	}
	
	// Hovering
	if (posX >= -145 && posX <= -127 && posY >= -97 && posY <= -88) {
		render.drawRect(Textures.UIs.quest_book, x + 128, y + 88, 223, 222, 18, 10);
		return;
	}
	
	render.drawRect(Textures.UIs.quest_book, x + 128, y + 88, 205, 222, 18, 10);
}

Again, Awesome work, and thanks for contributing to Wynntils!

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                render.drawString("Lootrun Loaded:", x/1.2f - 154/1.2f, y/1.2f - 30/1.2f, CommonColors.BLACK, SmartFontRenderer.TextAlignment.LEFT_RIGHT, SmartFontRenderer.TextShadow.NONE);
Let's remove this line so we open more space for the map preview and move some stuff up

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +
Remove extra space

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +
Remove this extra space

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                        GlStateManager.enableAlpha();
Let's static import GlStateManager so we don't keep repeating it over and over

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +
Remove extra space

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +            else {
we use
```java
} else {
```
instead of
```java
}
else {
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                render.drawString("Here you can see all lootruns", x - 154, y - 30, CommonColors.BLACK, SmartFontRenderer.TextAlignment.LEFT_RIGHT, SmartFontRenderer.TextShadow.NONE);
Let's make this text a String[] and calculate the Y offset automatically using a for

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +
Remove extra space

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +            else {
we use
```java
} else {
```
instead of
```java
}
else {
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +        if (selectedName != null) {
let's invert this if so we avoid extra tabbing.
```java
if (selectedName == null) return;
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +
Remove extra space

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +        return str;
Space above return

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +        else if (posX >= -30 && posX <= -13 && posY >= -97 && posY <= -88) { // page backwards button
else is redundant here, let's go with just an if.
```java
if (posX >= -30 && posX <= -13 && posY >= -97 && posY <= -88) { // page backwards button
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +        else if (posX >= 74 && posX <= 90 && posY >= 37 & posY <= 46) { // quest book back button
else is redundant here, let's go with just an if.
```java
if (posX >= 74 && posX <= 90 && posY >= 37 & posY <= 46) { // quest book back button
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                        Minecraft.getMinecraft().getSoundHandler().playSound(PositionedSoundRecord.getMasterRecord(SoundEvents.BLOCK_ANVIL_PLACE, 1f));
space above this line

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                else {
we use
```java
} else {
```
instead of
```java
}
else {
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                    return;
space above this line

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +        int mapWidth = 145;
space above this line

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +            else if (mouseButton == 2) { //middle click means open up folder
we use
```java
} else if {
```
instead of
```java
}
else if {
```

2021-04-17 14:02 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                            animationTick = 133;
space above this line

2021-04-18 03:51 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                render.drawString("Here you can see all lootruns", x - 154, y - 30, CommonColors.BLACK, SmartFontRenderer.TextAlignment.LEFT_RIGHT, SmartFontRenderer.TextShadow.NONE);
Did this for the other pages too

2021-04-19 21:43 UTC, HeyZeer0 requested changes

2021-04-19 21:43 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/QuestPageUtils.java
> +public class QuestPageUtils {
This class needs to be moved to the questbook module and be placed inside the `QuestBookPage` class, since it's only useful in there

2021-04-19 21:43 UTC, HeyZeer0 commented on src/main/java/com/wynntils/core/utils/QuestPageUtils.java
> +
Remove useless space

2021-04-19 21:43 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/QuestsPage.java
> +            List<String> textLines = Arrays.asList("Here you can see all quests", "available for you. You can", "also search for a specific", "quest just by typing its name.", "You can go to the next
You can make this a static and final array since it's not changing

2021-04-19 21:43 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/questbook/overlays/ui/LootRunPage.java
> +                List<String> textLines = Arrays.asList("Here you can see all lootruns", "you have downloaded. You can", "also search for a specific", "quest just by typing its name.", "You can go to
You can make this a static and final array since it's not changing

2021-04-20 04:44 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/questbook/instances/QuestBookPage.java
> +    protected void drawMenuButton(int x, int y, int posX, int posY) {
I've decided to modify have this method modify hoveredText

2021-04-21 14:39 UTC, HeyZeer0 approved these changes

2021-04-21 14:39 UTC, merged