Item favoriting
Wynntils/Wynntils-Legacy pull request #345
Opened 2021-08-28 04:09 UTC by P0keDev

Adds a system for 'favoriting' items so that they can more easily be noticed in loot chests. Users can favorite and unfavorite items through the item guide by shift left clicking, which is noted in each item's tooltip similar to the Wynndata feature. Any boxes that might contain a favorited item have a star icon to signify the fact, and the name of the item(s) in question will be underlined in the possibilities line of the tooltip, if item possibilities are enabled. Wynntils will also prevent the closing of chests with such boxes, in the same way it does with mythic boxes (this feature can be toggled off). Currently, only regular gear items are supported (basically, anything that shows up in the item guide) - I do want to expand the feature to ingredients eventually.

This PR also fixes a crash that occurs when extremely large numbers are entered as prices in the trade market, and disables clicking the ingredient pouch while in a chest, since it does nothing but force close the chest.

https://cdn.discordapp.com/attachments/879902018016251978/880701121881075752/unknown.png
https://cdn.discordapp.com/attachments/879902018016251978/881016942553612339/unknown.png
https://cdn.discordapp.com/attachments/879902018016251978/881023423592144906/unknown.png

2021-08-28 06:25 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            if (!itemName.contains("Unidentified")) {
I don't think this should be inverted

2021-08-28 14:42 UTC, HeyZeer0 requested changes
LGTM once changes were made. Really nice work on this! Definitely a cool feature and thanks for the bug fixes 😄

2021-08-28 14:42 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            ScreenRenderer r = new ScreenRenderer();
This will cause some heavy GC, don't we have a static instance of this stored somewhere? If not just create one on this class and it should be fine.

2021-08-28 14:42 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            ScreenRenderer.scale(scaleFactor);
Declaring the variable here seems unnecessary? Probably could be
```suggestion
            ScreenRenderer.scale(0.5f);
```

2021-08-28 14:42 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            r.drawRect(Textures.Map.map_icons, (int)((gui.getGuiLeft() + s.xPos + 10) / scaleFactor), (int)((gui.getGuiTop() + s.yPos - 5) / scaleFactor), 208, 36, 18, 18);
Instead of translating into 0, 0 with beginGl, translate to `gui.getGuiLeft()` and `gui.getGuiTop()` including the offset to the center of the slot, that will make you not need to divide by the scale factor reducing overhead and improving alias.

2021-08-28 14:42 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +                nbt.setBoolean("wynntilsFavorite", false);
Any reason why you are setting it to false instead of checking if it contains? This will probably add a bunch of unnecessary data but might have a reason

2021-08-28 14:42 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        }
Does this block clicks on the pouch with the pouch open? If so might wanna check if that doesn't cause any weird behavior

2021-08-28 20:22 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +                nbt.setBoolean("wynntilsFavorite", false);
I did it so that any item only needs to be checked once, and then can be ignored on every tick afterwards - I figured that would be more efficient

2021-08-28 21:40 UTC, P0keDev commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        }
Clicking the pouch while in the pouch menu force closes it in the same way as any other chest gui, so disabling it shouldn't be an issue

2021-08-29 20:41 UTC, HeyZeer0 approved these changes

2021-08-30 02:14 UTC, merged