Translate Quests Dialogue lines
Wynntils/Wynntils-Legacy pull request #347
Opened 2021-08-30 16:53 UTC by theobeaudenon

Translate Quests Dialogue lines

French Demo
![demo](https://i.imgur.com/t0VKDMV.png)

2021-08-30 16:55 UTC, theobeaudenon commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +                    ChatOverlay.getChat().printChatMessage(new TextComponentString(TranslationManager.TRANSLATED_PREFIX + prefix + org.apache.commons.lang3.StringUtils.stripAccents(translatedMsg) + s
Accents not well formatted so I removed them

2021-08-31 00:43 UTC, Incompleteusern commented
It might be better to check if the player is in dialogue before applying the matcher, which seems a little wonky. Other than that, great job for fixing an unfixed bug!

I think the regex could be changed from

`            "(.*:)(.+(?:(?:SHIFT)|(?:SNEAK))+.+)(.+.+)", Pattern.DOTALL);  // Quest Dialogue`

to

`            "(.+:)(.+(?:SHIFT)|(?:SNEAK).+)(.+)", Pattern.DOTALL);  // Quest Dialogue`,

This is not tested though

2021-09-02 11:04 UTC, theobeaudenon commented
> It might be better to check if the player is in dialogue before applying the matcher, which seems a little wonky. Other than that, great job for fixing an unfixed bug!
> 
> I think the regex could be changed from
> 
> ` "(.*:)(.+(?:(?:SHIFT)|(?:SNEAK))+.+)(.+.+)", Pattern.DOTALL); // Quest Dialogue`
> 
> to
> 
> ` "(.+:)(.+(?:SHIFT)|(?:SNEAK).+)(.+)", Pattern.DOTALL); // Quest Dialogue`,
> 
> This is not tested though

Your regex doesn't fully match the dialogue

2021-09-02 18:02 UTC, magicus requested changes

2021-09-02 18:02 UTC, magicus commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +                        if (ChatConfig.INSTANCE.addTimestampsToChat)
Please add braces when you spit single-line if statements. It's a huge source of bugs and misunderstandings. (Applies to all locations where you have done this)

2021-09-02 18:02 UTC, magicus commented on src/main/java/com/wynntils/modules/core/config/CoreDBConfig.java
> +            "§7Disable: §rThe mod will not update when a new version is released. ", upload = false)
This does not seem relevant to the current PR? Merge error?

2021-09-02 18:02 UTC, magicus commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +                    ChatOverlay.getChat().printChatMessage(new TextComponentString(translatedMsg == null ?  TranslationManager.UNTRANSLATED_PREFIX +  formatted : TranslationManager.TRANSLATED_PREFIX
Are you sure you should call StringUtils.stripAccents when printing the translations? I think that is wrong. I suspect that means that the Swedish characters "åäö" will be replaced with "aao", which is definitely wrong, and will render the translation incorrect and difficult to understand.

This is different from stripping accents from the Wynncraft original texts before sending them to translation, which is OK if the translation service has problem handling those.

2021-09-04 00:52 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/config/CoreDBConfig.java
> +            "§7Disable: §rThe mod will not update when a new version is released. ", upload = false)
See https://github.com/Wynntils/Wynntils/pull/315

2021-09-29 10:52 UTC, magicus commented
@theobeaudenon Did you give up on this? I think the premise is sound, it just needs some tweaking. Do you want help with getting it polished and integrated?

2021-09-29 12:03 UTC, theobeaudenon commented
Hey, with the new update, the regex doesn't work anymore. I'm working on it and I will make a new PR.

2021-09-29 12:05 UTC, theobeaudenon commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +                    ChatOverlay.getChat().printChatMessage(new TextComponentString(translatedMsg == null ?  TranslationManager.UNTRANSLATED_PREFIX +  formatted : TranslationManager.TRANSLATED_PREFIX
I will add an option to activate the stripAccents.

2021-09-29 12:05 UTC, theobeaudenon commented on src/main/java/com/wynntils/modules/core/config/CoreDBConfig.java
> +            "§7Disable: §rThe mod will not update when a new version is released. ", upload = false)
I will remove this

2021-09-29 12:06 UTC, theobeaudenon commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +                        if (ChatConfig.INSTANCE.addTimestampsToChat)
not my code xD 
maybe IDE do this

2021-09-30 18:23 UTC, theobeaudenon commented
strip Accents option 
![javaw_2021-09-30_20-22-44](https://user-images.githubusercontent.com/3408633/135510123-3a459335-0194-4de3-9ebd-b460766d7d30.png)


With Accent removal option :
![javaw_2021-09-29_20-44-20](https://user-images.githubusercontent.com/3408633/135509300-4bb2631b-5faf-45c8-9a76-f64b9398e99a.png)

Without Accent removal option :
![javaw_2021-09-29_20-43-52](https://user-images.githubusercontent.com/3408633/135509306-e41c4a78-7111-441e-9737-5a412e1e1d5f.png)

now Working Without npc name   
![javaw_2021-09-30_20-20-02](https://user-images.githubusercontent.com/3408633/135509833-4f9e4ac2-382e-40f9-bde9-88b5a86f94ac.png)

2021-10-01 08:10 UTC, magicus requested changes
Just fix the whitespaces as suggested, and this looks fine to me! Thank you for fixing this.

2021-10-01 08:10 UTC, magicus commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +            if(TranslationConfig.INSTANCE.removeAccents){
```suggestion
            if (TranslationConfig.INSTANCE.removeAccents) {
```

2021-10-01 08:10 UTC, magicus commented on src/main/java/com/wynntils/modules/chat/managers/ChatManager.java
> +                        if (ChatConfig.INSTANCE.addTimestampsToChat){
```suggestion
                        if (ChatConfig.INSTANCE.addTimestampsToChat) {
```

2021-10-01 08:56 UTC, magicus approved these changes
Looks good now!

2021-10-17 03:37 UTC, merged