Emerald pouch hotkey option
Wynntils/Wynntils-Legacy pull request #351
Opened 2021-10-05 08:58 UTC by DonkeyBlaster69

Code is similar to ingredient pouch when the emerald pouch is in the main inventory
Code is similar to horse spawning when the emerald pouch is in the hotbar
Function is unbound by default.

Not sure why I can't send a r-click packet when it's in the hotbar. If anyone happens to know, please ping on Discord/reply.

2021-10-05 22:30 UTC, Incompleteusern commented
Try checking the questbook analysis code for right clicking in the hotbar

2021-10-06 18:47 UTC, HeyZeer0 commented
Probably the reason you can't click on the Hotbar is because you are using the incorrect slot id, the packet requires the raw slot and the Hotbar is not 0-8 on raw slots

Check this out:
![Inventory Slots](https://user-images.githubusercontent.com/21368488/136264455-20278982-7561-4d81-9af1-2e1ed07d9ddb.png)

2021-10-07 07:42 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +                           case 0:
...! 😮 

So, you are "unrolling" the calculation `slotNumber + 36`? :-D

2021-10-07 17:31 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +                   GameUpdateOverlay.queueMessage(TextFormatting.DARK_RED + "You have more than one emerald pouch in your inventory.");
Just thinking out loud here. Maybe it would be better to open one of the pouches, if we have many? Like the first, or the last, or the one with most/least emeralds/free space in them?

Otoh, I have not really played with the new emerald pouches, so I can't say I really understand the need for this hotkey anyway. :-)

2021-10-07 17:32 UTC, magicus approved these changes
The code looks good now imho.

2021-10-07 18:20 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +                   GameUpdateOverlay.queueMessage(TextFormatting.DARK_RED + "You have more than one emerald pouch in your inventory.");
I was originally considering something like that as well, but I thought it'd be confusing at times and imo it's better to avoid it when dealing with currency and that sort of stuff

If anyone disagrees and wants it in though, I can work something out

2021-10-10 20:17 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/managers/KeyManager.java
> +                   GameUpdateOverlay.queueMessage(TextFormatting.DARK_RED + "You have more than one emerald pouch in your inventory.");
This is good for me. Leave it as it is.

2021-10-23 23:25 UTC, P0keDev requested changes
The pouch code (for both pouches) should be moved to a different file like for all the other hotkeys, to avoid cluttering this file

2021-10-25 07:50 UTC, magicus approved these changes

2021-10-28 00:34 UTC, P0keDev approved these changes

2021-10-28 00:34 UTC, merged