Add Emerald Pouch Usage Arc
Wynntils/Wynntils-Legacy pull request #352
Opened 2021-10-06 00:55 UTC by DonkeyBlaster69

Usage arc similar to the crafted item durability arc
- Starts at green when empty
- Progresses to red when getting full
- Setting to toggle on/off

2021-10-06 09:37 UTC, magicus approved these changes

2021-10-06 09:38 UTC, magicus commented
Cool idea. I wonder if we could/should show the ingredient pouch "fullness" with the same kind of functionality? (Not saying you should do that in this PR)

2021-10-06 17:51 UTC, HeyZeer0 requested changes
Nice additions, some changes are required, nice work on this!

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        return usage / capacity;
Space here!
```suggestion
        }
        
        return usage / capacity;
```

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        Matcher capacity_m = POUCH_CAPACITY_PATTERN.matcher(lore);
Better name these variables, they don't follow the camelCase pattern we use and don't really explain what they really are, something like ``usageMatcher`` would work better! 😄

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        }
Okay, this adds some limitations to the code and make it harder to read, took me like 3 minutes to understand that you were grouping together the number format splits, you can generify your regex to match them all together then replace all spaces in the group with an empty character and then convert it to a number.

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        float capacity = Float.parseFloat(capacity_m.group(1)) * 64;
Emeralds are integers not floats

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        int radius = (UtilitiesConfig.Items.INSTANCE.itemLevelArc) ? 7 : 8;
Move this out of the rendering block, place it together with int x and y so we don't pollute the rendering code. Nice documentation tho, although you could move it to the method documentation since it is a bit long to make it better structured.

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        GlStateManager.enableLighting();
OpenGL works with rendering stacks and Minecraft on 1.12 doesn't really accepts attribute stacks so make sure these are not breaking the render of something else that is on the same matrix stack

2021-10-06 17:51 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +    private static final String LE = "\u00BC\u00B2";
Uh, use the emerald symbols anyways, just replace the switch with an if since it is 2 conditions.

2021-10-06 21:52 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        GlStateManager.enableLighting();
I actually have no idea what these do at all, I just copied the arc rendering from the crafted durability function

2021-10-06 21:55 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        GlStateManager.enableLighting();
It looks like removing all of it breaks the arc rendering though

2021-10-06 22:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        int arcColor = MathHelper.hsvToRGB(120 * inverse_usage / 360.0F, 1.0F, 1.0F);
Inverse_usage could be inlined, as it is only used once.
Is there a reason 120 * inverse_usage / 360.0F is used instead of inverse_usage / 3.0F?

Nice work!

2021-10-06 22:55 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        int arcColor = MathHelper.hsvToRGB(120 * inverse_usage / 360.0F, 1.0F, 1.0F);
Nope, I just directly threw my thought process into there, fixed

2021-10-13 20:03 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/RarityColorOverlay.java
> +        GlStateManager.enableLighting();
After using this quite a bit, it looks like this doesn't break anything in-game, at least on my machine

2021-11-10 18:20 UTC, DonkeyBlaster69 commented
Can't merge until [this](https://discord.com/channels/394189072635133952/743928502314598511/908050918602342451) is fixed

2021-11-11 00:35 UTC, closed without merging