Tier overlay sync
Wynntils/Wynntils-Legacy pull request #353
Opened 2021-10-06 05:16 UTC by DonkeyBlaster69

### Tier Overlay Sync

- Previously, Corkian Amplifiers and elemental powders did not have the option to show their tiers when the "Show Item Levels" hotkey was pressed. Added.
- Added emerald pouch specification overlay as well as "Show Item Levels" hotkey
- Cleaned up roman numeral converting in ItemLevelOverlay.java
- Added a slider to allow users to adjust size of tier specifications. Currently used for powders, emerald pouches, and amplifiers.
- Combined all "Show Item Levels" tier overlays into one setting.

2021-10-06 09:35 UTC, magicus approved these changes
Overall I think this looks good. It is acceptable as-is, but I'd prefer if you could de-duplicate the regexes.

2021-10-06 09:35 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemLevelOverlay.java
> +    private static final Pattern POWDER_NAME_PATTERN = Pattern.compile("(?:Earth|Thunder|Water|Fire|Air|Blank) Powder ([IV]{1,3})");
I'm just curious. What is a "Blank" powder? Never heard about...

2021-10-06 09:35 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern powder = Pattern.compile("§[2ebcf8].? ?(Earth|Thunder|Water|Fire|Air|Blank) Powder ([IV]{1,3})");
Maybe you can reuse the POWDER_NAME_PATTERN here? Or move it to a better class and use it in both locations.

2021-10-06 09:35 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern emeraldPouch = Pattern.compile("§aEmerald Pouch§2 \\[Tier (IX|X|VI{1,3}|IV|V|I{1,3})]");
Same here, seems unnecessary to duplicate the regex.

2021-10-06 14:10 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemLevelOverlay.java
> +    private static final Pattern POWDER_NAME_PATTERN = Pattern.compile("(?:Earth|Thunder|Water|Fire|Air|Blank) Powder ([IV]{1,3})");
It's a powder of non type from corkus which can be exchanged for an elemental powder, still has tiers.

2021-10-06 14:11 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern powder = Pattern.compile("§[2ebcf8].? ?(Earth|Thunder|Water|Fire|Air|Blank) Powder ([IV]{1,3})");
Maybe move it to the Powder class

2021-10-06 14:13 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern emeraldPouch = Pattern.compile("§aEmerald Pouch§2 \\[Tier (IX|X|VI{1,3}|IV|V|I{1,3})]");
Shouldn't the last ] be escaped too?

2021-10-06 17:40 UTC, HeyZeer0 requested changes

2021-10-06 17:40 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern powder = Pattern.compile("§[2ebcf8].? ?(Earth|Thunder|Water|Fire|Air|Blank) Powder ([IV]{1,3})");
Yeah agreed, also compiling the pattern takes time, the appropriate behavior is to make it static

2021-10-06 17:40 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                    }
Pretty sure all of this is already available on the [Powder](https://github.com/Wynntils/Wynntils/blob/development/src/main/java/com/wynntils/core/framework/enums/Powder.java) class, you just need to find retrieve the enum value based on the group, better to keep it centralized so we can easily change it in the future

2021-10-06 17:40 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern emeraldPouch = Pattern.compile("§aEmerald Pouch§2 \\[Tier (IX|X|VI{1,3}|IV|V|I{1,3})]");
Yup, make it static!

2021-10-06 19:41 UTC, DonkeyBlaster69 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                Pattern emeraldPouch = Pattern.compile("§aEmerald Pouch§2 \\[Tier (IX|X|VI{1,3}|IV|V|I{1,3})]");
> Shouldn't the last ] be escaped too?

Is that required? We already escaped the first [ and there are no other ['s in the regex, so the last one is interpreted as a normal character by default

2021-10-06 19:42 UTC, DonkeyBlaster69 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                    }
Yup sounds good, though the Powder class doesn't have specifications for blank powders so that's gonna have to stay

2021-10-06 22:14 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                    }
Is it possible to add blank powder to the Powder class as it is a powder

2021-10-07 00:22 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/ItemSpecificationOverlay.java
> +                    }
> Is it possible to add blank powder to the Powder class as it is a powder

No because blank powders don't have symbols

2021-11-10 14:36 UTC, merged