Emerald Pouch Redirects
Wynntils/Wynntils-Legacy pull request #354
Opened 2021-10-07 03:52 UTC by DonkeyBlaster69

2021-10-08 18:15 UTC, Incompleteusern commented
GameUpdateOverlay#queueEditableMessage seems to be the same as GameUpdateOverlay#queueMessage but it returns the mssage. Since the editing functionality exists for all MessageContainers, you can merge the queueEditableMessage into queueMessage and just return it, as it is redundant currently. 

I like the implementation as it is really clean though.

2021-10-08 18:25 UTC, DonkeyBlaster69 commented
> GameUpdateOverlay#queueEditableMessage seems to be the same as GameUpdateOverlay#queueMessage but it returns the mssage. Since the editing functionality exists for all MessageContainers, you can merge the queueEditableMessage into queueMessage and just return it, as it is redundant currently. 
> 
> I like the implementation as it is really clean though.

I think I tried merging both functions together, and it raised '88 related problems' in IDEA. I don't remember what they were though, I'll take a look in a bit

2021-10-10 20:15 UTC, magicus requested changes

2021-10-10 20:15 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +            @Setting(displayName = "Redirect Emerald Pouch Messages", description = "Should messages about ingredients being added to your pouch be redirected to the game update ticker?")
```suggestion
            @Setting(displayName = "Redirect Emerald Pouch Messages", description = "Should messages about emeralds being added to your pouch be redirected to the game update ticker?")
```

2021-10-11 17:53 UTC, magicus approved these changes

2021-10-13 21:20 UTC, DonkeyBlaster69 commented
If these changes are okay and EmeraldPouchManager.java gets to stay, the usage arc #352 can be updated with those methods, will do that in a PR after all these are merged

2021-11-01 13:18 UTC, magicus approved these changes
I still think this looks good. I'd like to see some other developer chime in (or commit) though, since I'm not so active in the code base right now.

2021-11-10 11:40 UTC, merged