War QOL Feature: Shift + Right click on territory to open /guild territory for the hovered territory in GuildWorldMap
Wynntils/Wynntils-Legacy pull request #411
Opened 2021-12-28 20:22 UTC by kristofbolyai

Added a feature to the GuildWorldMap so that the player can Shift + Right-Click on a hovered territory to run `/guild territory <hovered territory name>`.

The feature can be disabled with a map button.

2021-12-28 20:28 UTC, Incompleteusern reviewed
LGTM

2021-12-28 20:28 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapTerritory.java
> +    public boolean IsBeingHovered(int mouseX, int mouseY) {
Make the function name be in camel Case

2021-12-28 20:28 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +            McIf.mc().displayGuiScreen(null);
Maybe use `Utils#displayGuiScreen`

2021-12-28 21:44 UTC, Incompleteusern reviewed
Last thing

2021-12-28 21:44 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        clicking[1] = Mouse.isButtonDown(1);
You might be missing 
```        clicking[0] = Mouse.isButtonDown(0);```

2021-12-28 21:46 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        clicking[1] = Mouse.isButtonDown(1);
I leave it out on purpose, I don't need `clicking[0]` at that time and it will be updated when `super.handleMouseInput();` is called.

2021-12-29 21:13 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        clicking[1] = Mouse.isButtonDown(1);
Then why is clicking[1] done

2021-12-29 21:17 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        clicking[1] = Mouse.isButtonDown(1);
> Then why is clicking[1] done

It is used by this override. Do you want me to replace `clicking[1]` with `Mouse.isButtonDown(1);`?


```
//Check for shift + left click
if (!territoryManageShortcut || !clicking[1] || !Keyboard.isKeyDown(Keyboard.KEY_LSHIFT)) {
    super.handleMouseInput();
    return;
}
```

2021-12-30 12:20 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        clicking[1] = Mouse.isButtonDown(1);
Yes, that looks much better. Don't drag `clicking` into this.

2021-12-30 12:21 UTC, magicus requested changes

2021-12-30 12:21 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +            McIf.player().sendChatMessage("/guild territory "+territory.getTerritory().getName());
```suggestion
            McIf.player().sendChatMessage("/guild territory " + territory.getTerritory().getName());
```

2021-12-30 14:26 UTC, magicus approved these changes

2021-12-30 14:33 UTC, merged