Lootrunning features added: Dry streak, dry boxes, death message with coordinates
Wynntils/Wynntils-Legacy pull request #415
Opened 2021-12-29 20:09 UTC by kristofbolyai

New features added:
- Toggleable option to have a message displaying the player's death position, clickable action to set waypoint there. Useful when lootrunners die during lootruns, they can go back to their exact position without remembering where they died.
![image](https://user-images.githubusercontent.com/49001742/147699553-1937ea45-181c-484c-8946-ac1affc33094.png)

- `%dry_streak%` and `%dry_boxes%` info variables added: Dry streak variables display how many chests were opened since last mythic finding in a loot chest, dry boxes count the number of unidentified item boxes since last mythic. This feature can be toggled.

2021-12-29 21:09 UTC, Incompleteusern requested changes
Some things

2021-12-29 21:09 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +    public void onMythicFound(PacketEvent<SPacketWindowItems> e) {
Inject this into the existing mythic found code

2021-12-29 21:09 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +
Try to remove lastplayerlocation through a packetevent if you can’t with the event

2021-12-29 21:09 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +
You could also instead of click here for compass, do the underline and events for the coords themselves

2021-12-29 21:09 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +            UtilitiesConfig.INSTANCE.dryStreakBoxes += 1;
Currently if I have a page with Unid items in the bank and flip to them back and forth you can arbitrarily increase the dry count

2021-12-29 21:09 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +            UtilitiesConfig.INSTANCE.dryStreakBoxes += 1;
Also a crafted would too if it contained Unidentified

2021-12-29 21:14 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +            UtilitiesConfig.INSTANCE.dryStreakBoxes += 1;
> Currently if I have a page with Unid items in the bank and flip to them back and forth you can arbitrarily increase the dry count

`if (!chest.getLowerInv().getName().contains("Loot Chest")) return;` prevents that?

2021-12-29 21:19 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +
> Try to remove lastplayerlocation through a packetevent if you can’t with the event

Wdym by remove? Do you want me to set it to null when the feature is disabled? Or when `!Reference.onWorld` is false?

2021-12-29 21:24 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +            UtilitiesConfig.INSTANCE.dryStreakBoxes += 1;
> Currently if I have a page with Unid items in the bank and flip to them back and forth you can arbitrarily increase the dry count
> Also a crafted would too if it contained Unidentified

Tested, works as intented.

2021-12-29 21:31 UTC, kristofbolyai commented
Is the event okay now? I merged it with the mythic sound effect one, moved it to the utilies/ClientEvents file.

2021-12-29 21:43 UTC, kristofbolyai commented
Merging the events causes a complexity check fail, is that to be ignored?

2021-12-29 22:14 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +
Nvm you probably want it changed so it is not needed at all.

2021-12-29 22:36 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +
I believe death can only be determined with the chat message. Could try attaching the chat event with PacketEvent<SPacketEntityTeleport> somehow and seeing how it functions, but in the end it would result in loads of bugs.

2021-12-30 15:54 UTC, Incompleteusern reviewed
Last last things

2021-12-30 15:54 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                UtilitiesConfig.INSTANCE.dryStreakBoxes = 0;
You probably can remove all the `foundMythic` and just return here since I doubt you want to count other boxes in the chest when there's also a mythic

2021-12-30 15:54 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (chest.getLowerInv().getName().contains("Loot Chest")) {
This can be cheesed still by bank pages

2021-12-30 15:54 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                ITextComponent textComponent = new TextComponentString("Dry streak broken! Mythic found!");
Only send this if `enableDryStreak` is enabled, maybe encorporate drystreak data into it but optional

2021-12-30 16:05 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                UtilitiesConfig.INSTANCE.dryStreakBoxes = 0;
Later code returns correctly, returning there would cause duplicate code.

```java
foundMythic = true;
UtilitiesConfig.INSTANCE.dryStreakCount = 0;
UtilitiesConfig.INSTANCE.dryStreakBoxes = 0;    //<--- Resets

if (MusicConfig.SoundEffects.INSTANCE.mythicFound)  //<----Play sound, if enabled
SoundTrackManager.findTrack(WebManager.getMusicLocations().getEntryTrack("mythicFound"),
        true, false, false, false, true, false);

if (UtilitiesConfig.INSTANCE.enableDryStreak) { //<---- Send message
    ITextComponent textComponent = new TextComponentString("Dry streak broken! Mythic found!");
    textComponent.getStyle()
            .setColor(TextFormatting.DARK_PURPLE)
            .setBold(true);
    McIf.player().sendMessage(textComponent);
}
break; //<--- If mythic was found break from loop.
}

if (!foundMythic) //<---Increase value if no mythic
UtilitiesConfig.INSTANCE.dryStreakCount += 1;

UtilitiesConfig.INSTANCE.saveSettings(UtilitiesModule.getModule()); //<----Save dry count and dry boxes  values, then return
return;
```

2021-12-30 16:59 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                UtilitiesConfig.INSTANCE.dryStreakBoxes = 0;
ah

2021-12-30 17:00 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (chest.getLowerInv().getName().contains("Loot Chest")) {
Fix this and Ill merge

2021-12-30 17:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (chest.getLowerInv().getName().contains("Loot Chest")) {
Actually this involes a lot more, turns out naming a bank page "Loot Chest" causes a crash, with code in development, also turns out PacketEvent<SPacketWindowItems> is faster than minecraft opening the gui, so it causes problems.
Working on a fix.

2021-12-30 17:07 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (chest.getLowerInv().getName().contains("Loot Chest")) {
Seems like when opening a chest with an interactable item (horse, weapon) `PacketEvent<SPacketWindowItems>` in the event, the current gui is `null`. Any easy workaround I don't know about?

2021-12-30 17:17 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (chest.getLowerInv().getName().contains("Loot Chest")) {
what

2021-12-30 17:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (chest.getLowerInv().getName().contains("Loot Chest")) {
Here,
```java
 @SubscribeEvent
    public void onMythicFound(PacketEvent<SPacketWindowItems> e) {
        if (McIf.mc().currentScreen == null) return;
        if (!(McIf.mc().currentScreen instanceof ChestReplacer)) return;

        ChestReplacer chest = (ChestReplacer) McIf.mc().currentScreen;
```

`McIf.mc().currentScreen` is `null` if the loot chest is opened with an item in hand, if opened with an empty hand it works fine.

2021-12-30 21:09 UTC, merged