Fixed jumpy map zooming (along with other fixes) and added setting: Map auto close on movement and different tier loot chests now have configurable minimum zoom levels
Wynntils/Wynntils-Legacy pull request #430
Opened 2022-01-02 13:02 UTC by kristofbolyai

Changed and fixes: 
- Fixed jumpy zooming in and out.
- Added setting to auto close the map on movement: Only works if the user is NOT holding the map key, otherwise behavior is unchanged.
- There are now settings for all different loot chest tiers to set the minimum zoom level needed to display them on the map.
- Also fixed some really old typo (This might break compatibility with older versions when the user tries to load waypoints from copy-paste data, if it contains a CHEST (T3). Can't do much about this, users will update and it will go away.) 
- At some comments and code parts maximum zoom level was only 300, while it is 500, changed it for consistency

2022-01-02 15:03 UTC, HeyZeer0 reviewed
Thanks for your contribution. Just some changes need to be made and it will look really good!
On the other side, the icon zoom config seems a bit hacky, personally, I would prefer it removed but I'll let the others decide 😄

Thanks again!

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +
The player can be moved by external actions, specifically check for the movement keybinds for better precision, and it will also remove the required variables. Just as a future tip for checking if the player moved this way, check if the player movement (movX, movY, movZ) != 0

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/MainWorldMapUI.java
> +
Same as above, also to not duplicate code please move this to a method and call it on both instances

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/MainWorldMapUI.java
> +    //Only updated if MapConfig.WorldMap.INSTANCE.autoCloseMapOnMovement is true, don't rely on this for anything else
Space after the //
```suggestion
    // Only updated if MapConfig.WorldMap.INSTANCE.autoCloseMapOnMovement is true, don't rely on this for anything else
```

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/instances/WaypointProfile.java
> +    }
Please follow our code patterns!
```suggestion
    public void setZoomNeeded(int zoomNeeded) {
        this.zoomNeeded = zoomNeeded;
    }
```

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +        public boolean autoCloseMapOnMovement = true;
Disabled by default
```suggestion
        public boolean autoCloseMapOnMovement = false;
```

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        }
I don't get the purpose of the `holdingDecided` variable? Aren't you able to just use the holdingMapKey? 🤔

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/WorldMapUI.java
> +                        }
Don't check for the display name, check literally for the enum values!
```suggestion
                        switch (waypointProfile.getType()) {
                            case LOOTCHEST_T1:
                                waypointProfile.setZoomNeeded(MapConfig.WorldMap.INSTANCE.lootChestTier1MinZoom);
                                break;
                            case LOOTCHEST_T2:
                                waypointProfile.setZoomNeeded(MapConfig.WorldMap.INSTANCE.lootChestTier2MinZoom);
                                break;
                            case LOOTCHEST_T3:
                                waypointProfile.setZoomNeeded(MapConfig.WorldMap.INSTANCE.lootChestTier3MinZoom);
                                break;
                            case LOOTCHEST_T4:
                                waypointProfile.setZoomNeeded(MapConfig.WorldMap.INSTANCE.lootChestTier4MinZoom);
                                break;
                        }
```

2022-01-02 15:03 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/WorldMapUI.java
> +        float percentage = MathHelper.clamp(1f - (zoomEnd - McIf.getSystemTime()) / ZOOM_RESISTANCE, 0f, 1f);
It is probably wise as well to avoid these issues in the future to replace the system time with nanoseconds (`System.nanoTime()`) since this one is calculated by the JVM and has higher precision. Tho some extra stuff will need to be changed if that's a lot of work, don't mind it 😄

2022-01-02 15:04 UTC, HeyZeer0 requested changes
Forgot to request the changes lol

2022-01-02 15:16 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        }
It is used in the code part below. We can't check for `!holdingMapKey` as it is defaulted to false, the condition will not work properly. That is why `holdingDecided` is introduced.

```java
            if (holdingDecided && !holdingMapKey && (lastPlayerX != Double.MAX_VALUE && lastPlayerZ != Double.MAX_VALUE) && (currentPosX != lastPlayerX || currentPosZ != lastPlayerZ)) {
                McIf.mc().displayGuiScreen(null);
                return;
            }
```

2022-01-02 19:09 UTC, TomR24 commented
Another cool thing would be an option to have the map become partially transparent when moving

2022-01-02 19:16 UTC, kristofbolyai commented
> Another cool thing would be an option to have the map become partially transparent when moving

Perhaps, may do it sometime later. (Definitely not this PR tho.)

2022-01-02 19:23 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/WorldMapUI.java
> +        float percentage = MathHelper.clamp(1f - (zoomEnd - McIf.getSystemTime()) / ZOOM_RESISTANCE, 0f, 1f);
Changed in https://github.com/Wynntils/Wynntils/pull/430/commits/587d8537fff526d69b3a9eb254e65e39d7e4b504.

Was it that simple or did I miss something? 🤔

2022-01-02 19:26 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        }
This is actually outdated now, as I extracted this into a new method, but same idea applies, we need to know 
if holding was decided or otherwise we might use `holdingMapKey`  before it was set, hence why `holdingDecided` was added.

See `WorldMapUI.java` line 542, the reason this was a needed change.

2022-02-13 17:47 UTC, HeyZeer0 requested changes
Awesome!! Feel free to merge it yourself whenever the last changes were made!

Thanks! 😄

2022-02-13 17:47 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +
Please follow our code standards! 
```suggestion
        if (MapConfig.WorldMap.INSTANCE.autoCloseMapOnMovement && checkForPlayerMovement(holdingDecided, holdingMapKey))  {
            McIf.mc().displayGuiScreen(null);
            return;
        }

```

2022-02-13 17:47 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/map/overlays/ui/MainWorldMapUI.java
> +
Please follow our code standards!
```suggestion
        if (MapConfig.WorldMap.INSTANCE.autoCloseMapOnMovement && checkForPlayerMovement(holdingDecided, holdingMapKey))  {
            McIf.mc().displayGuiScreen(null);
            return;
        }

```

2022-02-13 19:30 UTC, merged