Added ingredient guide and ingredient favoriting
Wynntils/Wynntils-Legacy pull request #436
Opened 2022-01-05 19:04 UTC by kristofbolyai

Finally got around doing this somewhat long awaited feature. The main focus was implementing the favoriting of ingredients. This means that while the guide is fully working, the search functions are very limited right now. In an upcoming PR, I am planning to address this and add the Advanced and Basic search modes the item guide has.

Some "bugs" or things that may need change, but I need input/help with:
- Those ingredients with player heads don't load the skin (Yes I did set the NBT data)
- Spawner eggs don't have the correct "color" (type)
- Quest book menu for the ingredient guide has the same icon (compass) as the item guide, not sure what to change it to nor how to do it

Few screenshots can be found here: https://imgur.com/a/OMSbaRd

2022-01-05 21:48 UTC, P0keDev commented
For skull textures, you can copy over [this method](https://github.com/P0keDev/Wynntils/blob/7fe9a2bd30e5a2d16245590a48313fdae1e1ff25/src/main/java/com/wynntils/core/utils/ItemUtils.java#L92). Should be noted that the textures are hard-coded into Athena since they're not in the API at all, and they're probably not up to date since I did them a year ago

2022-01-05 21:49 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +            itemLore.add(TextFormatting.RED + "Untradeable Item");
Should be "Untradable" in item lore

2022-01-05 21:54 UTC, kristofbolyai commented
> For skull textures, you can copy over [this method](https://github.com/P0keDev/Wynntils/blob/7fe9a2bd30e5a2d16245590a48313fdae1e1ff25/src/main/java/com/wynntils/core/utils/ItemUtils.java#L92). Should be noted that the textures are hard-coded into Athena since they're not in the API at all, and they're probably not up to date since I did them a year ago

Already doing most of that, except the random uuid. Kinda strange how that is needed, but thanks, add this next commit.

2022-01-06 00:47 UTC, Incompleteusern commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +    transient Map<ItemModifierType, ItemModifier> itemModifiersTypeMap = new HashMap<>();
`itemModifiersList` and `itemModifiersTypeMap` should be merged imo, maybe `itemModifiers` and `itemModifiersList` plus `ingredientModifiers` and `ingredientModifiersList`

2022-01-06 11:54 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +    transient Map<ItemModifierType, ItemModifier> itemModifiersTypeMap = new HashMap<>();
Merged `itemModifiersList` into `itemModifiersTypeMap`, but would rather keep `itemModifiersTypeMap`, may save lot of processing later on when search features are added. Also removed `ingredientModifiersList` but I may add them back later on, when search features are added, if they are worth caching instead of more processing.

2022-01-06 11:56 UTC, kristofbolyai commented
> For skull textures, you can copy over [this method](https://github.com/P0keDev/Wynntils/blob/7fe9a2bd30e5a2d16245590a48313fdae1e1ff25/src/main/java/com/wynntils/core/utils/ItemUtils.java#L92). Should be noted that the textures are hard-coded into Athena since they're not in the API at all, and they're probably not up to date since I did them a year ago

Also fixed this, did not mention it in PR.

2022-01-07 23:03 UTC, P0keDev requested changes
Went over things in more detail, feel free to ask for clarification on anything

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +        builder.append(ingredientTier.getBracketColor()).append("]");
The entire tier string should be defined in the IngredientTier enum, instead of building it in this messy way

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +            stack = new ItemStack(Item.getByNameOrId(material));
Brackets should be consistent

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +    //transient List<IngredientModifier> ingredientModifiersList = new ArrayList<>();
Don't include commented out code

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +    }
This implementation for modifiers (both item and ingredient) is quite messy - a better approach would be to define container objects like is done [here](https://github.com/Wynntils/Wynntils/blob/7d6e7fc65fe981542ed5684078afc8f405a1cadf/src/main/java/com/wynntils/webapi/profiles/item/objects/ItemRequirementsContainer.java), which is what I intended when designing the format of the Athena ingredient list

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +        ItemModifier duration = itemModifiersTypeMap.get(ItemModifierType.DURATION);
See other comment on modifiers

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +            itemLore.add(TextFormatting.RED + "Untradeable item");
Already mentioned this, should be "Untradable Item"

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +        {
Unless the entire method is formatted into these blocks (which I don't recommend), this shouldn't be its own block

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +                {
Bracket should be on same line as the if statement

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
This should not be hard-coded like this, if it's not getting parsed correctly then something may need to change on Athena's end

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +}
Use the `@SerializedName` annotation on the enum definitions instead, so you can directly serialize the numbers into the corresponding tier enum

2022-01-07 23:03 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
Don't think this should be here

2022-01-08 16:52 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
```java

2022-01-08 17:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
Actually that whole inheritance is not needed, fixed.

2022-01-08 18:11 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
This is getting parsed as `Gather X P Bonus`, needs to be changed to `gatherXpBonus` in Athena?

2022-01-08 18:27 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
Removed the hardcoded part.

2022-01-08 18:31 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/item/objects/IdentificationContainer.java
> +
Also, when/if we change that in Artemis, we should get the skull textures updated.

2022-01-12 23:57 UTC, Incompleteusern requested changes
Very cool! Also the icon is the same as item page since its passed the same to the constructor

2022-01-12 23:57 UTC, Incompleteusern commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientProfile.java
> +        int notTouching = ingredientModifiers.getNotTouching();
Please most most of this stack lore generation to the relevant classes. 

It might be good to remove the enums and inline the lore line generation, but that's up to you.

2022-01-13 16:22 UTC, kristofbolyai commented
> Also the icon is the same as item page since its passed the same to the constructor. If you want to change it, either make an icon yourself and create a reference to it, or I can put in the creative-team channel to ask for one to be made if you want.

Yes, I was aware why it was the same, but yes, asking the creative people would be helpful, I'm not an artist myself.

2022-01-18 23:09 UTC, Incompleteusern commented
Okay, Ill add a message in the channel later

2022-01-19 22:51 UTC, P0keDev reviewed
Apologies for taking so long to look over this

Overall looks good, although the modifier enums seem a bit unnecessary - they could probably be replaced with helper functions within the container classes, if not directly coded into the lore generation. Someone else may want to weigh in on that, though

2022-01-19 22:51 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +    TIER_3(3, "§3[§b✫✫✫§3]");
It's usually better to use `TextFormatting` than to directly include the color codes like this

2022-01-20 08:28 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +    TIER_3(3, "§3[§b✫✫✫§3]");
@P0keDev You think that? I typically prefer to use the literal strings, since these can be copied/compared directly with the output from Wynncraft. (Unless it's a string that *we* create to display to the user, then TextFormatting.RED etc is better)

2022-01-20 08:32 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +    TIER_3(3, "§3[§b✫✫✫§3]");
@magicus What do you think about removing the enums? Should we keep it or move to helper function or add it into lore generation?

2022-01-20 22:46 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +    TIER_3(3, "§3[§b✫✫✫§3]");
@magicus I prefer it because it's easier to understand and less prone to mistakes. Raw color codes are fine for checking Wynn messages in my opinion, since those messages are often a jumble of colors and what colors they are isn't super relevant, but for something like this I believe using `TextFormatting` is better - ultimately it's fine either way

2022-01-20 23:22 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +    TIER_3(3, "§3[§b✫✫✫§3]");
I needed to check the usage. Yes, I agree with you now. If it's used this way (to create strings of our own), TextFormatting is better.

2022-01-20 23:23 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +    TIER_3(3, "§3[§b✫✫✫§3]");
@kristofbolyai I have no strong opinion on that. The code looks fine to me (but I have not spent too much time understanding all details).

2022-01-23 17:44 UTC, Incompleteusern approved these changes

2022-01-25 05:30 UTC, P0keDev requested changes
My bad, I should've been more explicit - my comment on enums was referring to `IngredientModifierType` and `ItemModifierType`, and what I said about the tier enum was unrelated to that (which, for the record, is a better implementation than simply using an integer in my opinion).

Also, after taking a closer look, I can confidently say that those two enums should be removed; they contribute very little besides making everything more verbose.

2022-01-25 05:30 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
You could simply pass the appropriate lore string into this function and use it, instead of passing it a string that has to be parsed into an enum which stores the lore string in question.

2022-01-25 05:30 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +    }
The same applies here. I also recommend using braces for the outer if statements here.

2022-01-25 18:18 UTC, magicus approved these changes
LGTM!

2022-01-26 02:07 UTC, P0keDev requested changes

2022-01-26 02:07 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +    }
This method is completely unnecessary -- you pass a string to `getFormattedModifierText` only to use a switch statement that turns it into a different string (or even the same string). Remove this and pass the formatted string into `getFormattedModifierText`.

2022-01-26 02:07 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Same issue here - remove this method

2022-01-26 02:07 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +        else if (modifierValue > 0) {
Should be all one line

2022-01-26 06:05 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +    }
I mean, in the end it has to be parsed somewhere, so its just a matter of moving that code? Also, I made that switch have "useless" cases so all modifiers are defined in the code aswell, but I can see why we could remove it.

2022-01-26 12:06 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Is this not about converting one "type" of string to another? More precisely, mapping from how values are stored in the source json, to how information should be presented to the user. If this is the case, I do indeed see an argument for keeping both this and the other string conversion method.

2022-01-26 12:14 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
> Is this not about converting one "type" of string to another? More precisely, mapping from how values are stored in the source json, to how information should be presented to the user. If this is the case, I do indeed see an argument for keeping both this and the other string conversion method.

That is the case. See https://github.com/Wynntils/Wynntils/pull/436#discussion_r792335077

2022-01-26 15:55 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Maybe the original enum did have a purpose after all, then. I think I disagree with @P0keDev here, and would argue that the enum did have a code clarity purpose, but that it -- if anything -- did not go far enough. If it had, I don't think Poke would have suggested that it should be removed. 

Let's make sure we are all aboard for this, before doing further changes and then just reverting them. :-) What if you restored a enum type, with the following features:
 * a factory method that makes it clear they are created from json, e.g. `IngretientPlacement::fromJsonMarker(String s)`
 * a string output method that makes it clear it is for the GUI, e.g. `getFriendlyName()`

@P0keDev Would you find that reasonable? (My reasoning is about both enum types)

2022-01-26 15:55 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +        else if (modifierValue > 0) {
This I agree with fully ;-)

2022-01-26 16:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
> a factory method that makes it clear they are created from json, e.g. `IngretientPlacement::fromJsonMarker(String s)`

Not quite sure what that would change except marking that it is created from JSON which is already in the `webapi/profiles` folder, wouldn't that be enough?

2022-01-26 22:47 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Am I missing something? The only time this method is used is to convert a string literal passed into `getLoreLines`, as seen in `generateAllLoreLines`. I don't see it used anywhere to convert api values.

2022-01-27 07:51 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
@P0keDev , where do you suggest to do the parsing of the api then? It has to be done as API returns the modifier values but only a short name. For example: you have to convert `left` into `to the left of` when making the ingredient lores. Same with some other modifiers.

2022-01-27 09:48 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
@P0keDev The enums represent an abstract concept. This concept is realized in two different ways in the code: as a string in the json representation, and as a string for the user interface. 

So while it might seem like this is "converting" one string to another, that's mostly due to circumstances. What if the json representation had used integers instead, like 1 for left, 2 for right, etc. Would you have agreed in that case that the enum makes sense?

2022-01-27 10:32 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
@magicus I'm afraid I don't understand your point, because the format of the json representation doesn't need to be kept track of or parsed - it's deserialized for us. All of the information about the modifiers is extracted and stored using the variables `left`, `right`, `under`, etc. Every ingredient follows the same format, so all you need is the raw number values. With those, you already know exactly how to construct the ingredient lore. There is no reason to convert from anything to anything, because the raw values are the only information that varies between ingredients. If the issue is about avoiding string literals within the code, constants could be used and named accordingly - I don't see what an enum provides besides unnecessary bloat.

2022-01-27 10:35 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Oh, I think I see what you mean now, the IngredientProfile lore generation could just get the value and use the correct strings there.

2022-01-27 10:35 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
@kristofbolyai The only thing being parsed from the api is the numbers. The variables have names, and we know exactly what corresponds to what. The leftward ingredient modifier is stored in `left` - to format the string, you just need to return `left + "% Ingredient Effectiveness (Ingredients to the left of this one)`

2022-01-27 10:37 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
> @kristofbolyai The only thing being parsed from the api is the numbers. The variables have names, and we know exactly what corresponds to what. The leftward ingredient modifier is stored in `left` - to format the string, you just need to return `left + "% Ingredient Effectiveness (Ingredients to the left of this one)`

Yep, got it.

2022-01-27 10:38 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Waiting for @magicus before changing this.

2022-01-27 10:39 UTC, P0keDev commented
For the record, when I was designing the format of the Athena ingredient api, I had the implementation of [ItemRequirementsContainer](https://github.com/Wynntils/Wynntils/blob/development/src/main/java/com/wynntils/webapi/profiles/item/objects/ItemRequirementsContainer.java) in mind for these specific stats.

2022-01-28 07:44 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +            if (modifierValue > 0)
Also, multi-line if statements without braces is a recipe for problems. Please use braces.

2022-01-28 07:45 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientItemModifiers.java
> +            if (modifierValue > 0)
See e.g. https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/ for a cautionary tale.

2022-01-28 07:54 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Ok, now I have dived much deeper into the change than I did before. :-)

I think I see @P0keDev's point now. You have a single method with a switch, but this is only called with hard-coded string literals, so it can essentially be "inlined" at "compile time", and thus "inlined" at the source level.

I can agree with that. 

However. I still think we're missing some opporunity for code improvement. Let me see if I can be more concrete in what I mean. TBC.

2022-01-28 08:03 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Normally, I'd say that the start would be to convert the long list of integer members to an array. But that will break the json deserializing. :-( Right now I can't think of a good way to solve this (more than the realization that automagic deserialization of json can be anathema to good design). What I'd like to see, basically, is generateAllLoreLines turned into a loop, instead of a set of hard-coded duplicated pieces of code. 

Maybe the best solution would be to have a really, really simple holder class for json deserialization, and then move the results from that class, into a more general class that can associate each json field with an array `int[] modifiers`, and a corresponding `String[] modifiersDesc = { "to the left of", ... }`

Then we could have just one instance of "parsing" the json, when assigning `modifiers[0] = jsonObj.left` etc.

2022-01-28 08:04 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
If it's worth the trouble, I don't know. Otherwise just go with the code duplication and Pokes suggestions.

2022-01-28 08:40 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Reading through all of this, I think, this PR we should use P0ke's implementation idea, fix obvious code format issues and create a new draft PR and discuss the refactoring of the deserialization (maybe including Item Guide aswell). @magicus @P0keDev, what do you think?

2022-01-28 09:05 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
I'm okay with that. I'm also okay with not doing a follow-up PR. It's not the most pressing issue in Wynntils.

2022-01-28 09:36 UTC, P0keDev commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
Sounds good to me.

The more hardcoded, redundant implementation that's already used for items certainly isn't the cleanest, but I do think it has benefits in being easier to understand and not quite as verbose. Of course, if you really wanted to, you could have the best of both worlds by reformatting the api to use arrays, so we could deserialize those directly. Ultimately, I think it would be more trouble than it's worth.

2022-01-28 10:30 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +    }
My rule of thumb is that copying code once or twice is better than abstracting, but after that, the DRY principle wins. But, let's keep it this way now. Maybe we can rethink things for Artemis.

2022-01-28 13:14 UTC, kristofbolyai commented
Oops, I did not mean to request a review from Incompleteusern, sorry about that.

A fourth check might not be unnecessary on this PR though, just to make sure everybody agrees.

2022-01-28 13:34 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +        switch (modifierName) {
I still think you're missing the point..? The idea was that you shouldn't do any string replacement here, but call it with "to the left of" instead of "left" as the single place in the code where you're calling it with a string literal "left".

2022-01-28 13:34 UTC, magicus commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +        switch (modifierName) {
At least that's what I thought that Poke and I agreed on. :-)

2022-01-28 13:39 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/IngredientModifiers.java
> +        switch (modifierName) {
Oh, right, fixed it now. 😅

I totally got sidetracked by those minor refactorings.

2022-01-28 15:25 UTC, magicus approved these changes
Getting kind of lost now on what to look for, but I think this looks ok and has a promise to be the final iteration. :) Let @P0keDev have a look as well first, then you can push.

2022-01-28 23:46 UTC, P0keDev approved these changes

2022-01-28 23:46 UTC, merged