Adding soul points to /s command
Wynntils/Wynntils-Legacy pull request #451
Opened 2022-02-12 18:49 UTC by PhoenixImpulse

Made it so /s sp and /s nextsoulpoint will return 10 upcoming sp worlds

2022-02-12 18:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\n\nmore detailed help:\n/s <command> help \nSkill Points:\nnextsoulpoint";
Please make this so it follows the  help menu standards

2022-02-12 18:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                        break;
You can stack cases, no need to repeat code

2022-02-12 18:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\n\nmore detailed help:\n/s <command> help \nSkill Points:\nnextsoulpoint";
Also make sure the help command includes the aliases as well.

2022-02-12 19:01 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/ServerListManager.java
> +    public static Map<String, ServerProfile> getAvailableServers(){
Please add space before `{`.

2022-02-12 19:02 UTC, kristofbolyai commented
Also please close #450 if this is the working PR.

2022-02-12 19:37 UTC, PhoenixImpulse commented
fixed everything i was told to do now complete i think

2022-02-12 19:41 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
Space after `if` and before and after brackets and `==` please. Just in general try to follow code standards.

2022-02-12 19:44 UTC, kristofbolyai commented
> fixed everything i was told to do now complete i think

I think you missed this one.
https://github.com/Wynntils/Wynntils/pull/451#discussion_r805192306

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                style.setStrikethrough(false);
No need to set these.

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                style.setInsertion("");
Same as above, no need to set these.

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                HoverEvent hoverEvent = new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString(TextFormatting.RED + "You require Champion or Hero to access this feature."));
Change text to "HERO or higher rank is required to use /switch"

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                style.setClickEvent(clickEvent);
No need for these.

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\n\nmore detailed help:\n/s <command> help \nSkill Points:\nnextsoulpoint";
```suggestion
        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers\n\nmore detailed help:\n/s <command> help";
```

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                style.setObfuscated(false);
Not needed.

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            TextComponentString sent = new TextComponentString("§b- §6");
Use `TextFormatting.BOLD` and `TextFormatting.GOLD`.

2022-02-13 13:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                style.setInsertion("");
Not needed.

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers\n\nmore detailed help
```suggestion
        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers\n\nmore detailed help:\n/s <command> help";
        }
```

Sorry about this, my bad I think.

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        TextComponentString toSend = new TextComponentString("\n" + "§bApproximate soul point times:" + "\n");
No need for a newline before the message. Also no need to set it to bold, you do it with a style later on.

```suggestion
        TextComponentString toSend = new TextComponentString("Approximate soul point times:" + "\n");
```

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                TextComponentString wc = new TextComponentString(TextFormatting.BLUE + wynnServer);
Rename `wc` to `serverLine`.

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .setObfuscated(false)
Try removing these, now with the refactoring it should not crash.

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .setInsertion("");
Remove this, same as above.

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .setStrikethrough(false)
Also remove this.

2022-02-13 15:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .setInsertion("")
Same as before.

2022-02-13 16:29 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                sent.appendSibling(wc);
Rename `wc` here aswell.

2022-02-13 16:29 UTC, kristofbolyai commented
Rename that variable, otherwise looks good to me.

2022-02-13 17:59 UTC, HeyZeer0 requested changes
Awesome!! Thanks for contributing to Wynntils. 
We appreciate the help, just some changes and this should be ready!

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/ServerListManager.java
> +
Remove this empty white space
```suggestion
```

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/ServerListManager.java
> +    }
This code should be inside the ServerProfile and use the methods already available in there. The name of the method is also inverted, something like this would work:
```java
    public static int getUptimeMinutes() {
        return (int) (getUptime() / TimeUnit.MINUTES.toMillis(1));
    }
```

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/managers/ServerListManager.java
> +
This should be located below the ``getServer`` method.

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +
Remove this useless white space
```suggestion
```

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
Space this
```suggestion

            TextFormatting minuteColor;
            if (uptimeMinutes <= 2) {
                minuteColor = TextFormatting.GREEN;
            } else if (uptimeMinutes <= 5) {
                minuteColor = TextFormatting.YELLOW;
            } else {
                minuteColor = TextFormatting.RED;
            }
            
```

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if(WebManager.getPlayerProfile() != null && (WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.PlayerTag.HERO || WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.Pl
Space between the if and the condition
```suggestion
            if (WebManager.getPlayerProfile() != null && (WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.PlayerTag.HERO || WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.PlayerTag.CHAMPION)) {
```

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            sender.sendMessage(sent);
Space between the condition and the last action
```suggestion
            }
            
            sender.sendMessage(sent);
```

2022-02-13 17:59 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        }
I feel like this could be done in a cleaner way, you don't exactly need the minutes, you can always just use the MS, but it is fair!

2022-02-13 18:57 UTC, kristofbolyai commented
@PhoenixImpulse Check all the open requests, I closed those which were fixed.

2022-02-13 19:26 UTC, kristofbolyai commented
Looks ok to me now.

2022-02-14 11:23 UTC, magicus commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (WebManager.getPlayerProfile() != null && (WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.PlayerTag.HERO || WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.P
Personally I'd have extract this into a `boolean canUseSwitch` outside the for loop. Partly it's due to old school premature optimization thinking, but I also think it makes it clearer. You might want to get opinions from someone else than me on this, though...

2022-02-14 11:24 UTC, magicus reviewed
Overall looks very good!

2022-02-14 13:35 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (WebManager.getPlayerProfile() != null && (WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.PlayerTag.HERO || WebManager.getPlayerProfile().getTag() == PlayerStatsProfile.P
Maybe add it as a method in `PlayerTag`?

2022-02-14 15:39 UTC, kristofbolyai commented
Also small thing, could you rename the pull request? I think you accidentally misstyped it. Maybe something like "Adding soul point timers to /s" or something along those lines would be better. 👍

2022-02-14 15:44 UTC, magicus commented
@kristofbolyai Funny how you can be so blind to the obvious... I did not even see that. :) And yet "Do the patch do what it claims to do" is like the fundamental code reviewing rule.

2022-02-14 17:56 UTC, kristofbolyai requested changes

2022-02-14 17:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers and if you add switch
```suggestion
        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers\n\nmore detailed help:\n/s <command> help";
```

2022-02-14 17:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers and if you add switch
Instead of putting that description there, maybe add a check if `args[1] == "help"` and make it display the help for the subcommand and talk about the "switch" argument there.

Example: 
```java
        TextComponentString text;
        if (options.contains("help")) {
            text = new TextComponentString(
                    "Usage: /s list [type] [options]\n order of types and options does not matter\nDefault: print all servers oldest to new\n\ntypes:\n");
            for (String type : serverTypes) {
                text.appendText(String.format("  %s\n", type));
            }
            text.appendText("options:\n");
            text.appendText("  g, group : group servers by type\n");
            text.appendText("  s, sort : sort servers alphabetically, sets group flag\n");
            text.appendText("  c, count : print amount of online servers\n");
            text.appendText("  h, help : this help\n");
            sender.sendMessage(text);
            return;
        }
```

2022-02-14 17:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            else{
```suggestion
            else {
```

2022-02-14 17:58 UTC, kristofbolyai commented
Please implement the requested changed, let me know if you have questions regarding them. Also, good job implementing `PlayerTag.canUseSwitch()`.

2022-02-14 18:31 UTC, kristofbolyai reviewed
Those 2 small things, other than that it looks good!

2022-02-14 18:31 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +
Remove this useless line.

2022-02-14 18:31 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +
Remove this useless line.

2022-02-14 18:32 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +
Basically make it so the `}` and the `else` is in the same line.
Something like: `}  else if ...`

2022-02-14 18:35 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            else {
My bad on this, should have explained this better.

```suggestion
} else {
```

2022-02-14 18:36 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +} else {
```suggestion
            } else {
```

2022-02-14 18:37 UTC, kristofbolyai commented
Looks very good now!

2022-02-14 22:11 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
>              TextComponentString text = new TextComponentString("Usage: /s sp \nDefault: Prints the 10 worlds with the lowest soul point timers");
```suggestion
            TextComponentString text = new TextComponentString("Usage: /s sp \nDefault: Prints 10 worlds with increasing soul point timers");
```

2022-02-15 18:41 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +import scala.tools.nsc.doc.base.comment.Text;
Assume this was just left there unintentionally, could you remove it?

2022-02-15 21:19 UTC, HighCrit requested changes
I'll be testing this somewhere later this week. I also strongly believe the for-loops and the use of various data structures can be lessened, which I will play with during testing.

2022-02-15 21:19 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            sender.sendMessage(text);
Why do the work if you're not gonna use it?

2022-02-15 21:19 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        } else {
You can flatten the if-statement by using a return in the if block and remove the else. But this is just a personal preference.

2022-02-15 21:19 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            TextComponentString soulPointInfo = new TextComponentString("Approximate soul point times:" + "\n");
Why have two separate strings?

2022-02-15 21:19 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                    case "nextsoulpoint":
I feel like no one will use this long arg.

2022-02-15 21:19 UTC, HighCrit commented on src/main/java/com/wynntils/webapi/profiles/ServerProfile.java
> +import java.util.concurrent.TimeUnit;
This doesn't seem to be used.

2022-02-15 21:19 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                            .setColor(TextFormatting.BLUE)
Didn't you already set the colour in the constructor?

2022-02-16 07:35 UTC, kristofbolyai commented
The request wanted you to move the help to the top of the function so you don't do useless computations, not remove the help.

2022-02-16 08:01 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +    private void nextSoulPoint(MinecraftServer server, ICommandSender sender, String[] args){
`server` argument is unused and could therefore be removed

2022-02-19 13:39 UTC, kristofbolyai commented
What even is this feature exactly? https://github.com/Wynntils/Wynntils/pull/451/commits/e6ddb4371387896512b268dfaa44b539cf6429bf

Also, add some pull request description about it and change the PR name althought I don't really like that you kinda change up your mind mid PR.

2022-02-19 13:41 UTC, kristofbolyai commented
> What even is this feature exactly? [e6ddb43](https://github.com/Wynntils/Wynntils/commit/e6ddb4371387896512b268dfaa44b539cf6429bf)

Oh, I kinda see now. I don't see how it could be used tho.

2022-02-19 13:46 UTC, HighCrit requested changes

2022-02-19 13:46 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        }
Or make the interval an optional variable with a default value of 20 minutes. Then this would be the exact same as the nextSoulPoint function

2022-02-19 14:28 UTC, kristofbolyai commented
No mobs spawn every x minutes tho? Rare spawns don't really have a timer but also like you can't know if someone spawned that rare mob.

2022-02-19 14:31 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        }
You can generify this if statement by moving the loop outside the else-block then in the if-block replace everything by `interval=20` which you'd need to declare above the if due to scopes.

2022-02-19 21:22 UTC, Incompleteusern requested changes
Very cool and its great that you did this! However, I ask for some changes.

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            sender.sendMessage(text);
Inline `text`

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        if(args[1]!=null){
Please add spacing to this and the other `!=`

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        if(args[1]!=null){
Another optional thing is to make this a ternary,  along with the other one

```java
offset = args[1] != null ? Integer.parseInt(args[1]) : 0;
```

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (uptimeMinutes == 1) {
This can also be a ternary

```java
world.appendText(" §b in " + minuteColor + uptimeMinutes + (uptimeMinutes == 1 ? " minute" : "minutes"));
```

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
Untab this once

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            interval = Integer.parseInt(args[2]);
I don't see the benefit of a non-20 interval, or an offset

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        Map<String, Integer> sortedServers = nextServers.entrySet().stream()
Perhaps use a `TreeMap` instead

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            int uptimeMinutes = sortedServers.get(wynnServer);
Use `entryset` instead of using keys. A suggestion is to add an arg for the number of keys to filter

2022-02-19 21:22 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (WebManager.getPlayerProfile().canUseSwitch()) {
Remove duplicated code
```java
TextComponentString serverLine = new TextComponentString(TextFormatting.BLUE + wynnServer);

if (WebManager.getPlayerProfile().canUseSwitch()) {        
    serverLine.getStyle()
            .setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/switch " + wynnServer))
            .setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString("Switch To " + TextFormatting.BLUE + wynnServer)));
} else {
    serverLine.getStyle()
            .setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString(TextFormatting.RED + "HERO or higher rank is required to use /switch")));

}

world.appendSibling(serverLine);

2022-02-19 21:27 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        if(args[1]!=null){
Also make sure you are respecting the array size while using indexes, make sure `args.length >= 1`.

2022-02-21 10:22 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        Map<String, Integer> sortedServers = nextServers.entrySet().stream()
What is the benefit of this?

2022-02-21 10:24 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +import org.w3c.dom.Text;
Unused import?

2022-02-21 10:24 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        HashMap<String, Integer> nextServers = new HashMap<>();
Use Map<String, Integer>

2022-02-21 10:24 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (WebManager.getPlayerProfile().canUseSwitch()) {
`TextComponentString serverLine = new TextComponentString(TextFormatting.BLUE + wynnServer);

if (WebManager.getPlayerProfile().canUseSwitch()) {        
    serverLine.getStyle()
            .setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/switch " + wynnServer))
            .setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString("Switch To " + TextFormatting.BLUE + wynnServer)));
} else {
    serverLine.getStyle()
            .setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString(TextFormatting.RED + "HERO or higher rank is required to use /switch")));

}

world.appendSibling(serverLine);`
This code is needed to be there? It makes it so if you have HERO rank or above, you can run /switch onclick but otherwise it shows you that you can't on hover

2022-02-21 10:25 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        HashMap<String, Integer> nextServers = new HashMap<>();
Also with this what is the benifit?

2022-02-21 13:48 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        Map<String, Integer> sortedServers = nextServers.entrySet().stream()
@Incompleteusern a TreeMap sorts the elements based on their keys not the values.

2022-02-21 14:13 UTC, HighCrit requested changes

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        }
No need to reduce `worlds`'s value `.limit(n)` deals with situations when stream size is less than n

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .collect(Collectors.toList());
Instead of `.collect` you can immediatly start the loop with `.forEach` and remove the assignment of the variable

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
If length equals three then the minimum possible maximum index is 2. But you try and access index 3 here :?

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
If length equals two then the minimum possible maximum index is 1. But you try and access index 2 here :?

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
If length equals one then the minimum possible maximum index is 0. But you try and access index 1 here :?

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                worlds = args[3] != null ? Integer.parseInt(args[2]) : 0;
You'll want to prevent negative numbers here, because IllegalArgumentExceptions will be thrown by `.limit(n)`

2022-02-21 14:13 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            world.appendText(" §b in " + minuteColor + uptimeMinutes + (uptimeMinutes == 1 ? " minute" : "minutes"));
Please be consistent with how you use colour codes. As you've used `TextFormatting` for everything else instead of `§`

2022-02-21 14:27 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        Map<String, Integer> sortedServers = nextServers.entrySet().stream()
ah

2022-02-21 14:45 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                if(!args[1].equalsIgnoreCase("help")){
This should always be true since you returned online 82

2022-02-21 14:48 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        HashMap<String, Integer> nextServers = new HashMap<>();
It generalizes the assignment and allows for replacement with another subtype (`LinkedHashMap`) later

2022-02-21 14:49 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .collect(Collectors.toList());
What does this mean?

2022-02-21 14:56 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                .collect(Collectors.toList());
No, need to create a list and assign it to a variable. Since the variable is only used once in the look in the next line. Therefore, we can immediately loop on the stream. e.g.
```java
sortedServers.entrySet().stream()
  .limit(worlds)
  .map(Map.Entry::getKey)
  .forEach(server -> { ... });
```

2022-02-21 15:30 UTC, HighCrit requested changes
Please make the commit title more descriptive.  Examples: "Implemented requested changes by HighCrit", "Incorporated feedback" or preferably "Fixed AIOOB, moved main loop"

2022-02-21 15:30 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (args[1].equalsIgnoreCase("help")) {
Combine these two if-statement

2022-02-21 15:30 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        if(args.length >= 2){
Please change the condition to be `> 1` this makes it more consistent with the line below and is functionally the same.

2022-02-21 15:30 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
>              if (args.length >= 2) {
Please change the condition to be `> 1` this makes it more consistent with the line below and is functionally the same.

2022-02-21 15:30 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (args.length >= 3) {
Please change the condition to be `> 2` this makes it more consistent with the line below and is functionally the same.

2022-02-21 15:30 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (args.length >= 4) {
Please change the condition to be `> 3` this makes it more consistent with the line below and is functionally the same.

2022-02-21 20:40 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            int time = interval - (ServerListManager.getServer(availableServer).getUptimeMinutes() % interval) - offset;
Why not loop over `ServerListManager.getAvailableServers()` such that you don't have to call `ServerListManager.getServer(...)` each iteration?

2022-02-23 13:28 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (WebManager.getPlayerProfile().canUseSwitch()) {
Yes, but it's duplicated, so try to extract it into a function or rewrite the code in a way that it is only there once.

2022-02-23 15:02 UTC, kristofbolyai requested changes
General thing I found while testing is that this feature does not really work for soul points. Offsets vary be server because of the way Athena and Wynntils logs servers. Some timers were really off (even 5 minutes) and generally, even being 1 minute off can hurt this feature. I know we have optional offsets, they do not work since the server start time is offset by a random amount for each server, so there is not a general offset that could be used for this. I can't think of any solution to this as of right now.

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        return "/s <command> [options]\n\ncommands:\nl,ls,list | list available servers\ni,info | get info about a server\nsp,nextsoulpoint | list servers with soul point timers\n\nmore detailed help
The help string is outdated, remove `nextsoulpoint`.

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        TextComponentString soulPointInfo = args.length > 1 ? new TextComponentString("Approximate soul point times(-" + offset + "min offset, " + interval + "min interval" + "):" + "\n") : new TextC
```suggestion
        TextComponentString soulPointInfo = args.length > 1 ? new TextComponentString("Approximate soul point times(-" + offset + "min offset, " + interval + "min interval" + "):" + "\n") : new TextComponentString("Approximate soul point times:");
```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                    if (WebManager.getPlayerProfile().canUseSwitch()) {
Nullcheck WebManager.getPlayerProfile() first.

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                                .setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString("Switch To " + TextFormatting.BLUE + server)));
```suggestion
                                .setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new TextComponentString("Switch to " + TextFormatting.BLUE + server)));
```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            sender.sendMessage(helpMessage);
Use something like:
```java
int messageId = Utils.getRandom().nextInt(Integer.MAX_VALUE);
ChatOverlay.getChat().printUnloggedChatMessage(new TextComponentString("Usage: /s info <serverID>"), messageId);
 ```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        try{
```suggestion
        try {
```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            offset = args.length > 1 && args[1] != null ? Integer.parseInt(args[1]) : 0;
At this point, that null check is not needed.

```suggestion
            offset = args.length > 1 ? Integer.parseInt(args[1]) : 0;
```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        int worlds = 10;
Remove redundant initializers.

```suggestion
        int offset;
        int interval;
        int worlds;
```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            worlds = args.length > 3 && args[3] != null ? Integer.parseInt(args[3]) : 10;
Also check for negative numbers.

![image](https://user-images.githubusercontent.com/49001742/155343891-4a1c02c9-4890-4815-93d9-be70928b8e8d.png)

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                    if (WebManager.getPlayerProfile().canUseSwitch()) {
Also extract the statement. Put this before `sortedServers.entrySet().stream()`.

```java
PlayerStatsProfile playerProfile = WebManager.getPlayerProfile();
boolean canUseSwitch = playerProfile != null && playerProfile.canUseSwitch();
 ```

2022-02-23 15:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                        TextComponentString serverLine = new TextComponentString(TextFormatting.BLUE + server);
You can declare `TextComponentString serverLine = new TextComponentString(TextFormatting.BLUE + server);` before the if statements.

2022-02-23 19:14 UTC, PhoenixImpulse commented
> General thing I found while testing is that this feature does not really work for soul points. Offsets vary be server because of the way Athena and Wynntils logs servers. Some timers were really off (even 5 minutes) and generally, even being 1 minute off can hurt this feature. I know we have optional offsets, they do not work since the server start time is offset by a random amount for each server, so there is not a general offset that could be used for this. I can't think of any solution to this as of right now.

Not quite sure why the timers were off, they were fine for me

2022-02-23 20:02 UTC, kristofbolyai requested changes

2022-02-23 20:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            if (offset < 0 || interval < 0){
```suggestion
            if (offset < 0 || interval < 0) {
```

2022-02-23 20:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +        } catch (NumberFormatException exception){
```suggestion
        } catch (NumberFormatException exception) {
```

2022-02-23 20:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
```suggestion
            if (time > interval) {
                time = time-interval;
            }
```

2022-02-23 20:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +            }
```suggestion
            if (time < 0) {
                time = interval - Math.abs(time);
            }
```

2022-02-23 20:16 UTC, DevChromium requested changes

2022-02-23 20:16 UTC, DevChromium commented on src/main/java/com/wynntils/modules/core/commands/CommandServer.java
> +                time = time-interval;
```suggestion
                time = time - interval;
```

2022-02-23 21:18 UTC, magicus commented
It's kind a serious if the feature does not work as advertised. :-/ Do we need more testing to confirm if this does or does not work?

2022-02-24 12:15 UTC, PhoenixImpulse commented
> It's kind a serious if the feature does not work as advertised. :-/ Do we need more testing to confirm if this does or does not work?

Can you test it a bit? Whenever I have used it, it has been pretty acurate

2022-03-03 23:07 UTC, Incompleteusern commented
> > General thing I found while testing is that this feature does not really work for soul points. Offsets vary be server because of the way Athena and Wynntils logs servers. Some timers were really off (even 5 minutes) and generally, even being 1 minute off can hurt this feature. I know we have optional offsets, they do not work since the server start time is offset by a random amount for each server, so there is not a general offset that could be used for this. I can't think of any solution to this as of right now.
> 
> Not quite sure why the timers were off, they were fine for me

I really don't know why the offsets are off. Athena logs the join time by itself and logs it every 30 seconds, so this means that either the code is wrong or Wynn api is behind

2022-03-21 10:00 UTC, PhoenixOrigin commented
Closing PR since there are some differences that makes this useless and also avomod has it now

2022-03-21 10:00 UTC, closed without merging