feat: add guild territory defense level sorting
Wynntils/Wynntils-Legacy pull request #463
Opened 2022-02-16 01:51 UTC by DonkeyBlaster

Adds a button to only show a certain difficulty of guild territory defense on the guild map. Currently uses the search icon, though this can be changed to anything else.

This PR also does some refactoring and changes how MapButtons are handled. Tested in game; seems to work fine.

2022-02-19 11:04 UTC, kristofbolyai reviewed
Looks good mostly, noted some things you should consider

2022-02-19 11:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapButton.java
> +        return Boolean.parseBoolean(String.valueOf(state.apply(null)));
This looks a bit strange, is there any better way to do this?

2022-02-19 11:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapTerritory.java
> +    }
Why does equals not work here? Perhaps strip color codes? Or is there an other reason (if so maybe state that in the comment)?

2022-02-19 11:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +    private int territoryDefenseFilter = 0; // 0=off; 1=verylow; 2=low; 3=med; 4=high; 5=veryhigh
Wouldn't an enum be more useful here?

2022-02-19 11:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        }
I personally prefer to use `TextFormatting` in cases like this, but it's up to you.

2022-02-19 11:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +                }
From what I see here, there is no way to filter like `Medium or higher` territories?

2022-02-19 11:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +                }
Also, maybe try doing something about nesting.

2022-02-19 11:06 UTC, kristofbolyai commented
Also, just to note, this PR `most likely` won't be merged in this release version. (Not anything related to the code, it looks awesome, we just want to follow our time schedule and don't want to merge anything without a few days of testing in CE)

2022-02-19 21:03 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapButton.java
> +        return Boolean.parseBoolean(String.valueOf(state.apply(null)));
Oh yeah I forgot to change this after I discovered .parseBoolean doesn't actually convert 1s and 0s

2022-02-19 21:04 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapTerritory.java
> +    }
No idea, I even printed both the unformatted and formatted text - they yielded the same results (the strings in the if/else right now), and neither worked with .equals() - I can try again in a bit

2022-02-19 21:04 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        }
Yeah I'll change this

2022-02-19 21:05 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapTerritory.java
> +    }
Use `StringUtils#stripColorCodes` from Minecraft to actually remove color codes, sometimes formatted and unformatted does not work as expected.

2022-02-19 21:17 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +                }
No way to filter med+higher, we could try something like shift-click to view that diff and higher?

2022-02-19 21:19 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +                }
> No way to filter med+higher, we could try something like shift-click to view that diff and higher?

Yeah, maybe that, or some kind of button for that aswell?

Not sure, leaving it up to you, just try to make it as intuitive as possible.

2022-02-19 22:03 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +    private int territoryDefenseFilter = 0; // 0=off; 1=verylow; 2=low; 3=med; 4=high; 5=veryhigh
I think we should keep this as int; it'll be more consistent with the rest of the buttons
With an enum, it'd probably make more sense to create an enum for all the defense levels in MapTerritory and reference that, but that'd prevent us from having an off state. If we included an off state in the enum, future uses on that enum would be difficult as it'd have to excluded the off state.

2022-02-22 17:44 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +                }
@DonkeyBlaster Are you planning on working on this or are you done with this PR?

2022-02-22 17:48 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +                }
Working, though I'm trying to fix my item highlights first

2022-02-27 09:26 UTC, kristofbolyai requested changes
Looks good! 

I have found two things that I find a bit strange:

- Should we disable trade routes when using the filter? 
![image](https://user-images.githubusercontent.com/49001742/155876452-ff1c352d-1cbc-4689-a710-6d1eb7ff8e73.png)
Doesn't that image look a bit weird? Maybe disable all trade routes or only have them between drawn territories? I am up for discussion on this one.

- A bug I found while using the filter: Guild map has the ability to run `/gu territory <territory>` when the user Shift + Right clicks on a territory. This currently works with territories that are filtered. I would expect this to only work with territories that are drawn on the screen.

2022-02-27 11:01 UTC, DonkeyBlaster commented
I'll look into how both of these work - preferably, we'd have trade routes show for the territories that do appear.

2022-03-02 14:04 UTC, kristofbolyai approved these changes

2022-03-08 17:49 UTC, Incompleteusern requested changes
a few things

2022-03-08 17:49 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapButton.java
> +    public MapButton(int posX, int posY, MapButtonIcon icon, List<String> hoverLore, Boolean isBool, Function<Void, Integer> state, BiConsumer<MapButton, Integer> onClick) {
replace `Function<Void, Integer> state` with `Supplier<Integer>`

2022-03-08 17:49 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +            // Remove redundant settings (Very low and lower, very high and lower, very low and higher, very high and higher)
Are `very high and lower` and `very high and higher` filtered/

2022-03-08 17:51 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +            // Remove redundant settings (Very low and lower, very high and lower, very low and higher, very high and higher)
What do you mean by filtered? Currently it's just not possible to reach that filter state

2022-03-08 23:52 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +            // Remove redundant settings (Very low and lower, very high and lower, very low and higher, very high and higher)
wdym?

2022-03-09 01:11 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +            // Remove redundant settings (Very low and lower, very high and lower, very low and higher, very high and higher)
Clicking through the options will skip everything in that comment

2022-03-09 17:39 UTC, Incompleteusern approved these changes

2022-03-13 19:17 UTC, HighCrit commented on src/main/java/com/wynntils/modules/map/overlays/ui/GuildWorldMapUI.java
> +        }
Personally would've opted for a method in the enum

2022-03-13 19:23 UTC, HighCrit commented on src/main/java/com/wynntils/modules/map/overlays/ui/WorldMapUI.java
> +    protected MapButton addButton(MapButtonIcon icon, int offsetX, List<String> hover, Boolean isBool, Supplier<Integer> state, BiConsumer<MapButton, Integer> onClick) {
Why did state become an integer if all use cases are in conditions?

2022-03-14 07:25 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WorldMapUI.java
> +    protected MapButton addButton(MapButtonIcon icon, int offsetX, List<String> hover, Boolean isBool, Supplier<Integer> state, BiConsumer<MapButton, Integer> onClick) {
I don't actually remember too well - I think I had a reason to do with how I was going to inform the user of which filter state was currently selected but the current implementation doesn't need it. I'll look at reverting it back to what we had before.

2022-03-14 17:06 UTC, merged