fix: Item overlay rendering relating to charge count
Wynntils/Wynntils-Legacy pull request #465
Opened 2022-02-21 23:04 UTC by DonkeyBlaster

- Added a check to the charge count overlay to see if items are actually in the hotbar
- Reverted ItemLevelOverlay to previous change to ensure level overlay hotkey still works with hotbar overlay config on
- Separated hotbar charge overlay to its own file to improve check logic

2022-02-22 17:49 UTC, DonkeyBlaster commented
Typo fixes is actually kind of questionable, I think that resets configs? Not sure

2022-02-23 12:01 UTC, kristofbolyai approved these changes, later dismissed

2022-02-23 12:01 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/HotbarChargeOverlay.java
> +        ItemStack is = event.getStack();
Rename this variable for clarity

2022-02-23 12:01 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/HotbarChargeOverlay.java
> +        if (McIf.player().inventory.mainInventory.contains(is) && McIf.player().inventory.mainInventory.indexOf(is) > 8) return;
Does this actually work with all inventories?

2022-02-23 12:02 UTC, kristofbolyai commented
Did not mean to approve just yet.

2022-02-23 13:37 UTC, kristofbolyai requested changes

2022-02-23 13:37 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/HotbarChargeOverlay.java
> +        if (McIf.player().inventory.mainInventory.contains(is) && McIf.player().inventory.mainInventory.indexOf(is) > 8) return;
It think it does, nevermind.

2022-02-23 13:37 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/HotbarChargeOverlay.java
> +        if (!(item == Items.POTIONITEM) || item == Items.DIAMOND_AXE) return; // Consumables are only potions or diamond axes (crafted)
```suggestion
        if (item != Items.POTIONITEM) && item != Items.DIAMOND_AXE) return; // Consumables are only potions or diamond axes (crafted)
```

Isn't this what you meant to do?

2022-02-23 18:33 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/HotbarChargeOverlay.java
> +        if (!(item == Items.POTIONITEM) || item == Items.DIAMOND_AXE) return; // Consumables are only potions or diamond axes (crafted)
Yup thanks lol, I just copied directly from the previous file without really looking at it too much

2022-02-23 20:50 UTC, kristofbolyai approved these changes

2022-02-28 10:06 UTC, magicus approved these changes

2022-02-28 12:58 UTC, merged