feat: Add guild member searching
Wynntils/Wynntils-Legacy pull request #468
Opened 2022-02-28 18:54 UTC by DonkeyBlaster

Copies implementation from guild territory searching

2022-02-28 18:58 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Searched Item Highlight Colour", description = "What colour should the highlight for searched items be?\n\n§aClick the coloured box to open the colour wheel.", order = 25)
Incorrect text here

2022-02-28 19:04 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Searched Item Highlight Colour", description = "What colour should the highlight for searched items be?\n\n§aClick the coloured box to open the colour wheel.", order = 25)
Wait where?

2022-02-28 19:06 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Searched Item Highlight Colour", description = "What colour should the highlight for searched items be?\n\n§aClick the coloured box to open the colour wheel.", order = 25)
It says searched item highlight color and not guild menu highlight color

2022-02-28 19:06 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Searched Item Highlight Colour", description = "What colour should the highlight for searched items be?\n\n§aClick the coloured box to open the colour wheel.", order = 25)
The one for guild territory says the same; I'll change them both

2022-02-28 19:06 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Searched Item Highlight Colour", description = "What colour should the highlight for searched items be?\n\n§aClick the coloured box to open the colour wheel.", order = 25)
Also perhaps use this color in territory manage overlay aswell if it doesnt have a separate setting

2022-02-28 20:20 UTC, CringeAura commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Show Guild Manage Member Search Bar", description = "Should the search bar be shown in the guild manage members GUI?\n\n§8Members that match the search will be highlighted
Do you know if the name of the setting is getting truncated in the menu? If it is, it should be shortened.

2022-02-28 21:11 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Show Guild Manage Member Search Bar", description = "Should the search bar be shown in the guild manage members GUI?\n\n§8Members that match the search will be highlighted
Yup a few of these are getting cut - fixed in next commit

2022-03-02 14:00 UTC, kristofbolyai approved these changes

2022-03-13 19:07 UTC, HighCrit requested changes

2022-03-13 19:07 UTC, HighCrit commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/GuildMemberManageOverlay.java
> +        }
Should this be higher in the function?

2022-03-14 07:45 UTC, HighCrit approved these changes

2022-03-14 17:02 UTC, merged