Ingredients sort/filter
Wynntils/Wynntils-Legacy pull request #478
Opened 2022-03-22 22:37 UTC by chrisstar321

Add the same sort/filter functionality that the items guide has for the ingredients guide

2022-03-23 20:49 UTC, kristofbolyai reviewed
Imo, favorited filter should only show favorited items. I know that this is not how it is in the normal items page, perhaps that should be changed as well. I would prefer feedback about this from others on the team though.
![image](https://user-images.githubusercontent.com/49001742/159793040-77744522-1ff6-4c9f-840d-cf2a77f8463a.png)

2022-03-23 20:49 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/ProfessionType.java
> +    public static ProfessionType from(String type) {
Rename this method to something clearer. `fromString` maybe?

2022-03-23 21:00 UTC, chrisstar321 commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/ProfessionType.java
> +    public static ProfessionType from(String type) {
The same method in `ItemType` is also called from. Should i change that one to `fromString` as well?

2022-03-23 21:02 UTC, chrisstar321 commented
> Imo, favorited filter should only show favorited items. I know that this is not how it is in the normal items page, perhaps that should be changed as well. I would prefer feedback about this from others on the team though. ![image](https://user-images.githubusercontent.com/49001742/159793040-77744522-1ff6-4c9f-840d-cf2a77f8463a.png)

Technically, the 'Favorited Items' is a sorting method and not a filter, though

2022-03-23 21:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/ProfessionType.java
> +    public static ProfessionType from(String type) {
Sure

2022-03-23 21:03 UTC, kristofbolyai commented
> > Imo, favorited filter should only show favorited items. I know that this is not how it is in the normal items page, perhaps that should be changed as well. I would prefer feedback about this from others on the team though. ![image](https://user-images.githubusercontent.com/49001742/159793040-77744522-1ff6-4c9f-840d-cf2a77f8463a.png)
> 
> Technically, the 'Favorited Items' is a sorting method and not a filter, though

Yeah, it's kinda a strange one Imo, we will see what others think.

2022-03-28 15:04 UTC, Incompleteusern commented on src/main/java/com/wynntils/core/utils/helpers/IngredientFilter.java
> +public interface IngredientFilter extends Predicate<IngredientProfile>, Comparator<IngredientProfile> {
surely its possible to have a general Filter class which both extend?

2022-03-28 15:11 UTC, Incompleteusern commented on src/main/java/com/wynntils/core/utils/helpers/IngredientFilter.java
> +public interface IngredientFilter extends Predicate<IngredientProfile>, Comparator<IngredientProfile> {
it might be nice to have a general interface which both extend

2022-03-28 15:11 UTC, Incompleteusern commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +            case "common":
who does this?

2022-03-28 19:25 UTC, chrisstar321 commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/IngredientTier.java
> +            case "common":
i used the same aliases as item rarities here, just in case someone wants to use those

2022-03-28 19:26 UTC, chrisstar321 commented on src/main/java/com/wynntils/core/utils/helpers/IngredientFilter.java
> +public interface IngredientFilter extends Predicate<IngredientProfile>, Comparator<IngredientProfile> {
i thought so too. I've been working on it a little, but there's a lot of small differences between items and ingredients, and i don't have a lot of free time, so that might take a while

2022-03-28 21:52 UTC, Incompleteusern commented on src/main/java/com/wynntils/core/utils/helpers/IngredientFilter.java
> +public interface IngredientFilter extends Predicate<IngredientProfile>, Comparator<IngredientProfile> {
ah, its fine both ways

2022-03-29 22:08 UTC, magicus commented
The file profession_icons.png seem to have a lot more than the profession icons in it? In fact, it looks like it could be copied from some other texture file. Is that the case? If so, it's better to use the icons directly from that texture.

2022-03-29 22:09 UTC, magicus commented
I've never used the ingredient guide, and have no strong opinion on favorite filters. Can't say much more about this PR.

2022-04-05 23:39 UTC, Incompleteusern approved these changes

2022-04-09 13:42 UTC, kristofbolyai requested changes
Fix this text's position, then we are good to merge. 
![image](https://user-images.githubusercontent.com/49001742/162576757-0fa5af4a-ee8f-4125-81d7-ce124b8f2ca5.png)

2022-04-09 13:42 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/ingredient/enums/ProfessionType.java
> +    int textureY;
These can be made final?

2022-04-27 18:29 UTC, kristofbolyai approved these changes

2022-04-27 18:30 UTC, merged