Fix quest links not opening in quest book for people using old Java
Wynntils/Wynntils-Legacy pull request #479
Opened 2022-03-26 19:16 UTC by kristofbolyai

Fixes `[wynntils-web-request-pool-0/INFO] [wynntils]: Error occurred whilst fetching WikiQuestQuery from https://wynncraft.gamepedia.com/index.php?title=Special:CargoExport&format=json&tables=Quests&fields=Quests._pageTitle&where=Quests.name=%27Poisoning+the+Pest%27: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` by
registering Lets Encrypt certificate on startup if java version is old.

2022-03-26 19:20 UTC, DevScyu requested changes

2022-03-26 19:20 UTC, DevScyu commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            if (needsPatching()) return;
Is this correct? Feels like it should read like this:
```java
            if (!needsPatching()) return;
``` 

of course, also update the function above to follow

2022-03-26 19:24 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            if (needsPatching()) return;
Messed up the name, but I feel like it is fitting, so I changed how the method works.

2022-03-26 19:54 UTC, DevScyu approved these changes

2022-03-28 16:27 UTC, Incompleteusern commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            Reference.LOGGER.info("Found java version " + javaVersion);
should this be merged

2022-03-28 16:29 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            Reference.LOGGER.info("Found java version " + javaVersion);
Are you suggesting that the java version checking could be done better or are you talking about the whole PR?

2022-03-28 19:02 UTC, Incompleteusern commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            Reference.LOGGER.info("Found java version " + javaVersion);
Im talking about the debug

2022-03-28 19:03 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            Reference.LOGGER.info("Found java version " + javaVersion);
I mean there is no harm in logging that if we need to see user logs?

2022-03-28 19:12 UTC, Incompleteusern commented on src/main/java/com/wynntils/webapi/WebManager.java
> +            Reference.LOGGER.info("Found java version " + javaVersion);
sure

2022-03-28 19:12 UTC, Incompleteusern approved these changes

2022-03-29 08:06 UTC, magicus commented
An alternative approach (which I argue we should use 100% in Artemis) is to let Athena query the wiki, and then publish the data for the mod from Athena instead.

In this case your solution is probably the simplest, but I think this issue really highlights why this is important.

2022-03-29 11:40 UTC, merged