Auto clear lootruns on delete
Wynntils/Wynntils-Legacy pull request #507
Opened 2022-05-02 19:12 UTC by PhoenixImpulse

Pretty simple, just a small addition that to my understanding should clear the lootrun shown if you use delete.

2022-05-02 19:21 UTC, DevChromium commented
Shouldn't there also be a check if the lootrun you want to delete is the active one?
If I'm doing a lootrun and I decide to delete a random one in my list, this piece of code would unload my current lootrun.

2022-05-02 19:47 UTC, kristofbolyai requested changes

2022-05-02 19:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                    sender.sendMessage(new TextComponentString(RED + "The provided lootrun doesn't exists!"));
No need to change this line, we print message later on without the return

2022-05-02 19:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                    return;
This line breaks code. Remove it

2022-05-02 19:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                if (LootRunManager.getActivePath() != null) {
Check if activepath is the deleted one, only clear if so

2022-05-03 16:55 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                    return;
It was intended to stop the further code from running in the case it doesn't exist and in turn clearing the active lootrun. So what does it break apart from what I made it do?

2022-05-03 16:56 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                if (LootRunManager.getActivePath() != null) {
Ok 👍

2022-05-03 16:56 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                    sender.sendMessage(new TextComponentString(RED + "The provided lootrun doesn't exists!"));
As shown in the message below

2022-05-03 16:59 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                    return;
Yes I know what return does but if you move the active path if check (the one below) to the correct place this return is not needed and the line above does not need to be changed

2022-05-03 17:00 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                    return;
Ok

2022-05-03 17:02 UTC, kristofbolyai requested changes

2022-05-03 17:02 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                if (LootRunManager.getActivePath() != null && LootRunManager.getActivePathName().equals(name) {
If missing a )?

2022-05-03 17:14 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
>                      message = RED + "The provided lootrun doesn't exists!";
```suggestion
                    message = RED + "The provided lootrun doesn't exist!";
```

2022-05-03 18:33 UTC, PhoenixImpulse commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                if (LootRunManager.getActivePath() != null && LootRunManager.getActivePathName().equals(name) {
done

2022-05-03 23:55 UTC, DonkeyBlaster approved these changes

2022-05-04 16:51 UTC, Incompleteusern approved these changes

2022-05-07 13:24 UTC, kristofbolyai approved these changes

2022-05-07 13:24 UTC, merged