Add "time held" to territory tooltip. Make territory borders dashed if cooldown
Wynntils/Wynntils-Legacy pull request #542
Opened 2022-07-03 18:12 UTC by byBackfish

Hey o/ 

The "time held" will show when hovering over a territory in the guild map. It will be listed below the defence of the territory.
The dashed borders are toggle-able in the "world map" settings.

So, most of the time i had to go to avicia.ml/map to see the "time held" of an territory so i could check if a territory is on cooldown (time held < 10min). 
This was very tedious so i have decided to add this to Wynntils 😃 

As this is my first time contributing to Wynntils, i assume that i have made a few mistakes, so just leave a review/comment here or message me on Discord (GithubCopilot#5701) if you have any suggestions! Thanks for reading!

2022-07-03 18:22 UTC, kristofbolyai requested changes
Small changes, but looks fine. Thank you for adding this! 🥳

2022-07-03 18:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +        if(dashed) {
```suggestion
        if (dashed) {
```

2022-07-03 18:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +        if(dashed) {
```suggestion
        if (dashed) {
```

2022-07-03 18:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +}
Add ending new line

2022-07-03 18:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +        void calculate() {
```suggestion
        private void calculate() {
```

2022-07-03 18:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +        public String makeReadable() {
maybe rename this to toString? or asString

2022-07-03 19:58 UTC, byBackfish commented
Thanks :D i hopefully "fixed" all those reviews now! Thanks for looking into this 😃

2022-07-04 18:45 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +
I think you can inline this.

2022-07-04 18:45 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +    }
Not a fan of this whole class tbh, is there not a Date/Time wrapper in Java?

2022-07-04 19:14 UTC, byBackfish commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +    }
not sure how else i could implement this. Would moving it out of its own class be fine?

2022-07-04 19:29 UTC, kristofbolyai commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +    }
Maybe have a Time saved as acquired and then you can use date formatters to get the text.

2022-07-04 19:58 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +    public boolean isOnCooldown(){
Separate for readability?

2022-07-04 19:59 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/webapi/profiles/TerritoryProfile.java
> +    public String getRelativeTimeAcquired() {
Maybe rename to getReadableRelativeTimeAcquired or something? getRelativeTimeAcquired implies a timestamp for me, not sure about everyone else

2022-07-05 14:53 UTC, magicus commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +                xMax = Math.max(x1, x2) + drawingOrigin.x,
What's with all these indentation changes? Did the old code not follow the convention, or has these been inadvertently changed by your editor?

2022-07-05 14:54 UTC, magicus commented on src/main/java/com/wynntils/core/utils/helpers/SimpleRelativeDateFormatter.java
> +        return new Date(0);
This does not look correct..?

2022-07-05 14:55 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapTerritory.java
> +import java.util.*;
I thougth we did not use `*` imports..? Or is it just in Artemis?

2022-07-05 14:59 UTC, byBackfish commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +                xMax = Math.max(x1, x2) + drawingOrigin.x,
Im fairly Sure that i did not change those. I even copied those lines from the Wynntils Repo and there seems to be no difference from my local project to the Wynntils Repo.

2022-07-05 15:00 UTC, byBackfish commented on src/main/java/com/wynntils/core/utils/helpers/SimpleRelativeDateFormatter.java
> +        return new Date(0);
well, parsing relative Rates was completly useless for this. If you think that this will have a use in the Future, then i can try and implement this

2022-07-05 15:00 UTC, byBackfish commented on src/main/java/com/wynntils/modules/map/overlays/objects/MapTerritory.java
> +import java.util.*;
oh alright, my Editor just automatically makes it a `*` Import when there are 3 or more Imports of the same package. Will change this

2022-07-05 15:01 UTC, magicus commented on src/main/java/com/wynntils/core/utils/helpers/SimpleRelativeDateFormatter.java
> +        return new Date(0);
Ah, is it an abstract function? Didn't realize. Better perhaps to throw `java.lang.UnsupportedOperationException` then.

2022-07-05 15:02 UTC, magicus commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +                xMax = Math.max(x1, x2) + drawingOrigin.x,
Well, the diff contains changes, so revert them if you did not intend them.

2022-07-05 15:02 UTC, magicus commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +                xMax = Math.max(x1, x2) + drawingOrigin.x,
It's likely your editor has some setting to reformat code. It might be a tab vs space issue.

2022-07-05 15:42 UTC, magicus commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +                xMax = x2 + drawingOrigin.x,
I still see intendation changes...

2022-07-05 16:41 UTC, byBackfish commented on src/main/java/com/wynntils/core/framework/rendering/ScreenRenderer.java
> +                xMax = x2 + drawingOrigin.x,
sorry, they dont show for me. Even when i copy-paste the wynntils code directly into my editor. Seems like it has something to do with my editor's settings then. Did my new commit fix them now?

2022-07-05 20:58 UTC, magicus approved these changes, later dismissed
This looks good now. Thanks for hanging in there!

2022-07-06 02:00 UTC, DonkeyBlaster approved these changes, later dismissed
LGTM

2022-07-06 14:21 UTC, kristofbolyai approved these changes, later dismissed

2022-07-06 14:24 UTC, byBackfish commented
oops, sorry for dismissing those reviews :/, i meant to push these a bit ago but simply forgot

2022-07-06 15:44 UTC, magicus approved these changes

2022-07-06 15:45 UTC, kristofbolyai approved these changes

2022-07-06 15:56 UTC, merged