Prevent closing chests with emeralds, amount of chest close preventions
Wynntils/Wynntils-Legacy pull request #544
Opened 2022-07-06 17:49 UTC by byBackfish

Implement [Favoriting emeralds and option for closing chest with favorite items](https://feedback.wynntils.com/posts/33/favoriting-emeralds-and-option-for-closing-chest-with-favorite-items)

You can set an amount of emeralds (per stack) there have to be for the emeralds to be marked as a favorite item and therefore preventing you from closing this chest.
You can set an amount of times Wynntils should prevent you from closing the chests. If its set to X, then you have to try and close the chest X times before Wynntils actually lets you close it.

2022-07-06 18:36 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +
Remove extra blank line

2022-07-06 18:37 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +    int timesClosed = 1;
This is a field. Make it private and move it to the top of the class.

2022-07-06 18:37 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                if(!preventedClose){
```suggestion
                if (!preventedClose) {
```
Also fix spaces in rest of code.

2022-07-06 18:41 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                if(!preventedClose){
i think all of them are fixed now! Thanks for the review

2022-07-06 19:02 UTC, magicus submitted a review, later dismissed

2022-07-07 23:01 UTC, DonkeyBlaster requested changes

2022-07-07 23:01 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Emerald Chest Closing", description = "Should the closing of loot chests be prevented when they contain emeralds?", order = 4)
This description needs to be reworded. It doesn't actually inform the user what the intlimit means, as the question is just a yes/no question.

2022-07-07 23:01 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public int preventFavoritedChestCloseTimes = 0;
What is the 0 setting supposed to do here?

2022-07-07 23:01 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                if(UtilitiesConfig.INSTANCE.preventFavoritedChestCloseTimes != 0 && timesClosed >= UtilitiesConfig.INSTANCE.preventFavoritedChestCloseTimes) {
```suggestion
                if (UtilitiesConfig.INSTANCE.preventFavoritedChestCloseTimes != 0 && timesClosed >= UtilitiesConfig.INSTANCE.preventFavoritedChestCloseTimes) {
```

2022-07-07 23:03 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public int preventFavoritedChestCloseTimes = 0;
setting it to 0 means that the chest can not be closed at all. Just like how it is right now

2022-07-07 23:04 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public int preventFavoritedChestCloseTimes = 0;
This should be in the description then. Check out other descriptions on how footnotes like these are added, I believe you can find them by searching up `\n\n` in config files.

2022-07-08 15:06 UTC, byBackfish commented
oops, i honestly dont know why and how i did the "Merge remote-tracking branch" thing. Sorry if it was something bad

2022-07-08 23:07 UTC, magicus submitted a review, later dismissed

2022-07-09 00:08 UTC, DonkeyBlaster approved these changes, later dismissed
LGTM after these two edits. Just shortening it a bit since the description text shouldn't cover up a significant portion of the page

2022-07-09 00:08 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Emerald Chest Closing", description = "How many emeralds should there be in a chest (in one stack) for Wynntils to prevent you from closing it?\n\n§8Set to 0 to disable th
```suggestion
    @Setting(displayName = "Emerald Chest Closing", description = "How many emeralds should there be in a chest (in one stack) for Wynntils to prevent you from closing it?\n\n§8Set to 0 to disable this completely.", order = 4)
```

2022-07-09 00:08 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Favorited Item Close Times", description = "How often should Wynntils prevent you from closing a chest with favorite items in it?\n\n§8Setting it to 0 will make you unable
```suggestion
    @Setting(displayName = "Favorited Item Close Times", description = "How many times should you click to force close a chest with favorite items in it?\n\n§8Setting this to 0 will disable this feature.", order = 4)
```

2022-07-09 12:19 UTC, DonkeyBlaster approved these changes, later dismissed

2022-07-09 15:06 UTC, HeyZeer0 requested changes
Small changes are required, the implementation at first seems a bit wonky. Replace the break on the loop with a return and send everything required. If the return is never called it means the chest was closed and then you are able to do a `timesClosed = 1`, I would suggest also changing the code to make by default `timesClosed = 0` but that's optional.

As always thanks for helping on Wynntils 🎉

2022-07-09 15:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +                if(UtilitiesConfig.INSTANCE.preventEmeraldChestClose != 0 && stack.getCount() >= UtilitiesConfig.INSTANCE.preventEmeraldChestClose) {
Space between the operator and the condition
```suggestion
                if (UtilitiesConfig.INSTANCE.preventEmeraldChestClose != 0 && stack.getCount() >= UtilitiesConfig.INSTANCE.preventEmeraldChestClose) {
```

2022-07-09 15:06 UTC, HeyZeer0 commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +                }
The boolean `preventedClose` is completely useless, you can simply add a `timesClosed++;` **BEFORE** the `event.setCancelled(true)` at line 627. I'm aware you are using this to reset the counter but this needs to be done when the chest actually closes.

2022-07-09 22:09 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            if (stack.getItem() == Items.EMERALD && stack.getDisplayName().contains("Emerald")) {
To make sense, you should sum up all emeralds in all slots, and check this total sum against the config value (which desciption needs to be updated to match this).

2022-07-09 22:48 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            if (stack.getItem() == Items.EMERALD && stack.getDisplayName().contains("Emerald")) {
I also thought about this, but i thought this would make much more sense. If i were to Set this to 32, then i would not want to be stopped in a chest containing 32 emeralds in total and then having to pick up multiple different emerald stacks and rather would only be stopped if the chest actually has 32 in one stack. This might just be personal preference tho. Maybe have another switch for this?

2022-07-09 22:52 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            if (stack.getItem() == Items.EMERALD && stack.getDisplayName().contains("Emerald")) {
especially not as this method is only called when the gui is opened (as far as i know). If there is a total of 32 emeralds in that chest, one stack with 31 and one stack with only 1 emerald, then both of them would be favorited and it would result in the user having to pick up that single emerald

2022-07-10 07:08 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            if (stack.getItem() == Items.EMERALD && stack.getDisplayName().contains("Emerald")) {
Ok, if you say...

2022-07-10 07:08 UTC, magicus submitted a review, later dismissed

2022-07-10 10:42 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/FavoriteItemsOverlay.java
> +            if (stack.getItem() == Items.EMERALD && stack.getDisplayName().contains("Emerald")) {
its up to you, i just think its better this way. But if you want i can change it

2022-07-11 01:37 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting.Limitations.IntLimit(min = 0, max = 64)
Afaik a emerald stacks actually only go up to 32 per stack, unless someone else can  confirm otherwise? The max limit should be 32 in that case

2022-07-11 07:16 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting.Limitations.IntLimit(min = 0, max = 64)
As in "how large stacks you can ever find in a loot chest"? Otherwise, emeralds of course stack to 64.

2022-07-11 13:19 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting.Limitations.IntLimit(min = 0, max = 64)
Yep that's what I meant

2022-07-11 14:30 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting.Limitations.IntLimit(min = 0, max = 64)
are you sure? i thought i found a "stack" of over 32 before. I could be wrong tho

2022-07-11 14:43 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting.Limitations.IntLimit(min = 0, max = 64)
okay. I asked some friends and they all said 32. gonna change that

2022-07-11 19:25 UTC, magicus approved these changes

2022-07-11 19:29 UTC, DonkeyBlaster approved these changes

2022-07-11 19:46 UTC, magicus approved these changes

2022-07-11 19:48 UTC, magicus commented
@HeyZeer0 I think you need to approve as well, since you has marked the PR as "changes requested".

2022-07-11 19:49 UTC, kristofbolyai commented
> @HeyZeer0 I think you need to approve as well, since you has marked the PR as "changes requested".

I swear there was a way to dissmiss reviews, can't find it though.

2022-07-11 20:02 UTC, magicus commented
Yeah, it's odd. I wonder if that is limited to someone with full admin rights like @DevScyu ?

2022-07-11 22:31 UTC, DevScyu approved these changes

2022-07-11 22:31 UTC, merged