Changed the character the down arrow uses in the 'Waypoint overview menu' from 'V' to 'ᵛ'. Added a new config option to change the amount of space between the data in the 'Waypoint overview menu'.
Wynntils/Wynntils-Legacy pull request #552
Opened 2022-07-27 17:39 UTC by playfuldoggo

Me and my friends have found the 'Waypoint overview menu' hard to navigate and hard to delete and look at many waypoints. I made this to try and add an option that would help with this issue. There are three options 'DEFAULT' (what it is currently), 'COMPACT' (the same sizes except with no space between the 'Edit...' and 'Delete' buttons) and 'DECREASED_SIZE' (smaller 'Edit...' and 'Delete' buttons, and smaller up arrow and down arrow buttons).

Hopefully this is all alright, please let me know if there is anything that needs changing or comments that need to be added.

I am also not sure whether or not the commits form my previous pull request matter or not as I have not re-cloned the repository since Jul 15.

2022-07-27 22:55 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +    private int[] spacingArr = {25, 20, 14};
Instead of having a separate array with constants and an index into this array, can't you just set the spacing multiplier in the WaypointSpacing enum constructor directly? And have a `getSpacingMultiplier` method instead of getting the index.

2022-07-27 22:56 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +            HORSE_TIME_ESTIMATE("Estimated time (in minutes) from current horse level to next horse level"),
Somehow this PR seems to contain the latest updates to the mainline. I don't know what happened, but try merging in the latest main.

2022-07-27 22:58 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            GuiButton down = new GuiButton(7 + 10 * i, this.width/2 + 172 + groupShift, 54 + spacingArr[sizeArrayIndex] * i + (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (d
This was originally based on 65, not 54 as the others. Is this change to 54 intentional?

2022-07-28 00:13 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            GuiButton down = new GuiButton(7 + 10 * i, this.width/2 + 172 + groupShift, 54 + spacingArr[sizeArrayIndex] * i + (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (d
Yes as there is 11 added to 54 for that one as to add space between the two arrow buttons, however the space between the arrow buttons needs to be changed by the settings so I separated it out, the default is now 63 * i instead of 65 * i , this was done on complete accident because I did 65 - 54 wrong, however I think it actually looks better than 65 * i

![2022-07-28_00 56 13](https://user-images.githubusercontent.com/83927732/181392343-9504216c-4e84-4b50-853d-ebda03d1b043.png)
![2022-07-28_00 54 30](https://user-images.githubusercontent.com/83927732/181392344-4090151c-eb34-4a88-94ed-d25f6890ca2e.png)

Smaller gap is the 63 * i, bigger gap is the 65 * i. I can change it so that the gap is the same as it was before on default if you would like.

2022-07-28 00:16 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +    private int[] spacingArr = {25, 20, 14};
I think this is what you wanted (latest commit). If you want me to just use the `getSpacingMultiplier` method everywhere instead of just putting it into an into and using that, I can.

2022-07-28 08:29 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +
Delete extra empty line

2022-07-28 08:31 UTC, magicus commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +    private int[] spacingArr = {25, 20, 14};
Yes, this look good.

2022-07-28 12:43 UTC, magicus submitted a review, later dismissed
This looks okay for me now.

2022-07-28 20:25 UTC, DonkeyBlaster requested changes

2022-07-28 20:25 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            DECREASED_SIZE(2),
![image](https://user-images.githubusercontent.com/57310593/181629872-5043dc3e-ca08-4751-a011-2fcd3bf4e6fc.png)

The DECREASED_SIZE option makes this menu completely broken - Text is overflowing out of the buttons and the icons do not line up at all.

2022-07-28 20:25 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            COMPACT(1),
Same goes for COMPACT - the text is fine, but the icons do not line up at all.

2022-07-28 20:25 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            private int[] spacingArr = {25, 20, 14};
What is the point of this int array? Could we not just do this?
```
DECREASED_SIZE(14),
COMPACT(20),
DEFAULT(25)
```

2022-07-28 20:25 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            private int[] spacingArr = {25, 20, 14};
Also if it is necessary, make it final please

2022-07-28 20:25 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            GuiButton down = new GuiButton(7 + 10 * i, this.width/2 + 172 + groupShift, 54 + spacingMultiplier * i + (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (decreasedS
![image](https://user-images.githubusercontent.com/57310593/181630658-4c27dd29-9e99-4b54-8dae-7c7a1eea5c6a.png)

Since you changed the character into the different `v`, if possible, could you line it up so it's consistent (vertically) with the `^`? It's fine if you can't, this isn't a huge issue imo

2022-07-31 16:05 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            DECREASED_SIZE(2),
Forgot to write anything about this in the most recent commit message, however the icons and the text should both be fixed in the most recent commit.

2022-07-31 16:08 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            GuiButton down = new GuiButton(7 + 10 * i, this.width/2 + 172 + groupShift, 54 + spacingMultiplier * i + (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (decreasedS
I don't seem to be able to as just trying to use a newline doesn't work with 'GuiButton'. There may be another way to line it up, if you find one then let me know.

2022-07-31 16:11 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            private int[] spacingArr = {25, 20, 14};
Removed the array and changed the values in the enum constructor to what was in the array.

2022-07-31 16:54 UTC, magicus approved these changes, later dismissed
The code looks okay to me

2022-07-31 22:06 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            GuiButton down = new GuiButton(7 + 10 * i, this.width/2 + 172 + groupShift, 54 + spacingMultiplier * i + (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (decreasedS
```suggestion
            GuiButton down = new GuiButton(7 + 10 * i, this.width/2 + 172 + groupShift, 54 + spacingMultiplier * i + (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), (int)Math.round(9 * (decreasedSize ? 0.75 : 1.0)), "\u1D5B"); // This is the ᵛ character
```

2022-07-31 22:06 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            DEFAULT(25);
Code looks fine now. I'm not sure we should name these the way they are right now. DECREASED_SIZE and COMPACT mean pretty much the same thing in my book, and there is no way for the user to determine which of the two are smaller, unless they go to the menu and check. I think something like LARGE, MEDIUM, and SMALL works just fine. No need to mention which is the default, because the "reset" button exists. Also, if you want to, you can make MEDIUM(20) the default.

2022-07-31 22:06 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            editButtons.add(new GuiButton(5 + 10 * i, this.width/2 + 130 + groupShift, 54 + spacingMultiplier * i, (int)Math.round(40.0 * (decreasedSize ? 0.9 : 1.0)), (int)Math.round(20.0 * (decreas
I think the text for decreasedSize could be even smaller, maybe by another 0.1 or 0.2. Also while we're here, I don't think the `...` is needed at the end of "Edit...".

2022-07-31 23:57 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            editButtons.add(new GuiButton(5 + 10 * i, this.width/2 + 130 + groupShift, 54 + spacingMultiplier * i, (int)Math.round(40.0 * (decreasedSize ? 0.9 : 1.0)), (int)Math.round(20.0 * (decreas
Looking at the javadocs for forge 1.12, the constructor for 'GuiButton' doesn't seem to have any variable that changes the size of the text itself. I have removed the '...' at the end of 'Edit'.

2022-07-31 23:57 UTC, playfuldoggo commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +            DEFAULT(25);
Changed the names of the variables and set the default to 'MEDIUM'.

2022-08-01 04:20 UTC, DonkeyBlaster approved these changes
LGTM

2022-08-01 13:57 UTC, magicus approved these changes

2022-08-01 13:57 UTC, merged