Add button to clear all waypoints
Wynntils/Wynntils-Legacy pull request #559
Opened 2022-08-11 19:39 UTC by byBackfish

Implements [Auto delete waypoints button](https://feedback.wynntils.com/posts/51/auto-delete-waypoints-button)

![image](https://user-images.githubusercontent.com/38255215/184224942-4524f7be-9f56-4bc6-850c-354011118bfb.png)

2022-08-12 09:26 UTC, DonkeyBlaster commented
From what I can tell, this doesn't actually delete the waypoints from cloud and they just reappear after a relaunch. I think you will need to deal with `MapConfig.Waypoints.INSTANCE.waypoints` (L288; same file).

2022-08-12 11:34 UTC, byBackfish commented
> From what I can tell, this doesn't actually delete the waypoints from cloud and they just reappear after a relaunch. I think you will need to deal with `MapConfig.Waypoints.INSTANCE.waypoints` (L288; same file).

I thought `onWaypointChange()` would sync them? I tested it and even after restarting, they did not re-appear

2022-08-12 11:36 UTC, byBackfish commented
I'll look into it tho. Thanks for letting me know

2022-08-13 06:16 UTC, DonkeyBlaster reviewed
Last few things, then I think it's good

2022-08-13 06:16 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            if(clearCount == clearCountMax){
```suggestion
            if (clearCount == clearCountMax){
```

2022-08-13 06:16 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +    final int clearCountMax = 3;
Explicitly declare private for consistency

2022-08-13 06:16 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +        this.buttonList.add(clearBtn = new GuiButton(9, 25, this.height - 45, fontRenderer.getStringWidth("CLEAR (Press " + clearCountMax + " times)") + 15, 20, "CLEAR (Press " + clearCountMax + " ti
Explicit width declaration or wrap the two usages of that string into one variable

2022-08-13 23:51 UTC, DonkeyBlaster approved these changes, later dismissed

2022-08-19 09:42 UTC, kristofbolyai requested changes

2022-08-19 09:42 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            if(clearCount == clearCountMax){
Space after if.

2022-08-19 09:42 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +            if(clearCount == clearCountMax){
And before {

2022-08-19 09:42 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointOverviewUI.java
> +                clearBtn.displayString = "CLEAR (Press " + (clearCountMax-clearCount) + " times)";
clearCountMax - clearCount

2022-08-19 22:13 UTC, DonkeyBlaster approved these changes, later dismissed

2022-08-23 20:33 UTC, DonkeyBlaster commented
You should fix merge conflicts before requesting review

2022-08-30 15:13 UTC, kristofbolyai approved these changes

2022-08-30 16:26 UTC, DonkeyBlaster approved these changes

2022-08-30 16:28 UTC, merged