Add ability to load multiple lootruns at once
Wynntils/Wynntils-Legacy pull request #561
Opened 2022-08-17 16:04 UTC by byBackfish

Implement [Ability to load more then 1 lootrun at once.](https://feedback.wynntils.com/posts/34/ability-to-load-more-then-1-lootrun-at-once)

2022-08-17 23:07 UTC, DonkeyBlaster requested changes

2022-08-17 23:07 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +                if (LootRunManager.getActivePath().isEmpty()) {
Refactor getActivePath() to getActivePaths() or something of the sort

2022-08-17 23:07 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/commands/CommandLootRun.java
> +            case "current": {
This needs to be added to the `/lr help` command.

2022-08-17 23:07 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/managers/LootRunManager.java
>      public static void clearOnlyLoaded() {
Remove unused method

2022-08-17 23:07 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/managers/LootRunManager.java
> +    public static void unloadLootrun(String name) {
Since this already exists, would be nice to see `/lr unload`, similar to `/lr load`

2022-08-17 23:08 UTC, DonkeyBlaster commented
Would also be nice to see lootruns being colored differently to each other. All of them being the same shade of blue is messy

2022-08-18 05:44 UTC, byBackfish commented
> Would also be nice to see lootruns being colored differently to each other. All of them being the same shade of blue is messy

Yea, that would be a nice idea. I'll look into it and then make it a setting I guess. I think having no way to turn that off wouldn't be that great in some cases

2022-08-19 10:27 UTC, DonkeyBlaster requested changes
Also, `/lr` (the usage exception) does not list the new commands.

2022-08-19 10:27 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +        @Setting(displayName = "Show different colors if multiple", description = "Should paths be colored differently if multiple lootruns are active?\nDoes not work with rainbow paths enabled", ord
```suggestion
        @Setting(displayName = "Differentiate Path Colors", description = "Should paths be colored differently if multiple lootruns are active?\nDoes not work with rainbow paths enabled", order = 4)
```

2022-08-19 10:27 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/configs/MapConfig.java
> +        public boolean differentColorsMultipleLootruns = false;
I think having this on by default is better. As far as I can tell there is no drawback to doing so.

2022-08-19 10:27 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/managers/LootRunManager.java
> +        return CommonColors.colors[index];
This needs to be changed. CommonColors.colors[0] is black, which can be difficult to see in dark areas. I think making your own list here with suitable colors (brighter ones) would be better. This also allows CommonColors.colors to stay private.

2022-08-20 00:02 UTC, DonkeyBlaster approved these changes
This looks good in-game. However, lootruns that mark the same chests will result in the chest only being marked one color. I personally think this is a nonissue, but not sure about everyone else.

2022-08-20 13:54 UTC, magicus approved these changes

2022-08-20 13:55 UTC, merged