Draw Waypoints as beacon beams
Wynntils/Wynntils-Legacy pull request #562
Opened 2022-08-17 17:53 UTC by byBackfish

Implement [waypoints on hud with beams](https://feedback.wynntils.com/posts/17/waypoints-on-hud-with-beams)

Draws a beacon beam on the location of each waypoint. Toggle-able

2022-08-17 22:54 UTC, DonkeyBlaster commented
Not a huge fan of this implementation. I feel like this is too basic to be useful in most situations.

The main issue I have with this is that you can't control what types or groups of waypoints are given a beacon. This can prove less than useful for those that record all chests, including T1 and T2. Honestly, even with just my T3/T4, it is quite overwhelming and waypoints with actual purpose (eg. gathering spot markers) lose meaning.

I would love to see a couple things such as
- Ability to select groups of waypoints instead of a global on/off switch (maybe a custom gui? with check boxes like the chat tab gui?)
- Option to have beacons display Y location data similarly to journeymap
- Option to only display beacons within a certain radius of the player
- Option to have certain groups or waypoints have their names visible

2022-08-18 05:48 UTC, byBackfish commented
Actually, now that I think about it, adding a checkbox to each individual waypoint would be nice. This way you can make only the most important waypoints render a Beacon. And then making waypoints marked as "always show" (I forgot what it's actually called right now), always render, and the rest only rendering if the player is near. 
What are you thoughts on that?

2022-08-18 06:23 UTC, DonkeyBlaster commented
Sounds good, though I still think there should be a way to mark a batch/group of waypoints to show up with beacon

2022-08-18 16:57 UTC, byBackfish commented
I hope i did not forget to add something of the list you made. If I did, please let me know

2022-08-18 16:59 UTC, byBackfish commented
![image](https://user-images.githubusercontent.com/38255215/185452539-c5b4250e-7ec1-45ea-b32d-19f91e831af7.png)

2022-08-18 16:59 UTC, byBackfish commented
^ global beacon beam settings menu

2022-08-18 17:03 UTC, kristofbolyai commented
> ![image](https://user-images.githubusercontent.com/38255215/185452539-c5b4250e-7ec1-45ea-b32d-19f91e831af7.png)
> 
> 

How does that top text look in smaller windows?

2022-08-18 17:16 UTC, byBackfish commented
> > ![image](https://user-images.githubusercontent.com/38255215/185452539-c5b4250e-7ec1-45ea-b32d-19f91e831af7.png)
> 
> How does that top text look in smaller windows?

Good point. I split it up into two lines now, as long as you are playing on a reasonable resolution, you wont have any problems not being able to see the text fully

2022-08-19 10:32 UTC, DonkeyBlaster commented
![image](https://user-images.githubusercontent.com/57310593/185600318-fbe07a3a-8404-456b-9bb4-9995beb154ec.png)

Empty category in config book?

2022-08-19 10:34 UTC, DonkeyBlaster commented
![2022-08-19_03-33-3](https://user-images.githubusercontent.com/57310593/185600630-814d4a44-64fd-4962-b908-412874d7e382.gif)
The buttons here do a funny thing where they just decide to resize themselves

2022-08-19 10:41 UTC, DonkeyBlaster commented
Also, I think you should add some text letting the user know that by default, waypoints will only render when the player is close to them. I was kind of confused when I enabled everything and no beams appeared. Could be done under/near the existing text in the group selection screen?

2022-08-19 12:15 UTC, byBackfish commented
Yep, this commit should fix/implement those things. Thanks for the feedback

2022-08-20 12:00 UTC, DonkeyBlaster commented
This feels decent in-game now. I will look at the code tomorrow

2022-08-21 09:00 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointCreationMenu.java
> +        } else if(button == toggleBeaconBeam) {
```suggestion
        } else if (button == toggleBeaconBeam) {
```

2022-08-21 09:00 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointCreationMenu.java
> +        buttonList.add(toggleBeaconBeam = new GuiButton(104, this.width/2 - 150, this.height/2 + 10, 18, 18, beaconBeam ? ChatFormatting.GREEN + "✔" : ChatFormatting.RED + "╳"));
```suggestion
        buttonList.add(toggleBeaconBeam = new GuiButton(104, this.width/2 - 150, this.height/2 + 10, 18, 18, beaconBeam ? ChatFormatting.GREEN + "✔" : ChatFormatting.RED + "X"));
```

I am pretty sure other X buttons in Wynntils are just a standard `X`

2022-08-21 09:00 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointBeaconGroupMenu.java
> +    if(b == doneButton) {
```suggestion
    if (b == doneButton) {
```

2022-08-21 09:00 UTC, ryanzhoudev commented on src/main/java/com/wynntils/modules/map/managers/NametagManager.java
> +  private static void drawNametag(String text) {
Would like to see some spacing in this method. Maybe even a comment. Just looking to improve readability.

2022-08-21 10:36 UTC, magicus approved these changes

2022-08-21 10:37 UTC, magicus requested changes

2022-08-21 10:37 UTC, magicus commented on src/main/java/com/wynntils/modules/map/instances/WaypointProfile.java
> +        this.name = name; this.x = x; this.y = y; this.z = z; this.color = color; this.type = type; this.zoomNeeded = zoomNeeded; this.showBeaconBeam = showBeaconBeam;
The code quality tool complains about this, and I actully agree. You need one assignment per line. I realize this is not new code, but please fix it.

2022-08-21 10:51 UTC, magicus submitted a review, later dismissed

2022-08-21 16:38 UTC, DonkeyBlaster reviewed
I think this is good after these few spacing fixes.

2022-08-21 16:38 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointBeaconGroupMenu.java
> +  public String getText(WaypointProfile.WaypointType type){
```suggestion
  public String getText(WaypointProfile.WaypointType type) {
```

2022-08-21 16:38 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointBeaconGroupMenu.java
> +    doneButton = new GuiButton(0,this.width/2-fontRenderer.getStringWidth("Done"), this.height - 100, 45, 18, "Done");
```suggestion
    doneButton = new GuiButton(0, this.width/2-fontRenderer.getStringWidth("Done"), this.height - 100, 45, 18, "Done");
```

2022-08-21 16:38 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointBeaconGroupMenu.java
> +    for(WaypointProfile.WaypointType type : WaypointProfile.WaypointType.values()){
```suggestion
    for (WaypointProfile.WaypointType type : WaypointProfile.WaypointType.values()) {
```

2022-08-21 16:38 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/overlays/ui/WaypointBeaconGroupMenu.java
> +  void save(){
```suggestion
  void save() {
```

2022-08-21 16:58 UTC, DonkeyBlaster approved these changes

2022-08-21 19:12 UTC, magicus approved these changes

2022-08-21 19:13 UTC, merged

2022-11-06 20:57 UTC, Endermity commented
Maybe this needs some new features?
https://feedback.wynntils.com/posts/145/add-option-to-change-the-render-distance-for-waypoint-beam