Add trade market sell amount display/overlay
Wynntils/Wynntils-Legacy pull request #563
Opened 2022-08-18 17:05 UTC by byBackfish

Pretty self explanatory
![image](https://user-images.githubusercontent.com/38255215/185453621-0fc3d2ab-8306-4371-8b95-2d55eb1f7ee1.png)

2022-08-18 18:45 UTC, magicus commented
Is the idea to help the user set the right amount?

Can't you take it a step further, so if you e.g. right click on the amount button, the determined amount is sent as a chat message?

2022-08-18 19:33 UTC, byBackfish commented
> Is the idea to help the user set the right amount?
> 
> Can't you take it a step further, so if you e.g. right click on the amount button, the determined amount is sent as a chat message?

Good idea. I do not know why i did not think of this earlier. Ty for the suggestion

2022-08-19 09:41 UTC, DonkeyBlaster commented
https://feedback.wynntils.com/posts/21/a-sell-all-button

2022-08-19 09:45 UTC, kristofbolyai requested changes

2022-08-19 09:45 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/TradeMarketOverlay.java
> +    public void onRender(GuiOverlapEvent.ChestOverlap.HandleMouseClick e) {
Can we get some new lines? This code feels so crammed.

2022-08-19 09:45 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/TradeMarketOverlay.java
> +        System.out.println(itemStack.getDisplayName());
Debug line?

2022-08-19 12:16 UTC, magicus commented
> https://feedback.wynntils.com/posts/21/a-sell-all-button

@DonkeyBlaster Thanks for doing the work with confirming approval from the Wynncraft team, for this and other potential additions!

2022-08-19 12:21 UTC, magicus commented
@byBackfish You misunderstood me. I meant that Wynntils should take care of sending the reply in chat for the user. That is, if the user right clicks on the plus, Wynntils will do the following:
 * Fake a click on the "+" icon.
 * Send the amount of items as a chat message sent *from* the user.

I realize right-clicking might be both harder to do, and less visible, so maybe a better way to trigger this would be to add an additional "+" icon below (or above, whichever looks best), give it the tooltip "Add all items of this kind", and when that is clicked, do the "dance" above.

If this needs to much knowledge of Wynntils inner workings for you to pull off, you can go with the current solution. But if possible, I think it would be much nicer to have.

2022-08-19 12:23 UTC, magicus commented
(Also, that new "+" item could have the number you are going to add as index/"amount") so you can directly see the result of your action before doing it.

2022-08-19 14:53 UTC, byBackfish commented
@magicus oh alright. I tried my best, hope this is fine
![image](https://user-images.githubusercontent.com/38255215/185646464-d2f01b9b-002e-422f-b04b-f72e7afac227.png)

2022-08-19 15:10 UTC, byBackfish commented
Actually, I thought an Emerald would look nicer than the "+", but how about making it a green checkmark?

2022-08-19 15:38 UTC, magicus commented
Yeah, the "+" was just a suggestion. If there were a kind of "++" icon, I think that'd be the best, but whatever. I think the check mark should be reserved for executing the sale. 

The drawback with the emerald is that it is already used to signal setting the price. 

Maybe using a full pouch icon?

2022-08-19 15:43 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/TradeMarketOverlay.java
> +        nbt.setInteger("Count", 1);
Try setting this to `amountToSend`. It should work up to 64 at least, I believe. I don't know if our code to display higher values is general enough to pick this up, but maybe. It's better than nothing, I think.

2022-08-19 15:44 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/TradeMarketOverlay.java
> +        lore.appendTag(new NBTTagString("§7Click to sell all items in your inventory"));
```suggestion
        lore.appendTag(new NBTTagString("§7Click to sell all " + getAmount(itemName) + " items in your inventory"));
```

2022-08-19 15:54 UTC, magicus commented
If you want to test the ingredient pouch idea, set `id` to `minecraft:diamond_axe` and `Damage` to `93`. Unfortunately, I did not have a character with a full ingredient pouch (and no time to fill one up right now), so I can't give you a damage value for the full pouch icon.

2022-08-19 16:16 UTC, byBackfish commented
Yea, I have those damage values but thanks! Wouldn't it be better to make it a full emerald pouch instead of a full ingredient pouch?

2022-08-19 16:45 UTC, magicus commented
Maaaaaybe...? But I think my point here is that the first two slots is what you sell (item + amount), and the third is the price. And that "price" is associated with emeralds, but the other two are not. So I think the association with emeralds is a bit odd; it feels more like "set a maximum price" or so, rather than "sell all that I got". 

Ideally, I think we should have some kind of stacking +:es, something along these lines: http://svn.slimdevices.com/repos/jive/7.7/trunk/squeezeplay/assets/MasterIcons/icon_add_all.png. But creating new icons is tricky and kind of out of the scope for this PR.

2022-08-19 17:24 UTC, byBackfish commented
Once the count is above 64, the item just simply does not display. It now uses 64 if the amount would be above 64.

![image](https://user-images.githubusercontent.com/38255215/185674105-fe6311fd-6722-4ad2-bd33-b8952dadd420.png)

2022-08-19 17:25 UTC, magicus commented
I think this looks great! :-)

2022-08-19 17:25 UTC, magicus submitted a review, later dismissed

2022-08-19 17:27 UTC, magicus commented
(An alternative would be to set count to 1 if above 64, to have no number at all instead of an incorrect. But I'm not even sure that's better.)

2022-08-19 23:48 UTC, DonkeyBlaster approved these changes, later dismissed
Very nice

Actually, you could make a few of the methods in TradeMarketOverlay private. (getAmount, getItemName, buildNBT)

2022-08-20 00:11 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/TradeMarketOverlay.java
> +
Thinking about it a bit more... Maybe it only makes sense to display this icon if you have more than one item to sell? So if `getAmount(itemName) <= 1` you'd just return here. What do you think? Or do we always want this icon, even if you have only a single object of that kind?

2022-08-20 11:48 UTC, DonkeyBlaster approved these changes, later dismissed

2022-08-20 13:53 UTC, magicus submitted a review, later dismissed

2022-08-20 13:55 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/inventories/TradeMarketOverlay.java
> +        if(itemName == null) return;
```suggestion
        if (itemName == null) return;
```

2022-08-20 13:56 UTC, kristofbolyai approved these changes

2022-08-20 13:57 UTC, magicus approved these changes

2022-08-20 21:11 UTC, merged