Auto changelog + Curseforge deployment
Wynntils/Wynntils-Legacy pull request #571
Opened 2022-09-08 22:12 UTC by DevScyu

2022-09-08 23:36 UTC, magicus commented on .pre-commit.js
> +    const replaceAll = (startPath, filter, searchValue, replaceValue) => {
What is the purpose of this?

2022-09-09 05:10 UTC, HighCrit requested changes

2022-09-09 05:10 UTC, HighCrit commented on .github/workflows/release.yml
> +          game_versions: "Minecraft 1.12:1.12.2,java:Java 8,Forge"
The docs advise to use the numerical ids https://github.com/itsmeow/curseforge-upload#api-method just like the curseforge docs

2022-09-09 05:10 UTC, HighCrit commented on .github/workflows/release.yml
> +      - name: Build
It also seems a bit waste full to do a second build of the project. Is there no way to reuse it?

2022-09-09 06:40 UTC, HighCrit commented on .pre-commit.js
> +const fs = require("fs");
Could we not use sngrep to get the version number from build.gradle? Or set the version in build.gradle using environment variables?

2022-09-09 08:05 UTC, HighCrit commented on .github/workflows/release.yml
> +          game_versions: "Minecraft 1.12:1.12.2,java:Java 8,Forge"
Example: https://github.com/null511/MCRP-Textureless/blob/501dcc639dce1e39247dc51c95443808e11dbeac/.github/workflows/Release.yml#L67

2022-09-09 11:38 UTC, merged