add currently active shaman mask display
Wynntils/Wynntils-Legacy pull request #577
Opened 2022-09-11 19:51 UTC by byBackfish

Adds an overlay that displays the currently active shaman mask. Only displays if you are a shaman. Has an option to fully remove the title that Wynncraft displays on mask swap

Preview: (moved it to the center of the screen, not there by default)
![image](https://user-images.githubusercontent.com/38255215/189546372-9f560ae2-23f9-45f6-88b1-66cf743ae1bc.png)
![image](https://user-images.githubusercontent.com/38255215/189546381-7813b8fd-44d7-458f-8071-ac246b4d46e4.png)
![image](https://user-images.githubusercontent.com/38255215/189546384-22e0e67e-b200-4f2d-b2c0-bfb7abf48a24.png)
![image](https://user-images.githubusercontent.com/38255215/189546390-14c860a5-0deb-4e04-a581-4599aec5410b.png)

2022-09-13 09:17 UTC, kristofbolyai commented
Does this overlay disappear? Or does it stay for the full duration?

2022-09-13 09:31 UTC, byBackfish commented
It's supposed to show you what mask you are currently on, so it stays forever (unless you switch class or are not a shaman)

2022-09-13 15:04 UTC, byBackfish commented
The mask don't expire btw (at least I think they don't), you swap to them and then you keep them until you either disable it, /class or die

2022-09-14 08:03 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +        public String displayStringAwakened = "%mask% mask equipped";
new lines?

2022-09-14 08:03 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +    super("Current shaman mask overlay", 66, 10, true, 0.66f, 1f, -10, -38, OverlayGrowFrom.BOTTOM_RIGHT);
All capitalized?

2022-09-14 08:05 UTC, kristofbolyai commented
Please use conventional name for the PR too (chore,fix,feat,docs).

2022-09-14 13:05 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +public class CurrentMaskOverlay extends Overlay {
This whole file looks like it is tabulated differently than other files. Can you check?

2022-09-16 17:57 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +public class CurrentMaskOverlay extends Overlay {
I feel like this whole class has many checks that look a bit "loose". `parseSingle`, `parseMultiple`, `onTitle`. Is there a better way to handle all of this? (This will also help with future updates, as currently the code currently has so many state checks.)

2022-09-16 18:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
How can this even happen?

2022-09-16 18:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
```suggestion
        else if (title.startsWith("§8")) currentMask = MaskType.NONE;
        else if (matcher.matches()) currentMask = MaskType.find(matcher.group(1));
```

2022-09-16 18:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
Sometimes it is enough to parse the title. sometimes full name is shown?

2022-09-16 18:54 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
so. There are 3 masks in total. And then the "ultimate" (awakened mask) combines all other 3 masks. It only activates once you spend X amount of mana. 

Those 3 masks are seperate upgrades tho. So if you only have one mask unlocked, it will show `Mask of the <MaskName>`. But if you have multiple, it will show the masks listed like `L ➤F ➤ C` or just `L ➤ F` if you dont have the third one. 
And if you activate the awakened mask, it will show `Mask of the Awakened` with some fancy styling

2022-09-16 18:56 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
And there is not a single regex to handle this?

2022-09-16 18:56 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
if you have multiple, the mask that you activate is colored, the other ones are just gray. Thats why I check for the color code + then the shortened mask name.

That was also why it was called `parseSingle` (if you only had 1 unlocked) and `parseMultiple` (if you had multiple) before

2022-09-16 19:00 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
Yeah, my previous review might not have been that clear. I had no issues with having `parseMultiple` and `parseSingle` separated, my worry was that checking for a color code and a char at many places feels unsafe.

2022-09-16 19:00 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
> And there is not a single regex to handle this?

How do these mask activations look ingame?

2022-09-16 19:01 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
![image](https://user-images.githubusercontent.com/49001742/190712172-47f4bbac-8683-4608-a8de-0ae63e9260f3.png)
Like this?

2022-09-16 19:05 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
yea, thats what i looks like when you have multiple unlocked

2022-09-16 19:06 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +        else if(matcher.matches()) currentMask = MaskType.find(matcher.group(1));
![image](https://user-images.githubusercontent.com/38255215/190712809-f00de37a-01c2-4097-8c68-05ac85669828.png)
this is it if you only have one unlocked

2022-09-16 19:06 UTC, kristofbolyai submitted a review, later dismissed

2022-09-18 09:15 UTC, HighCrit commented on src/main/java/com/wynntils/modules/core/events/ClientEvents.java
> +        CurrentMaskOverlay.currentMask = CurrentMaskOverlay.MaskType.NONE;
Why not do this as in the lines above instead of directly setting it at the consumers? Because if we want to make this an info variable we could easily fetch if from `CharacterData`.

2022-09-18 09:15 UTC, HighCrit commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +        public String displayStringAwakened = "%mask% mask equipped";
Is it really neccessary to have 5 different customizable notification strings? I'd say at most 1 is required.

2022-09-18 09:18 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/configs/OverlayConfig.java
> +        public String displayStringAwakened = "%mask% mask equipped";
I personally really like being able to customize each mask.
For example:
I have the awakened mask set to `&c&k||&r &f&lAWAKENED&r &c&k||`
and when I have no mask, I set it to a very big and very long text so I actually notice that I forgot to equip a mask. And I sometimes forget what the others masks do, so I have it set to `Lunatic (DPS) (-> Fanatic)`, so it tells me what the mask is for, and what the next mask would be

2022-09-18 14:03 UTC, HighCrit requested changes

2022-09-18 14:03 UTC, HighCrit commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/CurrentMaskOverlay.java
> +    public void onTitle(PacketEvent<SPacketTitle> e) {
If we move the data to CharacterData the Overlay should no longer be responsible for getting/parsing it.

2022-09-20 14:02 UTC, HighCrit approved these changes, later dismissed

2022-09-20 18:21 UTC, byBackfish commented
hopefully fixed those merge conflicts... i have no idea if it worked, first time using the github "tool" for that

2022-09-20 20:25 UTC, DonkeyBlaster approved these changes, later dismissed
Tried it in-game, seems good to me

2022-09-21 10:07 UTC, magicus commented on src/main/java/com/wynntils/modules/utilities/instances/ShamanMaskType.java
> +}
```suggestion
}

```

2022-09-21 10:43 UTC, magicus approved these changes, later dismissed

2022-09-21 14:25 UTC, kristofbolyai approved these changes

2022-09-21 14:53 UTC, DonkeyBlaster approved these changes

2022-09-21 14:59 UTC, magicus approved these changes

2022-09-21 15:32 UTC, merged