feat: ability tree navigation using scroll wheel
Wynntils/Wynntils-Legacy pull request #582
Opened 2022-09-15 20:44 UTC by byBackfish

Adds the ability to use the scroll wheel to navigate up and down in the ability tree

Suggestion: [add scrolling support to ability tree](https://feedback.wynntils.com/posts/102/add-scrolling-support-to-ability-tree)

2022-09-15 21:01 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (!lowerInv.getName().endsWith("Abilities")) return;
Is this spoofable with bank names?

2022-09-16 12:30 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        if (!lowerInv.getName().endsWith("Abilities")) return;
i don't think so, but I added a regex pattern check now 👍

2022-09-16 18:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Scrolling in Ability Tree", description = "Should using the scroll wheel in the ability tree move a page down/up?", order = 5)
Order is same as the config before

2022-09-16 18:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +    private static final Pattern ABILITY_TREE_PATTERN = Pattern.compile("(Warrior|Shaman|Mage|Assassin|Archer) Abilities");
Does this work with reskinned classes?

2022-09-16 18:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        int scrollAmount = Mouse.getDWheel() / 120;
The 120 is a magic number to me. Can you describe what it is? (and perhaps extract it into a named const for clarity)

2022-09-16 18:04 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        int slot = up ? 57 : 59;
See my comment on magic numbers. (I get that these two numbers are the up and down arrow slots in the GUI, but still, extract it and give it a name.)

2022-09-16 18:29 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +    private static final Pattern ABILITY_TREE_PATTERN = Pattern.compile("(Warrior|Shaman|Mage|Assassin|Archer) Abilities");
yes, the ability tree name always takes the non-reskinned version

2022-09-16 18:45 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        int scrollAmount = Mouse.getDWheel() / 120;
honestly, I don't know why exactly 120, when I first looked up how to detect the direction of the mouse scroll, someone told me to divide it by 120. But it does not really make sense, as I only check if its above 0 or not, and dividing it by 120 wont change anything with that. I'll remove that 120 then

2022-09-16 18:54 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        int scrollAmount = Mouse.getDWheel();
Doesn't the event contain relevant information about scroll?

2022-09-16 18:57 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +        int scrollAmount = Mouse.getDWheel();
nope, it only tells you that an action with the mouse was made, and does not tell you what action

2022-09-16 19:02 UTC, kristofbolyai submitted a review, later dismissed

2022-09-16 20:15 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/events/ClientEvents.java
> +    private static final Pattern ABILITY_TREE_PATTERN = Pattern.compile("(Warrior|Shaman|Mage|Assassin|Archer) Abilities");
Change to non-capturing group? Doesn't look like the class name is used

2022-09-17 09:25 UTC, kristofbolyai submitted a review, later dismissed

2022-09-18 09:19 UTC, HighCrit requested changes, later dismissed

2022-09-18 09:19 UTC, HighCrit commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public boolean invertAbilityScroll = false;
Please use https://github.com/Wynntils/Wynntils/blob/development/src/main/java/com/wynntils/modules/core/config/CoreDBConfig.java#L37

2022-09-18 09:20 UTC, byBackfish commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public boolean invertAbilityScroll = false;
Should I use the same config field, or should I just change the type of the `invertAbilityScroll` from a boolean to that enum?

2022-09-18 09:50 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public boolean invertAbilityScroll = false;
Use the enum

2022-09-19 02:06 UTC, DonkeyBlaster approved these changes, later dismissed

2022-09-20 14:12 UTC, HighCrit commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    public boolean invertAbilityScroll = false;
@kristofbolyai I meant it as in the field. Such that the scroll experience is consistent across all Wynntils features

2022-09-21 10:08 UTC, magicus approved these changes, later dismissed

2022-09-21 14:58 UTC, magicus approved these changes

2022-09-21 15:00 UTC, DonkeyBlaster approved these changes

2022-09-21 15:13 UTC, merged