Utils Placeholders  V1
Wynntils/Wynntils-Legacy pull request #620
Opened 2022-10-28 18:39 UTC by Radi0o

Hi, i have added some placeholders and changed some there is a list of things i have done

**Info Component Changes**
- Added the %travel% placeholder (Traveling time to get to the beacon parsed in duration)
- Added the %travel_raw% placeholder (Traveling time to get to the beacon in seconds)

**Game Update Component Changes**
- Renamed the %pc% placeholder to %pc_raw%
- Added the %pc% placeholder (the %pc_raw% placeholder but parsed)

**Leveling Component Changes**
- Added the %grindtime% placeholder (Griding time to get to the next level)
- Renamed the %max% placeholder to %max_raw%
- Renamed the %actual% placeholder to %actual_raw%
- Renamed the %maxg% placeholder to %max_rawg%
- Reanamed the %actualg% placeholder to %actual_rawg%

**Util Functions**
- Added a duration parser (DurationintegerToShortString() function)
- Added a function to get the traveling time (getTravelingTime() function)

Also i would like to be a Wynntils Developper if its possible

2022-10-28 18:41 UTC, Radi0o commented
If you want me to add something please tell me

2022-10-28 18:47 UTC, DevScyu reviewed
Please remove empty lines throughout the code.

2022-10-28 18:47 UTC, DevScyu commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +
Please remove empty lines

2022-10-28 18:47 UTC, DevScyu commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +
Please remove empty lines

2022-10-28 18:47 UTC, DevScyu commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +
Please remove empty lines

2022-10-28 18:47 UTC, DevScyu commented on src/main/java/com/wynntils/core/framework/instances/data/CharacterData.java
> +
Please remove empty lines

2022-10-28 18:47 UTC, kristofbolyai reviewed
Firstly, run you changed code through some code formatter. You have a lot of stylistic issues I did not point out 1 by 1.

Secondly, do not change info variable names. I don't mind if you add new obviously, but let's not break everyone's config.

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +
Why random new spaces?

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +
Random spaces

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +        if((!(required == 0)) && (!(perminute == 0))){
You can simplify this :)

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +        if((!(required == 0)) && (!(perminute == 0))){
You also only need to check if perminute is 0. You can divide zero by x and not get an exception.

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +            if(!(bps == 0)){
I am not sure why you don't use `!=`

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +        if(!(compass == null)){
!=

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +    public static String DurationintegerToShortString(int count){
I am pretty sure there is something like this somewhere in the code-base. Anyways I am sure I can't tell you where. However the method naming is wrong, use lowerCamelCase.

2022-10-28 18:47 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +                return "" + count / 3600 + "h";
String.valueOf() so you don't need to "" + ?

2022-10-28 18:48 UTC, kristofbolyai commented
> Also i would like to be a Wynntils Developper if its possible

You have to contribute enough so you stand out and you get an internship invitation.

2022-10-28 18:48 UTC, Incompleteusern commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +                return "" + count / 3600 + "h";
I don't think the valueOf is even needed either

2022-10-28 18:49 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/instances/InfoFormatter.java
> +
Closing as duplicate of scyu's comment

2022-10-28 18:49 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +
Same comment

2022-10-28 18:51 UTC, kristofbolyai commented
Also, please rename your PR. You are adding info overlay and levelling overlay variables, so make sure your PR title says that.

2022-10-28 18:52 UTC, Incompleteusern commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +
extra space

2022-10-28 18:54 UTC, Incompleteusern commented
The idea of the time needed to get time for grinding and time for travelling are novel, nice!

2022-10-28 18:54 UTC, kristofbolyai commented
Other than the changes, thank you for your contribution. 

I see you want to work on "Wynntils-Reloaded" (as your fork title says). Maybe you should try to contribute to https://github.com/Wynntils/Artemis. Artemis is 1.18.2 rewrite of Wynntils, and will likely replace this version of Wynntils when the porting is finished.

2022-10-28 18:56 UTC, Zffu commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +
sorry

2022-10-28 18:59 UTC, Radi0o commented
When i mean Wynntils Reloaded i mean the 1.12.2 version also im gonna fix the extra spaces and unnedded code

2022-10-28 19:09 UTC, Radi0o commented
i think i solved everything

2022-10-28 19:16 UTC, Incompleteusern commented
> i think i fixed everything

Still haven't resolved the `valueOf` comment, but everything else seems to be resolved, thanks!

2022-10-28 19:17 UTC, Radi0o commented
oh lemme fix that rq

2022-10-28 19:23 UTC, Radi0o commented
i removed the "" at the start of the return

2022-10-28 19:25 UTC, kristofbolyai requested changes

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        if(count < 60){
```suggestion
        if (count < 60){
```

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +            if(count > 3600){
```suggestion
            if (count > 3600){
```

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +            return "" + count + "s";
remove "" +

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +        if(perminute != 0){
```suggestion
        if (perminute != 0){
```

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +                return (int) ((int)distance / bps);
Why the double int cast?

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +                return (int) ((int)distance / bps);
```suggestion
                return (int) (distance / bps);
```

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +        if(compass != null){
```suggestion
        if (compass != null) {
```

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +    public static int getTravelingTime(){
```suggestion
    public static int getTravelingTime() {
```

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +    }
You can remove these elses and return 0 at the end of the method.

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                        .replace("%pc_raw%", df.format(xpchange)));
You did not revert the changes. I asked you to not change old variables, but add new.

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/LevelingOverlay.java
> +                    .replace("%needed_rawg%", GROUPED_FORMAT.format(data.getXpNeededToLevelUp() - data.getCurrentXP()))
Revert these too.

2022-10-28 19:25 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/LevelingOverlay.java
> +                    .replace("%max_raw%", "" + data.getXpNeededToLevelUp())
This too

2022-10-28 19:27 UTC, Radi0o commented
ok

2022-10-28 19:27 UTC, Radi0o commented
i can rename the new ones to %max_formated% and %actual_formated% ?

2022-10-28 19:28 UTC, kristofbolyai commented
> i can rename the new ones to %max_formated% and %actual_formated% ?

Sure. That way old variables will function the same, but there will be new, formatted ones.

2022-10-28 19:31 UTC, Radi0o commented
done

2022-10-28 19:34 UTC, Radi0o commented
fixed the elses and other things

2022-10-28 19:53 UTC, kristofbolyai commented
@Radi0o check open conversations

2022-10-28 19:55 UTC, Radi0o commented
i resolved them

2022-10-28 20:01 UTC, Radi0o commented
i gtg rn i will add more things tomorrow i already have some cool ideas

2022-10-28 21:46 UTC, DonkeyBlaster requested changes

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        if (count < 60){
```suggestion
        if (count < 60) {
```

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +        if(perminute != 0){
```suggestion
        if (perminute != 0) {
```

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +            if(bps != 0){
```suggestion
            if (bps != 0) {
```

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/managers/SpeedometerManager.java
> +        if(compass != null){
```suggestion
        if (compass != null) {
```

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        else {
Please inline your `else` clauses with the closing bracket of the previous `if` clause to be consistent with the rest of our code.
`} else {`

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +import ibxm.Player;
Unused import?

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
> +     * Get Excepted Grind Time for leveling up
Excepted or expected?
```suggestion
     * Get expected grind time for leveling up
```

2022-10-28 21:46 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/LevelingOverlay.java
> +                    .replace("%actual_formated%", StringUtils.integerToShortString(data.getCurrentXP()))
Please fix the typo `formated` to `formatted`. There are a couple more instances of this a few lines down.

2022-10-29 06:15 UTC, Radi0o commented
fixed

2022-10-29 06:31 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +                return count / 3600 + "h";
maybe switch to `else if`?

2022-10-29 06:57 UTC, Radi0o commented
Done fixing the typos

2022-10-29 06:58 UTC, Radi0o commented
and the else if

2022-10-29 08:12 UTC, Radi0o reviewed
fixed

2022-10-29 08:14 UTC, Radi0o commented
@DonkeyBlaster if i have more variables to add did i need to make a new pull request?

2022-10-29 08:19 UTC, kristofbolyai commented
> @DonkeyBlaster if i have more variables to add did i need to make a new pull request?

If you don't stop updating PRs then it is never gonna get merged (change requests don't count). You should make a new PR.

2022-10-29 08:19 UTC, kristofbolyai commented
Generally you should only open a PR if you are happy with the changes, it works, and it is semi-final version.

2022-10-29 08:21 UTC, Radi0o commented
ok

2022-10-29 08:22 UTC, kristofbolyai requested changes

2022-10-29 08:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        }
Again the whole method formatting is a mess. Format it

2022-10-29 08:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/managers/LevelingManager.java
>   */
Let's just remove this whole comment imo

2022-10-29 08:22 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                        .replace("%pc_raw%", df.format(xpchange)));
Why did you mark this completed? You changed what %pc% does and added it back as %pc_raw%.

2022-10-29 08:23 UTC, Radi0o commented
oh i forgot to change this one

2022-10-29 08:25 UTC, Radi0o commented on src/main/java/com/wynntils/core/utils/StringUtils.java
> +        }
ok

2022-10-29 08:28 UTC, Radi0o commented
i formated the StringUtils function and reverted the %pc% variable

2022-10-31 18:35 UTC, DonkeyBlaster reviewed
Tried it in-game, seems fine

2022-10-31 18:35 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                        .replace("%pc_formatted%", com.wynntils.core.utils.StringUtils.integerToShortString((int) xpchange))
Please import this properly

2022-10-31 18:35 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/overlays/hud/LevelingOverlay.java
> +                    .replace("%nextlvl%", data.getLevel() == 104 ? "" : "" + (data.getLevel() + 1))
```suggestion
                    .replace("%nextlvl%", data.getLevel() == 106 ? "" : "" + (data.getLevel() + 1))
```

2022-11-01 09:51 UTC, Radi0o commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                        .replace("%pc_formatted%", com.wynntils.core.utils.StringUtils.integerToShortString((int) xpchange))
i cant there is another StringUtils class imported

2022-11-01 09:52 UTC, Radi0o commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +                                        .replace("%pc_formatted%", com.wynntils.core.utils.StringUtils.integerToShortString((int) xpchange))
nevermind i found a way

2022-11-01 20:58 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/overlays/OverlayEvents.java
> +
Remove random blank line

2023-03-28 09:45 UTC, closed without merging