feat: Hide pets messages
Wynntils/Wynntils-Legacy pull request #626
Opened 2022-10-29 09:57 UTC by Radi0o

[+] Added the "Hide Pets Messages" Option on the utilities category
[+] The pets messages (example: pet: *test*) will not be displayed if the "Hide Pets messages" option is enabled

2022-10-29 12:41 UTC, DevScyu commented on src/main/java/com/wynntils/modules/chat/events/ClientEvents.java
> +        } else if((UtilitiesConfig.INSTANCE.hidePetsMessages) && (McIf.getUnformattedText(e.getMessage()).matches("(.*): *(.*)*"))){
This regex is not specific enough and will match more than intended.

2022-10-29 13:06 UTC, Radi0o commented on src/main/java/com/wynntils/modules/chat/events/ClientEvents.java
> +        } else if((UtilitiesConfig.INSTANCE.hidePetsMessages) && (McIf.getUnformattedText(e.getMessage()).matches("(.*): *(.*)*"))){
i just realised that a few minutes ago im gonna fix this when im home

2022-10-29 13:58 UTC, Radi0o commented
fixed

2022-10-31 17:42 UTC, DonkeyBlaster requested changes

2022-10-31 17:42 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/chat/events/ClientEvents.java
> +        } else if((UtilitiesConfig.INSTANCE.hidePetsMessages) && (PET_MESSAGE.matcher(McIf.getFormattedText(e.getMessage())).matches())) {
Please fix the formatting and redundant parentheses.

2022-10-31 17:42 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +    @Setting(displayName = "Hide Pet Messages", description = "Should Wynntils Hide the Messages from pets", order = 35)
```suggestion
    @Setting(displayName = "Hide Pet Messages", description = "Should Wynntils hide the messages from pets?", order = 35)
```

2022-10-31 17:53 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/chat/events/ClientEvents.java
> +    private static final Pattern PET_MESSAGE = Pattern.compile("§2(.*): §a*(.*)*");
Also, please fix your regex. There is no need for the capture groups, and this currently matches more than necessary. You can use https://regexr.com/71b0a, I have created a few tests for you, but you should do your own testing as well.

2022-11-01 16:24 UTC, ryanzhoudev commented
@Radi0o why did you resolve the regex comment without solving the problem? This cannot be merged until that is fixed

2022-11-02 08:05 UTC, Zffu commented
i changed the regex and make some tests ingame and pets messages are not showing up like intended

2022-11-02 14:31 UTC, Radi0o commented on src/main/java/com/wynntils/modules/chat/events/ClientEvents.java
> +    private static final Pattern PET_MESSAGE = Pattern.compile("§2(.*): §a*(.*)*");
fixed

2022-11-02 16:44 UTC, DonkeyBlaster commented
> i changed the regex and make some tests ingame and pets messages are not showing up like intended

What does this mean? I am still not sure why you are marking the issue as resolved and saying it is "fixed" when there have been zero changes

2023-03-28 09:45 UTC, closed without merging