feat: Add Lootrun Variables
Wynntils/Wynntils-Legacy pull request #627
Opened 2022-10-29 15:06 UTC by Radi0o

**Info Variables Changes**
- Added the %slc% and %session_lootrun_chests% variables (The amount of opened chests in a lootrun in the playing session)
- Added the %lname% and %lootrun_name% variables (The name of the current lootrun)
- Added the %sl% and %session_lootruns% variables (The amount of lootruns done in the playing session)
- Added the %lc% and %lootrun_chests% variables (The amount of chests loaded in the current lootrun)
- Added the %lp% and %lootrun_points% variables (The amount of points loaded in the current lootrun)
- Added the %loc% and %lootrun_opened_chests% variables (The amount of opened chest during the current lootrun)

2022-10-29 21:06 UTC, DonkeyBlaster commented on src/main/java/com/wynntils/modules/map/events/ClientEvents.java
> +        if(LootRunManager.isLootrunLoaded()){
```suggestion
        if (LootRunManager.isLootrunLoaded()) {
```
Please be consistent with your formatting.

2022-10-31 09:02 UTC, Radi0o commented
is there anything i need to modify ?

2022-10-31 17:35 UTC, DonkeyBlaster commented
![image](https://user-images.githubusercontent.com/57310593/199072375-8ccef04c-7dbe-4b22-a52f-a1e7d977d7f1.png)

After unloading a lootrun, the %lname% variables does not reset. Additionally, before loading a lootrun, the %lname% variable displays as `%lname`. These should both be fixed; the lname variable should reset to `N/A` or `-` when nothing is loaded.

2022-10-31 17:37 UTC, DonkeyBlaster commented
Additionally, the %lname% variable only displays the most recently loaded lootrun, even though it is possible to load multiple runs. Maybe something like `name1, name2`?

Also, %SLC% tracks all chests opened when a lootrun is loaded, not just chests in the lootrun. Is this intentional?

2022-11-01 07:35 UTC, Radi0o commented
yes %slc% variable is the number of lootrun chests opened during the playing session

2022-11-01 07:36 UTC, Radi0o commented
and for the %lname% variable i can make a list of every lootrun loaded

2022-11-01 07:37 UTC, Radi0o commented
imma fix the %slc% chest bug

2022-11-01 07:41 UTC, Radi0o commented
imma fix the bugs first and then add multi lootruns comptability

2022-11-01 08:09 UTC, Zffu commented
It will display that when no lootrun is loaded 
![image](https://user-images.githubusercontent.com/103074097/199187896-56d41bc1-7fca-42b7-a30f-8a8b17cb7d9b.png)

2022-11-01 08:12 UTC, Radi0o commented
Display when there is multiple lootruns

![image](https://user-images.githubusercontent.com/103074097/199188467-8bc1e794-1781-4b9c-9af6-6609542df6be.png)

2022-11-01 08:31 UTC, Radi0o commented
I am adding a hashmap for every opened chest on specific lootruns so when you disable a lootrun it removes only the chest you have opened on this lootrun

2022-11-01 08:55 UTC, Radi0o commented
i think im gonna remove the %loc% variable because its not very useful and it can be confusing with player location

2022-11-01 16:10 UTC, DonkeyBlaster requested changes
You are changing code that is not within the scope of this PR. (OverlayEvents, ConsumableTimerOverlay, DynamicTimerContainer, TabListData). Looks like you reverted a recent PR in your own branch. Please fix.

2022-11-02 08:08 UTC, Radi0o commented
how to do that ?

2022-11-02 08:18 UTC, Radi0o commented
im gonna reopen a pull request when i finished reverting

2022-11-02 08:18 UTC, closed without merging