fix: Powders & pouches not favouriting with Arabic numerals, missing T10 pouch
Wynntils/Wynntils-Legacy pull request #642
Opened 2022-11-18 00:57 UTC by DonkeyBlaster

- Adds missing T10 pouch
- Fixes powder and pouch name changes with the Arabic numeral setting, which was originally intended for item specification overlays

2022-11-18 01:00 UTC, Incompleteusern requested changes
Tier 10 has 6 rows instead of 1 row

2022-11-18 02:16 UTC, Incompleteusern approved these changes

2022-12-08 12:44 UTC, kristofbolyai commented on src/main/java/com/wynntils/modules/utilities/configs/UtilitiesConfig.java
> +        // This is only for the item specification overlays, do not use anywhere else
We really did fix the emerald pouch roman / nonroman numeral favorite bug this way. Okay. I guess this works..

2022-12-08 12:44 UTC, kristofbolyai approved these changes

2022-12-08 23:46 UTC, merged